# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u1a', "A. Daha Hızlı, Daha Yüksek, Daha Güçlü: Olimpiyatlar — Olimpiya o'yinlari", 10, 19,
    goals=[
        "Hikâye (-mIştI, -(I)yordu) va rivayet (-mIşmIş) birikma zamonlarini farqlash",
        "Olimpiya o'yinlari va sport lug'atini qo'llash",
        "Sport tarixi haqidagi matnni tushunish va qisqacha so'zlab berish",
    ],
    blocks=[
        ("Hikâye birleşik zamanı: -mIştI, -(I)yordu, -(y)AcAktI",
         "Fe'lning zamon shakliga -(y)DI qo'shilsa, voqea o'tmishda sodir bo'lgan holatga aylanadi. Gelmişti (kelgan edi), çalışıyordu (ishlayotgan edi), yapacaktı (qiladigan edi). Hikâye zamonlari o'tmishdagi bir voqeadan oldin yoki u bilan bir vaqtda bo'lgan ishni bildiradi: Maça geldiğimde oyun başlamıştı. (Uchrashuvga kelganimda o'yin boshlangan edi.)"),
        ("Rivayet birleşik zamanı: -mIşmIş, -(I)yormuş",
         "-(y)mIş qo'shimchasi eshitilgan yoki o'zi guvoh bo'lmagan ma'lumotni bildiradi: İlk olimpiyat M.Ö. 776'da yapılmış. (Birinchi olimpiada mil. avv. 776-yilda o'tkazilgan ekan.) Öğretmen hastaymış. (O'qituvchi kasal ekan.) Bu shakl tarixiy hikoyalarda va xabar uzatishda keng qo'llanadi."),
        ("Şart birleşik zamanı: -mIşsA, -(I)yorsA",
         "Shart shakli zamon shakliga -sA qo'shib yasaladi: çalışmışsa (agar ishlagan bo'lsa), kazanıyorsa (agar yutayotgan bo'lsa). Hikâye va şart birga ishlatilib, \"agar shunday bo'lganida\" ma'nosi hosil bo'ladi: Antrenman yapmış olsaydı, kazanırdı."),
    ],
    facts=[
        "Hikâye: -mIştI, -(I)yordu, -(y)AcAktI — o'tmishdagi holat yoki voqeadan oldingi ish.",
        "Rivayet: -mIş / -(I)yormuş — eshitilgan yoki guvoh bo'lmagan ma'lumot.",
        "Olimpiya shiori: Citius, Altius, Fortius (Daha hızlı, daha yüksek, daha güçlü).",
        "Zamonaviy olimpiya o'yinlari 1896-yilda Afinada boshlangan.",
    ],
    vocab=[
        ("olimpiyat", "olimpiada", "Olimpiyat oyunları dört yılda bir yapılır.", "Olimpiya o'yinlari to'rt yilda bir o'tkaziladi."),
        ("madalya", "medal", "Takım altın madalya kazandı.", "Jamoa oltin medal yutdi."),
        ("şampiyon", "chempion", "Türkiye Avrupa şampiyonu oldu.", "Turkiya Yevropa chempioni bo'ldi."),
        ("rekor", "rekord", "Atlet yeni bir dünya rekoru kırdı.", "Sportchi yangi jahon rekordini yangiladi."),
        ("antrenman", "mashg'ulot", "Her sabah antrenman yapıyorlar.", "Ular har ertalab mashq qilishadi."),
        ("antrenör", "murabbiy", "Antrenör sporcuları tebrik etti.", "Murabbiy sportchilarni tabrikladi."),
        ("yarışma", "musobaqa", "Yarışma stadyumda yapılacak.", "Musobaqa stadionda o'tkaziladi."),
        ("sporcu", "sportchi", "Genç sporcular kampa katıldı.", "Yosh sportchilar yig'inda qatnashdi."),
        ("mücadele", "kurash", "İki takım büyük bir mücadele verdi.", "Ikki jamoa katta kurash olib bordi."),
        ("zafer", "g'alaba", "Zafer taraftarları coşturdu.", "G'alaba muxlislarni jo'shtirdi."),
        ("elemek", "saralab chiqarmoq", "Takım ilk turda elendi.", "Jamoa birinchi bosqichda saralab tashlandi."),
        ("kupa", "kubok", "Kaptan kupayı havaya kaldırdı.", "Sardor kubokni osmonga ko'tardi."),
    ],
    reading=("Olimpiyatların öyküsü",
        "Antik çağda Olimpiyat Oyunları, Yunanistan'daki Olimpiya kentinde Zeus onuruna yapılırmış. İlk oyunların M.Ö. 776'da düzenlendiği söylenir. O dönemde savaşlar bile oyunlar süresince durdurulurmuş. Oyunlara yalnızca özgür erkekler katılabiliyormuş ve kazananlara zeytin dalından yapılmış bir taç verilirmiş.\n\nİmparator I. Theodosius oyunları yasaklamış, böylece yaklaşık bin yıl süren gelenek sona ermişti. Modern Olimpiyat Oyunları'nı ise Fransız Baron Pierre de Coubertin yeniden canlandırdı. İlk modern oyunlar 1896'da Atina'da yapıldı; o zaman yalnızca on dört ülke yarışmıştı. Bugün iki yüzü aşkın ülke Olimpiyatlar'a katılıyor.\n\nOlimpiyat halkaları beş kıtayı simgeler. \"Daha hızlı, daha yüksek, daha güçlü\" sözü ise sporcuların her zaman kendilerini aşmaları gerektiğini anlatır.",
        [
            ("Antik Olimpiyatlar nerede ve kimin onuruna yapılırmış?", ["Olimpiya kentinde, Zeus onuruna", "Atina'da, Atena onuruna", "Roma'da, Jüpiter onuruna", "Sparta'da, Ares onuruna"]),
            ("Kazananlara ne verilirmiş?", ["Zeytin dalından bir taç", "Altın madalya", "Gümüş kupa", "Para ödülü"]),
            ("Antik oyunları kim yasaklamış?", ["İmparator I. Theodosius", "Pierre de Coubertin", "Zeus", "Atina Meclisi"]),
            ("İlk modern oyunlar nerede ve ne zaman yapıldı?", ["1896'da Atina'da", "1900'de Paris'te", "1912'de Stockholm'de", "1924'te Roma'da"]),
            ("Olimpiyat halkaları neyi simgeler?", ["Beş kıtayı", "Beş sporu", "Beş kazananı", "Beş ülkeyi"]),
        ]),
    listening=([
        ("Ali", "Dün akşam açılış töreni nasıldı? Ben izleyememiştim."),
        ("Selin", "Harikaydı! Ben gittiğimde tören başlamıştı bile."),
        ("Ali", "Türk sporcular da yürüdü mü?"),
        ("Selin", "Evet, bayrağı bir güreşçi taşıyormuş."),
        ("Ali", "Keşke ben de görseydim. Madalya umudumuz var mı?"),
        ("Selin", "Antrenörleri çok iddialıydı; şampiyon olacaklarını söylüyordu."),
    ], [
        ("Selin marosimga kelganida nima bo'lgan edi?", ["Marosim allaqachon boshlangan edi", "Hali boshlanmagan edi", "Bekor qilingan edi", "Tugagan edi"]),
        ("Turk bayrog'ini kim ko'tarib yurgan ekan?", ["Bir kurashchi", "Bir suzuvchi", "Bir futbolchi", "Murabbiy"]),
    ]),
    practice=[
        ('c', "\"Uchrashuvga kelganimda o'yin boshlangan edi.\"", ["Maça geldiğimde oyun başlamıştı.", "Maça geldiğimde oyun başlıyor.", "Maça geldiğimde oyun başlayacak.", "Maça geldiğimde oyun başlar."]),
        ('c', "Eshitilgan xabar: \"Ali kasal ekan.\"", ["Ali hastaymış.", "Ali hastadır.", "Ali hastaydı.", "Ali hasta olur."]),
        ('c', "\"U yutayotgan edi\" qaysi?", ["Kazanıyordu.", "Kazanmıştı.", "Kazanacak.", "Kazanırmış."]),
        ('c', "\"Medal\" turkchada:", ["madalya", "kupa", "rekor", "zafer"]),
        ('o', "\"Jamoa birinchi bosqichda saralandi.\" gapini tuzing.", ["Takım", "ilk", "turda", "elendi."]),
        ('o', "\"Murabbiy sportchilarni tabrikladi.\" gapini tuzing.", ["Antrenör", "sporcuları", "tebrik", "etti."]),
    ],
    writing=("Sevgan sportchingiz haqida rivayet shaklidan foydalanib 3 gap yozing.",
             "Bu sporcu çok genç yaşta antrenmana başlamış. İlk yarışmasını kazanmış. Daha sonra dünya rekoru kırmış."),
    speaking=["Oyun başlamıştı.", "Takım şampiyon olmuş.", "Antrenör çok memnundu.", "Yeni bir rekor kırıldı."],
    test=[
        ("Hikâye birleşik zamanı qaysi qo'shimcha bilan yasaladi?", ["-(y)DI (zamon shakliga)", "-sA", "-mAk", "-DIr"]),
        ("\"Gelmişti\" nima degani?", ["kelgan edi", "keladi", "kelmoqchi", "kelsa"]),
        ("\"Hastaymış\" nima degani?", ["kasal ekan", "kasal edi", "kasal bo'ladi", "kasal bo'lsa"]),
        ("Qaysi gap rivayet shaklida?", ["Takım kazanmış.", "Takım kazandı.", "Takım kazanacak.", "Takım kazanır."]),
        ("\"Olimpiyat\" so'zining ma'nosi:", ["olimpiada", "musobaqa", "murabbiy", "kubok"]),
        ("\"Antrenman\" nima?", ["mashg'ulot", "kurash", "g'alaba", "rekord"]),
        ("\"Rekor kırmak\" nima degani?", ["rekord yangilamoq", "rekordni yo'qotmoq", "qoidani buzmoq", "mashq qilmoq"]),
        ("\"Zafer\" so'zining ma'nosi:", ["g'alaba", "mag'lubiyat", "durang", "musobaqa"]),
        ("Olimpiya shiori qanday?", ["Daha hızlı, daha yüksek, daha güçlü", "Barış ve kardeşlik", "Birlikte yarışalım", "Önce sağlık"]),
        ("Zamonaviy olimpiya o'yinlari qayerda boshlangan?", ["Afinada (1896)", "Parijda", "Rimda", "Londonda"]),
    ],
    bank=[
        ("\"Yarışıyordu\" nima degani?", ["musobaqalashayotgan edi", "musobaqalashgan", "musobaqalashadi", "musobaqalashsa"]),
        ("\"Başlayacaktı\" nima degani?", ["boshlanadigan edi", "boshlandi", "boshlayapti", "boshlanmagan"]),
        ("\"Kupa\" so'zining ma'nosi:", ["kubok", "medal", "stadion", "forma"]),
        ("\"Mücadele\" nima?", ["kurash", "dam olish", "bayram", "mashq"]),
        ("\"Elenmek\" nima degani?", ["saralab chiqarilmoq", "yutmoq", "qatnashmoq", "mashq qilmoq"]),
        ("\"Sporcu\" kim?", ["sportchi", "murabbiy", "hakam", "tomoshabin"]),
        ("\"Antrenör\" kim?", ["murabbiy", "sportchi", "hakam", "muxlis"]),
        ("Antik oyunlarda g'oliblarga nima berilgan?", ["zaytun shoxidan toj", "oltin medal", "kumush kubok", "pul"]),
        ("Zamonaviy olimpiyani kim qayta tikladi?", ["Pierre de Coubertin", "Zeus", "I. Theodosius", "Atatürk"]),
        ("Olimpiya halqalari nimani bildiradi?", ["besh qit'a", "besh sport turi", "besh g'olib", "besh davlat"]),
        ("\"Maç başlamıştı bile.\" gapida \"bile\" nima ma'no beradi?", ["allaqachon", "hech qachon", "ehtimol", "faqat"]),
        ("Rivayet shakli qaysi?", ["-mIş / -(I)yormuş", "-DIr", "-sA", "-mAk"]),
    ],
)

B = topic(
    'u1b', "B. Spor Çeşitleri — Sport turlari", 20, 25,
    goals=[
        "Qiyoslash va ustunlik darajasi (daha, en, -DIkçA) tuzilmalarini qo'llash",
        "Sport turlari va jihozlari lug'atini bilish",
        "Sevimli sport turi haqida fikr bildirish",
    ],
    blocks=[
        ("Karşılaştırma: daha, kadar, -(y)lA birlikte",
         "Ikki narsani qiyoslashda \"daha\" va chiqish kelishigi (-DAn) ishlatiladi: Futbol basketboldan daha yaygın. Tenglikda \"kadar\" ishlatiladi: Voleybol futbol kadar popüler. Murakkab qiyoslarda \"-(y)lA birlikte\" (bilan birga) va \"-DIğI kadar\" kabi tuzilmalar keladi: Düşündüğümüzden daha zor bir spor."),
        ("Üstünlük: en, -(y)An en",
         "\"En\" eng yuqori darajani bildiradi: En sevdiğim spor tenis. Sifat-fe'l bilan: Dünyada en çok izlenen spor futbol. \"En az\" kamida, \"en fazla\" ko'pi bilan ma'nosini beradi."),
        ("-DIkçA ... -DIkçA: kuchayib boruvchi nisbat",
         "-DIkçA \"... gan sari\" ma'nosini beradi va ikkinchi qismda \"daha\" bilan birga kelib, o'zaro bog'liq o'sishni ko'rsatadi: Antrenman yaptıkça daha güçleniyorum. Koştukça nefesim düzeliyor. (Yugurgan sari nafasim yaxshilanyapti.)"),
    ],
    facts=[
        "Qiyos: daha + chiqish kelishigi (-DAn); tenglik: kadar.",
        "Ustunlik: en + sifat/ravish; en çok, en az.",
        "-DIkçA = ...gan sari; ko'pincha daha bilan: yaptıkça daha iyi oluyor.",
        "Futbol dunyoda eng ommabop sport turi hisoblanadi.",
    ],
    vocab=[
        ("futbol", "futbol", "Futbol dünyanın en popüler sporudur.", "Futbol dunyoning eng mashhur sporti."),
        ("basketbol", "basketbol", "Basketbol sahasında beş oyuncu bulunur.", "Basketbol maydonida besh o'yinchi bo'ladi."),
        ("voleybol", "voleybol", "Voleybolda file üzerinden top aşırılır.", "Voleybolda to'r ustidan to'p oshiriladi."),
        ("güreş", "kurash", "Güreş Türkler için köklü bir spordur.", "Kurash turklar uchun qadimiy sport turi."),
        ("yüzme", "suzish", "Yüzme bütün vücut için yararlı.", "Suzish butun tana uchun foydali."),
        ("koşu", "yugurish", "Sabah koşusu zinde tutar.", "Ertalabki yugurish tetik saqlaydi."),
        ("jimnastik", "gimnastika", "Jimnastikte denge çok önemlidir.", "Gimnastikada muvozanat juda muhim."),
        ("okçuluk", "kamondan otish", "Okçuluk Türklerin eski sporlarından.", "Kamondan otish turklarning qadimiy sportlaridan."),
        ("ağırlık", "og'irlik, shtanga", "Ağırlık kaldırmada Türkiye başarılı.", "Og'ir atletikada Turkiya muvaffaqiyatli."),
        ("hakem", "hakam", "Hakem düdüğü çaldı.", "Hakam hushtak chaldi."),
        ("saha", "maydon", "Oyuncular sahaya çıktı.", "O'yinchilar maydonga chiqdi."),
        ("taraftar", "muxlis", "Taraftarlar takımı destekledi.", "Muxlislar jamoani qo'llab-quvvatladi."),
    ],
    reading=("Benim şehrim, benim sporum",
        "Trabzon'da büyüdüm ve çocukluğumdan beri futbola tutkuyla bağlıyım. Ancak yüzme, benim için daha eğlenceli; çünkü denize yakın yaşıyoruz. Arkadaşlarım futbolu yüzmeden daha çok sever, ben ise tam tersini düşünürüm.\n\nKoştukça daha dayanıklı olduğumu fark ettim. Bu yüzden her sabah sahil yolunda koşuyorum. En sevdiğim an, sabah güneşinin denizde parlamasıdır. Hafta sonları ise okçuluk kursuna gidiyorum; Türklerin bu sporu binlerce yıldır yaptığını öğrenmek beni çok etkiledi.\n\nSizce hangi spor en faydalıdır? Bence yüzme, bütün kasları çalıştırdığı için en iyisidir. Ama herkesin sevdiği spor farklıdır; önemli olan hareket etmektir.",
        [
            ("Yazar çocukluğundan beri hangi spora bağlı?", ["Futbola", "Yüzmeye", "Okçuluğa", "Güreşe"]),
            ("Yazar neden yüzmeyi daha eğlenceli buluyor?", ["Denize yakın yaşadığı için", "Arkadaşları yüzdüğü için", "Takım sporu olduğu için", "Daha kolay olduğu için"]),
            ("Koştukça yazar ne fark etti?", ["Daha dayanıklı olduğunu", "Daha çok yorulduğunu", "Kilo aldığını", "Hızlandığını"]),
            ("Hafta sonları nereye gidiyor?", ["Okçuluk kursuna", "Futbol maçına", "Yüzme havuzuna", "Dağa"]),
            ("Yazara göre en faydalı spor hangisi?", ["Yüzme", "Futbol", "Okçuluk", "Koşu"]),
        ]),
    listening=([
        ("Emre", "Hafta sonu hangi spor dalıyla ilgileneceksin?"),
        ("Deniz", "Basketbol oynayacağım. Futboldan daha heyecanlı buluyorum."),
        ("Emre", "Ben aksine futbolu basketboldan çok seviyorum."),
        ("Deniz", "Oynadıkça daha iyi oluyorum, sen de dene."),
        ("Emre", "Tamam, ama önce hakemin kurallarını öğreneyim."),
        ("Deniz", "Merak etme, ben anlatırım."),
    ], [
        ("Deniz qaysi sportni yoqtiradi?", ["Basketbolni", "Futbolni", "Suzishni", "Kurashni"]),
        ("Emre nimani o'rganmoqchi?", ["Hakam qoidalarini", "Suzishni", "Yugurishni", "Kamondan otishni"]),
    ]),
    practice=[
        ('c', "\"Futbol basketboldan ommaboproq.\"", ["Futbol basketboldan daha yaygın.", "Futbol basketbol kadar yaygın.", "Futbol basketbolun en yaygın.", "Futbol daha basketbol."]),
        ('c', "\"Yugurgan sari nafasim yaxshilanyapti.\"", ["Koştukça nefesim düzeliyor.", "Koşarsa nefesim düzelir.", "Koşmadan nefesim düzelir.", "Koşunca düzeldi nefes."]),
        ('c', "\"Eng sevimli sport\" turkchada:", ["en sevdiğim spor", "daha sevdiğim spor", "çok sevdiğim sport", "az sevdiğim spor"]),
        ('c', "\"Hakam\" turkchada:", ["hakem", "taraftar", "saha", "kupa"]),
        ('o', "\"Mashq qilgan sari kuchlanaman.\" gapini tuzing.", ["Antrenman", "yaptıkça", "güçleniyorum."]),
        ('o', "\"Voleybol futbol kabi mashhur.\" gapini tuzing.", ["Voleybol", "futbol", "kadar", "popüler."]),
    ],
    writing=("Sevimli sport turingiz haqida va uni nega yoqtirishingiz haqida 3 gap yozing (qiyosdan foydalaning).",
             "En sevdiğim spor yüzmedir. Yüzmeyi koşudan daha rahat buluyorum. Yüzdükçe daha mutlu oluyorum."),
    speaking=["Futbol en popüler spordur.", "Koştukça daha iyi oluyorum.", "Yüzmeyi çok seviyorum.", "Hakem düdüğü çaldı."],
    test=[
        ("\"Daha\" qaysi vazifada keladi?", ["qiyosiy darajada", "ustunlik darajasida", "inkor", "buyruq"]),
        ("\"Futbol voleybol kadar yaygın.\" gapi nima bildiradi?", ["tenglik", "ustunlik", "kamlik", "inkor"]),
        ("-DIkçA qo'shimchasining ma'nosi:", ["...gan sari", "...sa", "...maslik", "...ish uchun"]),
        ("\"Koştukça nefesim düzeliyor.\" ma'nosi:", ["Yugurgan sari nafasim yaxshilanyapti.", "Yugurmasam nafasim yaxshi.", "Yugursam ham yaxshi emas.", "Yugurdim va charchadim."]),
        ("\"En sevdiğim\" nima degani?", ["eng yoqtirganim", "kamroq yoqtirganim", "yoqtirmaganim", "ko'proq yoqtirganim"]),
        ("\"Güreş\" so'zining ma'nosi:", ["kurash", "suzish", "yugurish", "gimnastika"]),
        ("\"Hakem\" kim?", ["hakam", "murabbiy", "muxlis", "o'yinchi"]),
        ("\"Taraftar\" nima?", ["muxlis", "sportchi", "kapitan", "hakam"]),
        ("\"Okçuluk\" nima?", ["kamondan otish", "suzish", "yugurish", "tennis"]),
        ("\"Saha\" so'zining ma'nosi:", ["maydon", "stadion kassasi", "forma", "kubok"]),
    ],
    bank=[
        ("\"Basketbol\" necha kishilik jamoa o'yini (maydonda)?", ["besh kishi", "yetti kishi", "ikki kishi", "o'n bir kishi"]),
        ("\"Yüzme\" nima?", ["suzish", "yugurish", "kurash", "tennis"]),
        ("\"Koşu\" nima?", ["yugurish", "suzish", "sakrash", "otish"]),
        ("\"Ağırlık kaldırma\" nima?", ["og'ir atletika", "kamondan otish", "suzish", "gimnastika"]),
        ("\"Daha güçlü\" nima degani?", ["kuchliroq", "eng kuchli", "kuchsiz", "kuchli emas"]),
        ("\"Kadar\" nimani bildiradi?", ["tenglik", "ustunlik", "inkor", "maqsad"]),
        ("\"En az\" nima degani?", ["kamida", "eng ko'p", "ko'pi bilan emas", "ham"]),
        ("Qaysi gap qiyos?", ["Yüzme koşudan daha eğlenceli.", "Yüzme eğlenceli.", "Yüzmeyi seviyorum.", "Yüzmek için gidiyorum."]),
        ("\"Antrenman yaptıkça\" nima?", ["mashq qilgan sari", "mashq qilsa", "mashq qilmasdan", "mashq qilib"]),
        ("\"Jimnastik\" nima?", ["gimnastika", "yugurish", "kurash", "suzish"]),
        ("\"Hakem düdüğü çaldı.\" ma'nosi:", ["Hakam hushtak chaldi.", "Hakam ketdi.", "Hakam yutdi.", "Hakam yiqildi."]),
        ("\"Sahaya çıkmak\" nima?", ["maydonga chiqmoq", "uyga qaytmoq", "dam olmoq", "mashq qilmoq"]),
    ],
)

C = topic(
    'u1c', "C. Sağlıklı Yaşam İçin Spor — Sog'lom hayot uchun sport", 26, 34,
    goals=[
        "Gereklilik va maslahat shakllarini (-mAlI, -sA iyi olur, lazım) qo'llash",
        "Sog'liq va ovqatlanish lug'atini bilish",
        "Sog'lom turmush tarzi haqida maslahat berish",
    ],
    blocks=[
        ("Gereklilik: -mAlI, -mAk gerekir, lazım",
         "Majburiyat va zaruriyat -mAlI bilan ifodalanadi: Her gün yürümelisin. (Har kuni yurishing kerak.) Inkor shakli -mAmAlI: Fazla yağlı yememelisin. Qo'shimcha usullar: -mAsI gerekir, -mAk lazım: Düzenli spor yapman gerekir. Uyumak lazım."),
        ("Öneri ve tavsiye: -sA iyi olur, -sAnA, -AyIm mI?",
         "Yumshoq maslahat \"-sA iyi olur\" bilan beriladi: Biraz dinlensen iyi olur. -(y)sAnA \"shunday qilsang-chi\" ma'nosida taklif beradi: Havuza gitsene. Taklif: Beraber yürüyelim mi? Birinchi shaxs savol: Sana yardım edeyim mi?"),
        ("Şart ve tavsiye birlikte: -DIğIndA, -mAdIkçA",
         "-mAdIkçA \"... maguncha, ... masa\" ma'nosini beradi: Düzenli uyumadıkça sağlıklı olamazsın. -DIğIndA payt bildiradi: Yorulduğunda dinlen."),
    ],
    facts=[
        "-mAlI = kerak/majbur; inkor -mAmAlI = bo'lmaydi.",
        "-sA iyi olur = yumshoq maslahat; -sAnA = taklif.",
        "-mAdIkçA = ...maguncha; shartli to'siq.",
        "Dunyo sog'liqni saqlash tashkiloti kattalarga haftada kamida 150 daqiqa harakatni tavsiya qiladi.",
    ],
    vocab=[
        ("sağlıklı", "sog'lom", "Sağlıklı beslenmek çok önemlidir.", "Sog'lom ovqatlanish juda muhim."),
        ("zinde", "tetik, baquvvat", "Spor beni zinde tutuyor.", "Sport meni tetik saqlaydi."),
        ("düzenli", "muntazam", "Düzenli spor yapmalısın.", "Muntazam sport qilishing kerak."),
        ("beslenme", "ovqatlanish", "Dengeli beslenme sağlığın temelidir.", "Muvozanatli ovqatlanish sog'liq asosi."),
        ("vitamin", "vitamin", "Meyvede çok vitamin var.", "Mevada vitamin ko'p."),
        ("kas", "mushak", "Yüzme kasları güçlendirir.", "Suzish mushaklarni mustahkamlaydi."),
        ("kalp", "yurak", "Yürüyüş kalbi korur.", "Piyoda yurish yurakni asraydi."),
        ("yorgunluk", "charchoq", "Yorgunluğu atmak için dinlen.", "Charchoqni yozish uchun dam ol."),
        ("uyku", "uyqu", "Yeterli uyku şarttır.", "Yetarli uyqu shart."),
        ("sakat", "jarohatlangan", "Oyuncu sakat kaldı.", "O'yinchi jarohatlanib qoldi."),
        ("kilo", "vazn", "Kilo vermek için çok yürüyor.", "Vazn tashlash uchun ko'p yuradi."),
        ("doktor", "shifokor", "Doktora danışmadan diyet yapma.", "Shifokor bilan maslahatlashmay parhez qilma."),
    ],
    reading=("Spor yap, zinde kal",
        "Doktorlar yetişkinlerin haftada en az yüz elli dakika hareket etmesi gerektiğini söylüyor. Bu süre, günde yirmi dakikalık bir yürüyüşle bile tamamlanabilir. Düzenli spor yapmayan insanların kalp hastalıklarına yakalanma riski daha yüksektir.\n\nUzmanlar şu önerilerde bulunuyor: Önce hedefini belirle; kendine uygun bir spor seç; yavaş başla ve zamanla artır. Aşırı yorulduğunda dinlenmelisin, çünkü fazla zorlamak sakatlığa yol açabilir. Yeterli su içmek ve dengeli beslenmek de en az spor kadar önemlidir.\n\nUyku da sağlığın bir parçasıdır. Yeterince uyumadıkça kaslar toparlanamaz. Bu nedenle spor yapan biri gece yedi sekiz saat uyumalıdır.",
        [
            ("Doktorlara göre yetişkinler haftada en az ne kadar hareket etmeli?", ["150 dakika", "30 dakika", "300 dakika", "60 dakika"]),
            ("Düzenli spor yapmayanlarda hangi risk yüksek?", ["Kalp hastalığı riski", "Soğuk algınlığı", "Göz hastalığı", "Diş sorunu"]),
            ("Fazla zorlamak neye yol açabilir?", ["Sakatlığa", "Kilo vermeye", "Daha çok uykuya", "Daha iyi beslenmeye"]),
            ("Metne göre kaslar neden toparlanamaz?", ["Yeterince uyumadıkça", "Su içmedikçe", "Koşmadıkça", "Yemek yemedikçe"]),
            ("Spor yapan biri gece kaç saat uyumalı?", ["Yedi sekiz saat", "Üç dört saat", "On saat", "Beş saat"]),
        ]),
    listening=([
        ("Doktor", "Kilo vermek istiyorsun ama düzenli hareket etmiyorsun."),
        ("Hasta", "Evet, zamanım olmuyor."),
        ("Doktor", "Her gün yarım saat yürüsen iyi olur."),
        ("Hasta", "Peki beslenme konusunda ne yapmalıyım?"),
        ("Doktor", "Fazla tatlı yememelisin ve bol su içmelisin."),
        ("Hasta", "Peki, yarın başlayacağım."),
    ], [
        ("Shifokor nima maslahat berdi?", ["Har kuni yarim soat yurishni", "Dori ichishni", "Uxlamaslikni", "Ko'p ovqat yeyishni"]),
        ("Bemor nimadan qochishi kerak?", ["Ko'p shirinlikdan", "Suvdan", "Yurishdan", "Sabzavotdan"]),
    ]),
    practice=[
        ('c', "\"Har kuni yurishing kerak.\"", ["Her gün yürümelisin.", "Her gün yürürsün.", "Her gün yürüdün.", "Her gün yürüyecek."]),
        ('c', "\"Biroz dam olsang yaxshi bo'ladi.\"", ["Biraz dinlensen iyi olur.", "Biraz dinlendin iyi.", "Biraz dinlenmek iyi değil.", "Biraz dinlenmiş iyi."]),
        ('c', "\"Uxlamaguncha mushaklar tiklanmaydi.\"", ["Uyumadıkça kaslar toparlanamaz.", "Uyudukça kaslar toparlanır.", "Uyumak kaslar için.", "Uyuyunca toparlanmaz."]),
        ('c', "\"Yurak\" turkchada:", ["kalp", "kas", "uyku", "kilo"]),
        ('o', "\"Muntazam sport qilishing kerak.\" gapini tuzing.", ["Düzenli", "spor", "yapmalısın."]),
        ('o', "\"Fazla yog'li yemasliging kerak.\" gapini tuzing.", ["Fazla", "yağlı", "yememelisin."]),
    ],
    writing=("Do'stingizga sog'lom turmush bo'yicha 3 ta maslahat yozing (-mAlI va -sA iyi olur).",
             "Her gün yürümelisin. Daha az tatlı yesen iyi olur. Gece erken uyumalısın."),
    speaking=["Düzenli spor yapmalısın.", "Biraz dinlensen iyi olur.", "Bol su içmelisin.", "Yeterince uyumadıkça zinde olamazsın."],
    test=[
        ("-mAlI qo'shimchasi nimani bildiradi?", ["zaruriyat, majburiyat", "o'tgan zamon", "shart", "ravishdosh"]),
        ("\"Yememelisin\" nima degani?", ["yemasliging kerak", "yeyishing kerak", "yeding", "yeysan"]),
        ("\"Dinlensen iyi olur.\" nima?", ["Dam olsang yaxshi bo'ladi.", "Dam olding.", "Dam olma.", "Dam olmoqda."]),
        ("-mAdIkçA nima degani?", ["...maguncha, ...masa", "...gan sari", "...ganda", "...ish uchun"]),
        ("\"Zinde\" so'zining ma'nosi:", ["tetik, baquvvat", "charchagan", "kasal", "uyqusiz"]),
        ("\"Beslenme\" nima?", ["ovqatlanish", "uyqu", "mashq", "dam olish"]),
        ("\"Sakat\" so'zining ma'nosi:", ["jarohatlangan", "sog'lom", "kuchli", "charchagan"]),
        ("\"Kalp\" so'zining ma'nosi:", ["yurak", "mushak", "o'pka", "miya"]),
        ("\"Kilo vermek\" nima?", ["vazn tashlamoq", "vazn olmoq", "ovqat yemoq", "yugurmoq"]),
        ("Kattalar haftada kamida qancha harakat qilishi kerak?", ["150 daqiqa", "15 daqiqa", "1500 daqiqa", "50 daqiqa"]),
    ],
    bank=[
        ("\"Düzenli\" nima degani?", ["muntazam", "tasodifiy", "kamdan-kam", "kechqurun"]),
        ("\"Yorgunluk\" nima?", ["charchoq", "uyqu", "mushak", "ovqat"]),
        ("\"Uyku\" nima?", ["uyqu", "charchoq", "kasallik", "mashq"]),
        ("\"Doktora danışmak\" nima?", ["shifokor bilan maslahatlashmoq", "dori ichmoq", "ovqat yemoq", "yugurmoq"]),
        ("\"Gitsene\" nima ma'no beradi?", ["taklif (bor-chi)", "buyruq emas", "inkor", "o'tgan zamon"]),
        ("\"Yürüyelim mi?\" nima?", ["Yuraylikmi?", "Yurdikmi?", "Yurmaymizmi?", "Yurganmiz?"]),
        ("Qaysi gap maslahat?", ["Daha çok su içsen iyi olur.", "Su içti.", "Su içiyor.", "Su içmişti."]),
        ("\"Fazla zorlamak\" nima?", ["ortiqcha zo'rlamoq", "dam olmoq", "yengil mashq", "yig'moq"]),
        ("\"Vitamin\" qaysi mahsulotda ko'p?", ["mevada", "yog'da", "shakarda", "tuzda"]),
        ("\"Kas\" nima?", ["mushak", "suyak", "yurak", "teri"]),
        ("\"Dengeli beslenme\" nima?", ["muvozanatli ovqatlanish", "ko'p ovqat", "kam ovqat", "yog'li ovqat"]),
        ("\"Dinlenmek\" nima?", ["dam olmoq", "yugurmoq", "ishlamoq", "o'qimoq"]),
    ],
)

TOPICS = [A, B, C]
