# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u2a', "A. Dünden Bugüne — Kechadan bugungacha", 36, 42,
    goals=[
        "Sifat-fe'l -DIk/-(y)An va -DIğI zaman, -DIkçA tuzilmalarini qo'llash",
        "O'tmish va hozirni qiyoslovchi ifodalarni (eskiden, artık, hâlâ) ishlatish",
        "Texnologiya va kundalik hayot o'zgarishi haqida matn tuzish",
    ],
    blocks=[
        ("Eskiden / artık / hâlâ: o'tmish va hozir",
         "Eskiden (ilgari) odatni, artık (endi) o'zgarishni, hâlâ (hamon) davomiylikni bildiradi: Eskiden mektup yazardık; artık mesaj atıyoruz. Hâlâ postaneye gidenler var. \"-Ir oldu / -mAz oldu\" tuzilmasi odatiy o'tgan zamonni ko'rsatadi: Eskiden insanlar akşamları sohbet ederdi."),
        ("-DIğI zaman / -DIğI gibi / -DIğI için",
         "-DIğI + payt/ko'makchi tuzilmalari bog'lovchi vazifasida: Çocuk olduğum zaman köyde yaşıyorduk. Gördüğüm gibi anlattım (ko'rganimcha aytdim). Zaman değiştiği için alışkanlıklar da değişti."),
        ("-DIkçA: takrorlanuvchi ish",
         "-DIkçA ham \"...gan sari\" ham \"har safar\" ma'nosida keladi: Teknoloji geliştikçe hayat kolaylaştı. Ne zaman şehre gitsem eski dostlarımı ararım: Gittikçe (borgan sari) ... ."),
    ],
    facts=[
        "Eskiden = ilgari; artık = endi; hâlâ = hamon.",
        "-DIğI zaman = ...gan paytda; -DIğI için = ...gani uchun.",
        "-DIkçA: ...gan sari / har safar.",
        "Telegraf va telefondan keyin internet muloqot usullarini tubdan o'zgartirdi.",
    ],
    vocab=[
        ("eskiden", "ilgari", "Eskiden köylerde elektrik yoktu.", "Ilgari qishloqlarda elektr yo'q edi."),
        ("artık", "endi", "Artık herkes cep telefonu kullanıyor.", "Endi hamma mobil telefondan foydalanadi."),
        ("hâlâ", "hamon", "Hâlâ eski radyomu dinliyorum.", "Hamon eski radiomni tinglayapman."),
        ("gelişmek", "rivojlanmoq", "Teknoloji hızla gelişti.", "Texnologiya tez rivojlandi."),
        ("değişmek", "o'zgarmoq", "Zamanla birçok şey değişti.", "Vaqt o'tishi bilan ko'p narsa o'zgardi."),
        ("alışkanlık", "odat", "Eski alışkanlıkları bırakmak zordur.", "Eski odatlarni tashlash qiyin."),
        ("gelenek", "an'ana", "Bayram gelenekleri unutulmuyor.", "Bayram an'analari unutilmayapti."),
        ("icat", "ixtiro", "Matbaa büyük bir icattı.", "Bosmaxona buyuk ixtiro edi."),
        ("iletişim", "aloqa", "İletişim araçları çoğaldı.", "Aloqa vositalari ko'paydi."),
        ("dönem", "davr", "O dönemde herkes mektup yazardı.", "O davrda hamma xat yozardi."),
        ("kuşak", "avlod", "Yeni kuşak teknolojiyle büyüyor.", "Yangi avlod texnologiya bilan o'smoqda."),
        ("geçmiş", "o'tmish", "Geçmişi bilmeyen geleceği kuramaz.", "O'tmishni bilmagan kelajak qura olmaydi."),
    ],
    reading=("Mektuptan mesaja",
        "Büyükannem gençliğinde mektup yazarmış. Bir mektubun karşı şehre ulaşması günler sürermiş. Eskiden insanlar postacıyı sabırsızlıkla beklerdi; zarfı açarken kalpleri çarparmış. Artık aynı haberi saniyeler içinde alabiliyoruz.\n\nTeknoloji geliştikçe iletişim kolaylaştı ama bazı şeyler de kayboldu. Eskiden aile üyeleri akşam yemeğinde uzun uzun konuşurdu; şimdi birçoğumuzun gözü telefonda. Yine de büyükannem hâlâ el yazısıyla mektup yazıyor ve bunun bir mesajdan daha samimi olduğunu söylüyor.\n\nBence geçmişin değerli yönlerini koruyarak yeniliklerden yararlanmak gerekir.",
        [
            ("Büyükanne gençliğinde ne yazarmış?", ["Mektup", "Roman", "Günlük", "Şiir"]),
            ("Mektubun ulaşması eskiden ne kadar sürerdi?", ["Günler", "Saniyeler", "Aylar", "Saatler"]),
            ("Metne göre teknoloji geliştikçe ne oldu?", ["İletişim kolaylaştı ama bazı şeyler kayboldu", "İletişim zorlaştı", "Hiçbir şey değişmedi", "Mektuplar çoğaldı"]),
            ("Büyükanne hâlâ ne yapıyor?", ["El yazısıyla mektup yazıyor", "Mesaj atıyor", "E-posta gönderiyor", "Telefon ediyor"]),
            ("Yazarın görüşü nedir?", ["Geçmişin değerlerini koruyup yeniliklerden yararlanmalı", "Teknoloji bırakılmalı", "Mektup yasaklanmalı", "Eski her şey kötü"]),
        ]),
    listening=([
        ("Baba", "Biz çocukken televizyon yoktu; akşamları radyo dinlerdik."),
        ("Kız", "Gerçekten mi? Peki sıkılmaz mıydınız?"),
        ("Baba", "Hayır, birbirimize hikâye anlatırdık."),
        ("Kız", "Artık herkes kendi telefonuyla ilgileniyor."),
        ("Baba", "Haklısın. Teknoloji geliştikçe sohbet azaldı."),
        ("Kız", "Bu akşam telefonları bırakıp biz de hikâye anlatalım."),
    ], [
        ("Ota bolaligida kechqurunlari nima tinglagan?", ["Radio", "Televizor", "Musiqa", "Kitob"]),
        ("Qiz nimani taklif qildi?", ["Telefonlarni qo'yib hikoya aytishni", "Televizor ko'rishni", "Ko'chaga chiqishni", "Uxlashni"]),
    ]),
    practice=[
        ('c', "\"Ilgari xat yozardik.\"", ["Eskiden mektup yazardık.", "Artık mektup yazıyoruz.", "Hâlâ mektup yazdık.", "Yarın mektup yazarız."]),
        ('c', "\"Endi hamma telefondan foydalanadi.\"", ["Artık herkes telefon kullanıyor.", "Eskiden herkes telefon kullanırdı.", "Hâlâ herkes kullanacak.", "Hiç kimse kullanmıyor."]),
        ('c', "\"Texnologiya rivojlangan sari hayot yengillashdi.\"", ["Teknoloji geliştikçe hayat kolaylaştı.", "Teknoloji gelişirse hayat zor.", "Teknoloji geliştiği yok.", "Teknoloji gelişince kolaylaştır."]),
        ('c', "\"Ixtiro\" turkchada:", ["icat", "dönem", "kuşak", "gelenek"]),
        ('o', "\"Hamon eski radiomni tinglayman.\" gapini tuzing.", ["Hâlâ", "eski", "radyomu", "dinliyorum."]),
        ('o', "\"Vaqt o'zgargani uchun odatlar ham o'zgardi.\" gapini tuzing.", ["Zaman", "değiştiği", "için", "alışkanlıklar", "da", "değişti."]),
    ],
    writing=("Ota-onangiz yoshligi va bugungi hayot o'rtasidagi 3 ta farqni yozing (eskiden, artık).",
             "Eskiden insanlar mektup yazardı. Artık mesaj atıyor. Hâlâ bazıları el yazısını seviyor."),
    speaking=["Eskiden mektup yazardık.", "Artık herkes telefon kullanıyor.", "Teknoloji geliştikçe hayat kolaylaşıyor.", "Hâlâ eski radyomu dinliyorum."],
    test=[
        ("\"Eskiden\" so'zining ma'nosi:", ["ilgari", "endi", "hamon", "kelajakda"]),
        ("\"Artık\" so'zining ma'nosi:", ["endi", "ilgari", "hech qachon", "balki"]),
        ("\"Hâlâ\" so'zining ma'nosi:", ["hamon", "endi", "ilgari", "darhol"]),
        ("-DIkçA qo'shimchasining ma'nosi:", ["...gan sari / har safar", "...gach", "...maguncha", "...ish uchun"]),
        ("\"Gördüğüm gibi\" nima degani?", ["ko'rganimdek", "ko'rmaganimdek", "ko'raman", "ko'rsam"]),
        ("\"İletişim\" so'zining ma'nosi:", ["aloqa", "ixtiro", "avlod", "odat"]),
        ("\"Kuşak\" nima?", ["avlod", "davr", "an'ana", "ixtiro"]),
        ("\"Gelenek\" so'zining ma'nosi:", ["an'ana", "odat", "ixtiro", "davr"]),
        ("\"Alışkanlık\" so'zining ma'nosi:", ["odat", "an'ana", "avlod", "tajriba"]),
        ("\"Teknoloji geliştikçe\" nima?", ["texnologiya rivojlangan sari", "texnologiya rivojlansa", "texnologiya rivojlanmasa", "texnologiya rivojlanish uchun"]),
    ],
    bank=[
        ("\"Dönem\" nima?", ["davr", "avlod", "ixtiro", "xat"]),
        ("\"Geçmiş\" nima?", ["o'tmish", "kelajak", "hozir", "ertaga"]),
        ("\"Değişmek\" nima degani?", ["o'zgarmoq", "saqlamoq", "yo'qolmoq", "boshlamoq"]),
        ("\"Gelişmek\" nima degani?", ["rivojlanmoq", "orqaga ketmoq", "to'xtamoq", "yo'qolmoq"]),
        ("\"İcat\" nima?", ["ixtiro", "an'ana", "davr", "xat"]),
        ("\"Zaman değiştiği için\" nima?", ["vaqt o'zgargani uchun", "vaqt o'zgarsa", "vaqt o'zgarmaguncha", "vaqt o'zgarganda"]),
        ("\"Çocuk olduğum zaman\" nima?", ["bola bo'lganimda", "bola bo'lsam", "bola bo'laman", "bola bo'lmasam"]),
        ("Qaysi gap odatiy o'tgan zamonni bildiradi?", ["Eskiden mektup yazardık.", "Mektup yazdık.", "Mektup yazıyoruz.", "Mektup yazacağız."]),
        ("\"Postacı\" kim?", ["pochtachi", "xattot", "muallif", "yozuvchi"]),
        ("\"Sabırsızlıkla beklemek\" nima?", ["sabrsizlik bilan kutmoq", "xotirjam kutmoq", "kutmaslik", "qochmoq"]),
        ("\"Samimi\" nima?", ["samimiy", "rasmiy", "sovuq", "uzoq"]),
        ("\"Yeni kuşak\" nima?", ["yangi avlod", "eski davr", "yangi uy", "yangi xat"]),
    ],
)

B = topic(
    'u2b', "B. Neredeyim? — Men qayerdaman?", 43, 48,
    goals=[
        "Yo'nalish va joylashuv ifodalarini (karşısında, yanında, -DIğI yer) qo'llash",
        "Shahar va yo'l tariflash lug'atini bilish",
        "Manzil so'rash va yo'l ko'rsatish suhbatini yuritish",
    ],
    blocks=[
        ("Konum ilgeçleri: karşısında, arkasında, çaprazında",
         "Joylashuvni bildirishda ism + egalik + joy kelishigi ishlatiladi: Okulun karşısında bir kütüphane var. Bankanın yanındaki sokaktan sağa dön. \"Çaprazında\" (diagonal bo'yicha), \"köşesinde\" (burchakda), \"ilerisinde\" (oldinda)."),
        ("Yön tarifi: -(y)ArAk, -(y)Ip, -ınca",
         "Yo'l tarifida ravishdoshlar ketma-ketlikni beradi: Düz giderek ikinci sokaktan sola dönün. Köprüyü geçip hastaneyi göreceksiniz. Işıklara gelince sağa dönün."),
        ("Sıfat-fiil bilan yer tarifi: -DIğI yer, -(y)An",
         "Joyni sifat-fe'l bilan tariflash: Benim yaşadığım mahalle sessizdir. Müzeyi gösteren tabela. Geçtiğimiz sokak. Bu tuzilma aniq joyni aytishga yordam beradi: Çiçekçinin bulunduğu köşe."),
    ],
    facts=[
        "karşısında = qarshisida; çaprazında = diagonalida; köşesinde = burchagida.",
        "Yo'l tarifi: düz git, sağa/sola dön, ... geçince.",
        "-DIğI yer, -(y)An yer — joyni sifat-fe'l bilan tarif.",
        "Turkiyada manzil odatda mahalle - cadde - sokak - kapı numarası ketma-ketligida yoziladi.",
    ],
    vocab=[
        ("cadde", "katta ko'cha", "Bu cadde şehrin ana yoludur.", "Bu katta ko'cha shaharning asosiy yo'li."),
        ("sokak", "ko'cha", "Evimiz sakin bir sokakta.", "Uyimiz tinch ko'chada."),
        ("kavşak", "chorraha", "Kavşakta sağa dönün.", "Chorrahada o'ngga buring."),
        ("köprü", "ko'prik", "Köprüden sonra sola dönün.", "Ko'prikdan keyin chapga buring."),
        ("meydan", "maydon", "Meydanda büyük bir heykel var.", "Maydonda katta haykal bor."),
        ("tabela", "yo'l belgisi, lavha", "Tabelayı okuyunca yolu buldum.", "Lavhani o'qib yo'lni topdim."),
        ("harita", "xarita", "Haritaya bakarak ilerledik.", "Xaritaga qarab oldinga yurdik."),
        ("durak", "bekat", "Durak okulun hemen önünde.", "Bekat maktab oldidagina."),
        ("yaya", "piyoda", "Yayalar kaldırımı kullanmalı.", "Piyodalar yo'lakdan foydalanishi kerak."),
        ("kaldırım", "yo'lak, trotuar", "Kaldırımda yürüyelim.", "Yo'lakda yuraylik."),
        ("adres", "manzil", "Adresi telefonuma kaydettim.", "Manzilni telefonimga saqladim."),
        ("yön", "yo'nalish", "Hangi yöne gitmeliyiz?", "Qaysi yo'nalishga borishimiz kerak?"),
    ],
    reading=("Kaybolmak güzeldir",
        "İstanbul'a ilk kez gelen Selim, otelinden çıkıp eski şehri gezmeye karar verdi. Elinde harita vardı ama sokaklar dar ve karışıktı. Bir kavşakta durup yönünü bulmaya çalıştı. Karşısında küçük bir çay ocağı gördü ve yardım istedi.\n\nÇaycı gülümseyerek tarif etti: \"Düz giderek ikinci sokaktan sola dönün. Köprüyü geçince sağınızda büyük bir meydan göreceksiniz. Aradığınız müze meydanın çaprazında.\"\n\nSelim teşekkür edip yola çıktı. Yolda tabelaları okuyarak ilerledi. Müzeye vardığında hem aradığını bulmuştu hem de yolda gördüğü güzel sokaklar için mutluydu.",
        [
            ("Selim neye karar verdi?", ["Eski şehri gezmeye", "Otele dönmeye", "Alışveriş yapmaya", "Müzeyi kapatmaya"]),
            ("Selim kimden yardım istedi?", ["Bir çaycıdan", "Polisten", "Otelci'den", "Taksiciden"]),
            ("Köprüyü geçince nerede ne göreceksin?", ["Sağda büyük bir meydan", "Solda müze", "Karşıda otel", "Arkada çay ocağı"]),
            ("Müze nerede?", ["Meydanın çaprazında", "Köprünün altında", "Otelin yanında", "Çay ocağının arkasında"]),
            ("Selim yolda ne yaptı?", ["Tabelaları okuyarak ilerledi", "Taksiye bindi", "Haritayı attı", "Geri döndü"]),
        ]),
    listening=([
        ("Turist", "Affedersiniz, hastane nerede acaba?"),
        ("Yerli", "Şu kavşaktan sağa dönün, bankanın yanındaki sokaktan düz gidin."),
        ("Turist", "Uzak mı?"),
        ("Yerli", "Hayır, yürüyerek on dakika. Okulun karşısında."),
        ("Turist", "Teşekkür ederim."),
        ("Yerli", "Rica ederim, iyi yolculuklar."),
    ], [
        ("Turist nimani so'radi?", ["Kasalxona qayerda", "Maktab qayerda", "Bank qayerda", "Bekat qayerda"]),
        ("Kasalxona qayerda?", ["Maktab qarshisida", "Bank yonida", "Ko'prik ostida", "Maydon orqasida"]),
    ]),
    practice=[
        ('c', "\"Maktab qarshisida kutubxona bor.\"", ["Okulun karşısında bir kütüphane var.", "Okulun yanında kütüphane yok.", "Okul kütüphanenin karşısı.", "Kütüphane okul gidiyor."]),
        ('c', "\"To'g'ri borib ikkinchi ko'chadan chapga buring.\"", ["Düz giderek ikinci sokaktan sola dönün.", "Düz gitmeden sağa dönün.", "Sola gidip düz dönün.", "İkinci sokak düzdür."]),
        ('c', "\"Chorraha\" turkchada:", ["kavşak", "meydan", "köprü", "tabela"]),
        ('c', "\"Burchakda\" turkchada:", ["köşesinde", "karşısında", "arkasında", "yanında"]),
        ('o', "\"Ko'prikdan o'tgach o'ngda maydonni ko'rasiz.\" gapini tuzing.", ["Köprüyü", "geçince", "sağınızda", "meydanı", "göreceksiniz."]),
        ('o', "\"Bekat maktab oldida.\" gapini tuzing.", ["Durak", "okulun", "hemen", "önünde."]),
    ],
    writing=("Maktabingizdan eng yaqin do'konga yo'lni 3 gapda tariflang.",
             "Okuldan çıkınca sağa dönün. Düz giderek ikinci sokaktan geçin. Market bankanın karşısında."),
    speaking=["Düz giderek sola dönün.", "Köprüyü geçince sağda.", "Durak okulun önünde.", "Haritaya bakarak ilerledik."],
    test=[
        ("\"Karşısında\" nima degani?", ["qarshisida", "orqasida", "yonida", "ichida"]),
        ("\"Çaprazında\" nima degani?", ["diagonalida", "oldida", "ustida", "ostida"]),
        ("\"Sola dönmek\" nima?", ["chapga burilmoq", "o'ngga burilmoq", "to'g'ri bormoq", "qaytmoq"]),
        ("\"Kavşak\" nima?", ["chorraha", "maydon", "bekat", "ko'prik"]),
        ("\"Köprü\" nima?", ["ko'prik", "yo'lak", "bekat", "tabela"]),
        ("\"Kaldırım\" nima?", ["yo'lak", "ko'cha", "maydon", "bekat"]),
        ("\"Adres\" nima?", ["manzil", "xarita", "bekat", "yo'l"]),
        ("\"Yaya\" kim?", ["piyoda", "haydovchi", "yo'lovchi", "turist"]),
        ("\"Düz gitmek\" nima?", ["to'g'ri bormoq", "qaytmoq", "burilmoq", "to'xtamoq"]),
        ("\"Geçince\" nima degani?", ["o'tgach", "o'tmasdan", "o'tish uchun", "o'tsa"]),
    ],
    bank=[
        ("\"Sokak\" nima?", ["ko'cha", "katta ko'cha", "maydon", "ko'prik"]),
        ("\"Cadde\" nima?", ["katta ko'cha", "ko'cha", "yo'lak", "bekat"]),
        ("\"Meydan\" nima?", ["maydon", "ko'prik", "ko'cha", "yo'l"]),
        ("\"Tabela\" nima?", ["yo'l belgisi, lavha", "xarita", "bekat", "ko'cha"]),
        ("\"Durak\" nima?", ["bekat", "maydon", "yo'lak", "ko'prik"]),
        ("\"Harita\" nima?", ["xarita", "manzil", "bekat", "kitob"]),
        ("\"Yön\" nima?", ["yo'nalish", "manzil", "ko'cha", "bekat"]),
        ("\"Arkasında\" nima?", ["orqasida", "oldida", "yonida", "ostida"]),
        ("\"Yanında\" nima?", ["yonida", "qarshisida", "ustida", "ichida"]),
        ("\"Köşesinde\" nima?", ["burchagida", "oldida", "ostida", "ichida"]),
        ("\"Ilerisinde\" nima?", ["oldinda, narigi tomonida", "orqasida", "chap tomonida", "ichida"]),
        ("\"Yürüyerek\" nima?", ["piyoda yurib", "mashinada", "yugurib", "uchib"]),
    ],
)

C = topic(
    'u2c', "C. Yakın Gelecek — Yaqin kelajak", 49, 54,
    goals=[
        "Kelasi zamon va ehtimol shakllarini (-(y)AcAk, -(y)Ir, -(y)AbIlIr, -mIş olacak) qo'llash",
        "Taxmin ifodalari (herhalde, muhtemelen, belki) ni ishlatish",
        "Kelajak texnologiyalari haqida suhbat qurish",
    ],
    blocks=[
        ("Gelecek zaman ve plan: -(y)AcAk, -mAk üzere",
         "Rejalashtirilgan kelajakni -(y)AcAk bilan beramiz: Gelecek yıl şehir dışına taşınacağız. Qat'iy niyatni \"-mAk üzere\" bilan ham aytish mumkin: Toplantı yapmak üzereyiz (yig'ilish o'tkazish arafasidamiz)."),
        ("Olasılık: -(y)AbIlIr, -(y)AbIlmek, belki, muhtemelen",
         "Ehtimol -(y)AbIl- bilan beriladi: Yarın yağmur yağabilir. Taxmin so'zlari: herhalde (ehtimol), muhtemelen (ehtimol bilan), belki (balki). Kuchli ishonch: Mutlaka başaracaksın. Zaif: Belki gelmez."),
        ("Bitmiş gelecek: -mIş olacak, -DIğI zaman",
         "Kelajakda tugallangan ish: Akşama kadar işimi bitirmiş olacağım. Saat ona kadar uyanmış olursun. Bu tuzilma ma'lum nuqtagacha ishning tugagan bo'lishini ko'rsatadi."),
    ],
    facts=[
        "-(y)AcAk = kelasi zamon; -mAk üzere = ...moq arafasida.",
        "-(y)AbIlIr = ehtimol (…ishi mumkin).",
        "Taxmin: herhalde, muhtemelen, belki.",
        "Bitmiş gelecek: -mIş olacak — ma'lum vaqtgacha tugagan ish.",
    ],
    vocab=[
        ("gelecek", "kelajak", "Gelecek nasıl olacak?", "Kelajak qanday bo'ladi?"),
        ("yapay zekâ", "sun'iy intellekt", "Yapay zekâ hayatımızı değiştirecek.", "Sun'iy intellekt hayotimizni o'zgartiradi."),
        ("robot", "robot", "Robotlar fabrikalarda çalışacak.", "Robotlar zavodlarda ishlaydi."),
        ("uzay", "kosmos", "İnsanlar uzayda yaşayabilir.", "Odamlar kosmosda yashashi mumkin."),
        ("enerji", "energiya", "Güneş enerjisi yaygınlaşacak.", "Quyosh energiyasi keng tarqaladi."),
        ("yenilenebilir", "qayta tiklanadigan", "Yenilenebilir enerji önemli.", "Qayta tiklanadigan energiya muhim."),
        ("teknoloji", "texnologiya", "Teknoloji çok hızlı ilerliyor.", "Texnologiya juda tez ilerilamoqda."),
        ("tahmin", "taxmin", "Uzmanlar bir tahmin yaptı.", "Mutaxassislar taxmin qildi."),
        ("ihtimal", "ehtimol", "Yağmur ihtimali yüksek.", "Yomg'ir ehtimoli yuqori."),
        ("muhtemelen", "ehtimol bilan", "Muhtemelen toplantı ertelenecek.", "Ehtimol, yig'ilish keyinga suriladi."),
        ("belki", "balki", "Belki seni arayabilirim.", "Balki senga qo'ng'iroq qilarman."),
        ("hedef", "maqsad", "Hedefim yeni bir dil öğrenmek.", "Maqsadim yangi til o'rganish."),
    ],
    reading=("Yirmi yıl sonra",
        "Uzmanlara göre yirmi yıl sonra hayatımız bugünkünden çok farklı olacak. Yapay zekâ birçok işi insanlar yerine yapabilecek; ancak yine de yaratıcı mesleklere ihtiyaç duyulacak. Arabalar muhtemelen sürücüsüz olacak ve şehirlerde trafik çok azalabilir.\n\nEnerji alanında yenilenebilir kaynaklar yaygınlaşacak. Güneş ve rüzgâr enerjisi evlerimizi ısıtacak. Belki bazı insanlar uzayda kısa tatiller bile yapabilecek.\n\nBununla birlikte, teknoloji ne kadar gelişirse gelişsin, insanın insana duyduğu ihtiyaç hiç bitmeyecek. Uzmanlar, gelecekte eğitimin hayat boyu süreceğini ve herkesin sürekli yeni şeyler öğrenmek zorunda kalacağını söylüyor.",
        [
            ("Uzmanlara göre yirmi yıl sonra ne olacak?", ["Hayat bugünden çok farklı olacak", "Hiçbir şey değişmeyecek", "Teknoloji duracak", "Şehirler küçülecek"]),
            ("Arabalar muhtemelen nasıl olacak?", ["Sürücüsüz", "Daha yavaş", "Daha pahalı", "Yasaklanmış"]),
            ("Hangi enerji yaygınlaşacak?", ["Güneş ve rüzgâr enerjisi", "Kömür", "Odun", "Doğalgaz"]),
            ("Metne göre gelecekte eğitim nasıl olacak?", ["Hayat boyu sürecek", "Kısalacak", "Bitecek", "Sadece okulda olacak"]),
            ("Yazara göre ne hiç bitmeyecek?", ["İnsanın insana ihtiyacı", "İş", "Trafik", "Enerji"]),
        ]),
    listening=([
        ("Ayşe", "Gelecek yıl yurt dışına gideceğim."),
        ("Can", "Gerçekten mi? Nereye?"),
        ("Ayşe", "Muhtemelen Almanya'ya. Henüz kesin değil."),
        ("Can", "Belki ben de seninle gelebilirim."),
        ("Ayşe", "Harika olur. Bu yıl sonuna kadar vizeyi almış olmalıyız."),
        ("Can", "Tamam, hemen başvuruyu hazırlayalım."),
    ], [
        ("Ayşe qayerga borishni rejalashtirgan?", ["Ehtimol Germaniyaga", "Fransiyaga", "Angliyaga", "Italiyaga"]),
        ("Yil oxirigacha nima tayyor bo'lishi kerak?", ["Viza", "Pul", "Diplom", "Kitob"]),
    ]),
    practice=[
        ('c', "\"Ertaga yomg'ir yog'ishi mumkin.\"", ["Yarın yağmur yağabilir.", "Yarın yağmur yağdı.", "Yarın yağmur yağıyor.", "Yarın yağmur yağmaz."]),
        ('c', "\"Kelasi yil ko'chib o'tamiz.\"", ["Gelecek yıl taşınacağız.", "Geçen yıl taşındık.", "Her yıl taşınırız.", "Şimdi taşınıyoruz."]),
        ('c', "\"Kechgacha ishimni tugatgan bo'laman.\"", ["Akşama kadar işimi bitirmiş olacağım.", "Akşam işimi bitirdim.", "Akşama kadar bitiriyorum.", "İşi bitirdi akşam."]),
        ('c', "\"Ehtimol\" turkchada:", ["muhtemelen", "hiç", "asla", "dün"]),
        ('o', "\"Sun'iy intellekt hayotimizni o'zgartiradi.\" gapini tuzing.", ["Yapay", "zekâ", "hayatımızı", "değiştirecek."]),
        ('o', "\"Balki sizga qo'ng'iroq qilaman.\" gapini tuzing.", ["Belki", "sizi", "arayacağım."]),
    ],
    writing=("O'n yildan keyingi hayotingiz haqida 3 gap yozing (kelasi zamon va ehtimol).",
             "On yıl sonra büyük bir şirkette çalışacağım. Belki başka bir ülkede yaşayacağım. Yeni diller öğrenmiş olacağım."),
    speaking=["Yarın yağmur yağabilir.", "Gelecek yıl taşınacağız.", "Muhtemelen toplantı ertelenecek.", "Belki seni ararım."],
    test=[
        ("-(y)AcAk qo'shimchasi nimani bildiradi?", ["kelasi zamon", "o'tgan zamon", "shart", "inkor"]),
        ("-(y)AbIlIr nimani bildiradi?", ["ehtimol, imkon", "majburiyat", "buyruq", "taqiq"]),
        ("\"Yağabilir\" nima degani?", ["yog'ishi mumkin", "yog'di", "yog'maydi", "yog'moqda"]),
        ("\"Muhtemelen\" nima degani?", ["ehtimol bilan", "hech qachon", "albatta", "kecha"]),
        ("\"Belki\" nima degani?", ["balki", "albatta", "hech", "faqat"]),
        ("\"Yapay zekâ\" nima?", ["sun'iy intellekt", "robot", "kompyuter", "internet"]),
        ("\"Hedef\" nima?", ["maqsad", "reja", "tahmin", "ehtimol"]),
        ("\"Enerji\" so'zining ma'nosi:", ["energiya", "texnologiya", "kosmos", "ixtiro"]),
        ("\"Tahmin\" nima?", ["taxmin", "maqsad", "ehtimol", "ixtiro"]),
        ("\"Yenilenebilir\" nima?", ["qayta tiklanadigan", "yangi", "qimmat", "eski"]),
    ],
    bank=[
        ("\"Uzay\" nima?", ["kosmos", "yer", "osmon", "dengiz"]),
        ("\"İhtimal\" nima?", ["ehtimol", "maqsad", "taxmin", "ixtiro"]),
        ("\"Toplantı yapmak üzereyiz.\" nima?", ["Yig'ilish o'tkazish arafasidamiz.", "Yig'ilish o'tkazdik.", "Yig'ilish bo'lmaydi.", "Yig'ilishni bekor qildik."]),
        ("\"Mutlaka\" nima degani?", ["albatta", "balki", "hech", "kam"]),
        ("\"Herhalde\" nima degani?", ["ehtimol", "albatta", "hech qachon", "kecha"]),
        ("\"Başaracaksın\" nima degani?", ["uddalaysan", "uddalading", "uddalamaysan", "uddalayapsan"]),
        ("Qaysi gap bitmiş gelecek?", ["Saat ona kadar işi bitirmiş olacak.", "İşi bitirdi.", "İşi bitiriyor.", "İşi bitirecek."]),
        ("\"Güneş enerjisi\" nima?", ["quyosh energiyasi", "shamol energiyasi", "ko'mir", "suv"]),
        ("\"Sürücüsüz araba\" nima?", ["haydovchisiz mashina", "tez mashina", "qimmat mashina", "kichik mashina"]),
        ("\"Hayat boyu\" nima?", ["umr bo'yi", "bir kun", "bir hafta", "bir yil"]),
        ("\"Yaygınlaşmak\" nima?", ["keng tarqalmoq", "yo'qolmoq", "kamayib ketmoq", "to'xtamoq"]),
        ("\"Gelecek yıl\" nima?", ["kelasi yil", "o'tgan yil", "har yil", "bu yil"]),
    ],
)

TOPICS = [A, B, C]
