# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u3a', "A. Sözlerin Gizemi — So'zlarning siri", 56, 60,
    goals=[
        "Deyim va atasözlarining ma'nosi va farqini bilish",
        "Kundalik nutqda mashhur deyimlarni qo'llash",
        "So'zlarning kelib chiqishi (etimologiya) haqidagi matnni tushunish",
    ],
    blocks=[
        ("Deyim nedir?",
         "Deyim — ma'nosi so'zlar yig'indisidan emas, butun birikmadan kelib chiqadigan qotib qolgan ifoda: Gözden düşmek (obro'sini yo'qotmoq), burun kıvırmak (ensasi qotmoq, mensimaslik), ağzı kulağında (xursand), kulak asmak (quloq solmoq). Deyim fe'l shaklida o'zgaradi: gözden düştü, gözden düşecek."),
        ("Atasözü nedir?",
         "Atasözü — tugallangan fikrni bildiruvchi hikmatli gap: Damlaya damlaya göl olur. (Tomchi-tomchi ko'l bo'lur.) Ak akçe kara gün içindir. (Oq tanga qora kun uchun.) Atasözlari o'zgarmaydi va nasihat beradi."),
        ("Ünlü sözlerin hikâyesi",
         "Ko'p so'zlarning kelib chiqishi qiziq hikoyaga ega: \"Kahve\" arabcha qahwa'dan, \"çay\" xitoycha cha'dan, \"merhaba\" arabcha marhaba'dan olingan. Etimologiya so'zning tarixini o'rganadi. Turkchada \"-lA\" so'zi \"bilan\" ma'nosini beradi: kalemle yazmak."),
    ],
    facts=[
        "Deyim — ma'nosi bir butun; shakli fe'lga qarab o'zgaradi.",
        "Atasözü — o'zgarmas, nasihat beruvchi tugal gap.",
        "Damlaya damlaya göl olur = tomchi-tomchi ko'l bo'lur.",
        "Kahve, çay, merhaba — chet tillardan kirgan, turkchalashgan so'zlar.",
    ],
    vocab=[
        ("deyim", "idioma, frazeologizm", "Bu deyimi sık kullanırız.", "Bu idiomani tez-tez ishlatamiz."),
        ("atasözü", "maqol", "Atasözleri halkın bilgeliğidir.", "Maqollar xalq donoligidir."),
        ("anlam", "ma'no", "Kelimenin anlamını sözlükte buldum.", "So'zning ma'nosini lug'atdan topdim."),
        ("mecaz", "ko'chma ma'no", "Bu cümle mecaz anlamda kullanılmış.", "Bu gap ko'chma ma'noda ishlatilgan."),
        ("söz dağarcığı", "lug'at boyligi", "Okudukça söz dağarcığın genişler.", "O'qigan sari lug'at boyligingiz kengayadi."),
        ("kaynak", "manba", "Bu kelimenin kaynağı Arapça.", "Bu so'zning manbai arabcha."),
        ("sözlük", "lug'at", "Sözlüğe bakmadan çeviremem.", "Lug'atga qaramay tarjima qila olmayman."),
        ("hikmet", "hikmat", "Her atasözünde bir hikmet var.", "Har maqolda hikmat bor."),
        ("nasihat", "nasihat", "Büyüklerin nasihatini dinlemeli.", "Kattalarning nasihatini tinglash kerak."),
        ("kulak asmak", "quloq solmoq", "Uyarıya kulak asmadı.", "Ogohlantirishga quloq solmadi."),
        ("gözden düşmek", "obro'sini yo'qotmoq", "Yalan söyleyince gözden düştü.", "Yolg'on aytgach obro'sidan tushdi."),
        ("burun kıvırmak", "mensimaslik", "Verilen işe burun kıvırdı.", "Berilgan ishni mensimadi."),
    ],
    reading=("Atasözleri ne anlatır?",
        "Atasözleri, bir milletin yüzyıllar boyunca biriktirdiği tecrübelerin kısa ve etkileyici ifadesidir. \"Damlaya damlaya göl olur\" sözü, küçük birikimlerin zamanla büyük sonuçlar doğuracağını anlatır. \"Ak akçe kara gün içindir\" ise tasarruf etmenin önemini hatırlatır.\n\nDeyimler ise farklıdır. \"Ağzı kulağında\" diyerek çok sevinen birini anlatırız; bu söz kelime kelime çevrilirse anlam çıkmaz. Yabancı dil öğrenenler için deyimler zordur, çünkü anlam kelimelerden değil ifadeden doğar.\n\nSöz dağarcığını genişletmek isteyen biri deyim ve atasözlerini öğrenmelidir. Böylece hem anadili konuşanları daha iyi anlar hem de kendini daha etkili ifade eder.",
        [
            ("Atasözleri neyin ifadesidir?", ["Yüzyıllarca biriken tecrübelerin", "Yeni icatların", "Kanunların", "Şarkıların"]),
            ("\"Damlaya damlaya göl olur\" ne anlatır?", ["Küçük birikimler büyük sonuç verir", "Yağmur çok yağar", "Göller kurur", "Su pahalıdır"]),
            ("\"Ağzı kulağında\" ne anlatır?", ["Çok sevinen birini", "Çok konuşan birini", "Kızgın birini", "Uykulu birini"]),
            ("Deyimler yabancılar için neden zordur?", ["Anlam kelimelerden değil ifadeden doğar", "Çok uzundur", "Yazılmaz", "Eskidir"]),
            ("Söz dağarcığını genişletmek için ne yapmalı?", ["Deyim ve atasözlerini öğrenmeli", "Sadece dilbilgisi çalışmalı", "TV izlememeli", "Hiçbir şey"]),
        ]),
    listening=([
        ("Hoca", "\"Ak akçe kara gün içindir\" atasözünü anlayan var mı?"),
        ("Öğrenci", "Para biriktirmenin önemini anlatıyor sanırım."),
        ("Hoca", "Doğru. Peki \"burun kıvırmak\" ne demek?"),
        ("Öğrenci", "Bir şeyi beğenmemek, küçümsemek."),
        ("Hoca", "Çok güzel. Şimdi bunlarla birer cümle kuralım."),
        ("Öğrenci", "O verilen işe burun kıvırdı ama sonra pişman oldu."),
    ], [
        ("\"Ak akçe kara gün içindir\" nimani anglatadi?", ["Pul yig'ishning ahamiyatini", "Pul sarflashni", "Qarzni", "Savdoni"]),
        ("\"Burun kıvırmak\" nima?", ["Mensimaslik", "Xursand bo'lish", "Yig'lash", "Kulish"]),
    ]),
    practice=[
        ('c', "\"Maqol\" turkchada:", ["atasözü", "deyim", "mecaz", "sözlük"]),
        ('c', "\"Lug'at boyligi\" turkchada:", ["söz dağarcığı", "söz sanatı", "kelime oyunu", "dil bilgisi"]),
        ('c', "\"Quloq solmoq\" deyimi:", ["kulak asmak", "burun kıvırmak", "gözden düşmek", "ağzı kulağında olmak"]),
        ('c', "\"Obro'sini yo'qotmoq\" deyimi:", ["gözden düşmek", "kulak asmak", "burun kıvırmak", "dil dökmek"]),
        ('o', "\"Tomchi-tomchi ko'l bo'lur.\" gapini tuzing.", ["Damlaya", "damlaya", "göl", "olur."]),
        ('o', "\"U ogohlantirishga quloq solmadi.\" gapini tuzing.", ["Uyarıya", "kulak", "asmadı."]),
    ],
    writing=("O'zbek tilidagi bir maqolni turkchaga o'xshash maqol bilan taqqoslab 2-3 gap yozing.",
             "Türkçedeki \"Damlaya damlaya göl olur\" atasözü Özbekçede de aynı anlamdadır. İkisi de birikimin önemini anlatır."),
    speaking=["Damlaya damlaya göl olur.", "Ağzı kulağında.", "Uyarıya kulak asmadı.", "Sözlüğe bakmadan çeviremem."],
    test=[
        ("Deyim nima?", ["ma'nosi butun birikmadan kelib chiqadigan qotgan ifoda", "tugal nasihat gap", "she'r", "so'z yasovchi qo'shimcha"]),
        ("Maqol nima?", ["nasihat beruvchi tugal gap", "so'z o'yini", "lug'at", "ko'chma ma'no"]),
        ("\"Ağzı kulağında\" nima?", ["juda xursand", "juda g'azablangan", "uyquli", "charchagan"]),
        ("\"Burun kıvırmak\" nima?", ["mensimaslik", "quvonmoq", "kulmoq", "yig'lamoq"]),
        ("\"Gözden düşmek\" nima?", ["obro'sini yo'qotmoq", "ko'zi og'rimoq", "yiqilmoq", "ko'rmoq"]),
        ("\"Mecaz\" nima?", ["ko'chma ma'no", "to'g'ri ma'no", "maqol", "lug'at"]),
        ("\"Sözlük\" nima?", ["lug'at", "so'z", "maqol", "kitob"]),
        ("\"Hikmet\" nima?", ["hikmat", "nasihat", "lug'at", "ma'no"]),
        ("\"Kaynak\" nima?", ["manba", "ma'no", "lug'at", "gap"]),
        ("\"Kulak asmak\" nima?", ["quloq solmoq", "quloqni berkitmoq", "eshitmaslik", "gapirmaslik"]),
    ],
    bank=[
        ("\"Ak akçe kara gün içindir\" nimani bildiradi?", ["tejamkorlik", "isrof", "savdo", "sovg'a"]),
        ("\"Anlam\" nima?", ["ma'no", "manba", "gap", "so'z"]),
        ("\"Nasihat\" nima?", ["nasihat", "buyruq", "taqiq", "iltimos"]),
        ("\"Merhaba\" qaysi tildan?", ["arabchadan", "forschadan", "yunoncha", "lotincha"]),
        ("\"Çay\" qaysi tildan?", ["xitoychadan", "arabchadan", "forschadan", "lotincha"]),
        ("\"Etimoloji\" nimani o'rganadi?", ["so'z kelib chiqishini", "gap tuzilishini", "yozuvni", "talaffuzni"]),
        ("Deyim shakli o'zgaradimi?", ["ha, fe'l shakliga qarab", "yo'q, hech qachon", "faqat inkorda", "faqat ko'plikda"]),
        ("\"Kulak asmadı\" nima?", ["quloq solmadi", "eshitdi", "so'radi", "kuldi"]),
        ("\"Söz dağarcığı\" nima?", ["lug'at boyligi", "gap tuzilishi", "yozuv", "tinish belgisi"]),
        ("\"Yabancı dil\" nima?", ["chet tili", "ona tili", "eski til", "yangi til"]),
        ("\"Etkili\" nima?", ["ta'sirchan", "ta'sirsiz", "uzun", "qisqa"]),
        ("\"Tecrübe\" nima?", ["tajriba", "sinov", "xato", "yutuq"]),
    ],
)

B = topic(
    'u3b', "B. Sazın ve Sözün Ustaları — Soz va so'z ustalari", 61, 65,
    goals=[
        "Aşıklık an'anasi va xalq shoirlari haqida o'qish",
        "Sifat-fe'llar (-An, -DIk, -(y)AcAk, -mIş) ni murakkab gapda qo'llash",
        "Yunus Emre, Karacaoğlan, Aşık Veysel kabi shoirlarni tanish",
    ],
    blocks=[
        ("Sıfat-fiil: -An (özne), -DIk (nesne)",
         "Sifat-fe'l bosh gapdagi egani yoki to'ldiruvchini tavsiflaydi. -An ega haqida: Saz çalan âşık (soz chalayotgan oshiq). -DIk to'ldiruvchi haqida: Âşığın çaldığı saz (oshiq chalgan soz). -(y)AcAk kelajak ishni: Yarın okuyacağım şiir. -mIş tugallangan holatni: Yazılmış şiir."),
        ("Aşık geleneği",
         "Âşık — saz chalib, o'zi yozgan yoki xalq she'rlarini kuylagan xalq shoiri. Deyişme (o'zaro qo'shiq musobaqasi), taşlama (hajviy), koşma (xalq she'r shakli) mashhur. Yunus Emre (XIII-XIV asr), Karacaoğlan (XVII asr), Aşık Veysel (1894-1973) eng mashhur ismlar."),
        ("Ek fiil -(y)mIş ve -DIr ile hüküm",
         "Shoir haqida xulosa va taxmin: O büyük bir ustaymış (u katta usta ekan). Bu şiir halk edebiyatına aittir. Ek fiil ma'lumotni yumshoq yoki rasmiy tarzda beradi."),
    ],
    facts=[
        "-An (ega) va -DIk (to'ldiruvchi) sifat-fe'l: saz çalan âşık / âşığın çaldığı saz.",
        "Âşık — saz bilan she'r kuylagan xalq shoiri.",
        "Yunus Emre, Karacaoğlan, Aşık Veysel — turk xalq she'riyatining mashhur siymolari.",
        "Deyişme — oshiqlarning o'zaro she'riy bahsi.",
    ],
    vocab=[
        ("âşık", "xalq shoiri (oshiq)", "Âşık sazıyla köy köy dolaşırdı.", "Oshiq sozi bilan qishloqma-qishloq yurardi."),
        ("saz", "soz (cholg'u)", "Sazın sesi insanı etkiler.", "Sozning ovozi insonga ta'sir qiladi."),
        ("şiir", "she'r", "Bu şiiri ezbere biliyorum.", "Bu she'rni yoddan bilaman."),
        ("koşma", "xalq she'ri shakli", "Koşma halk şiirinin bir türüdür.", "Koshma xalq she'riyatining turi."),
        ("deyiş", "qo'shiq-she'r", "Aşık Veysel'in deyişleri çok sevilir.", "Oshiq Vaysalning qo'shiqlari sevib tinglanadi."),
        ("ozan", "qadimiy xalq shoiri", "Ozanlar destan anlatırdı.", "Ozanlar doston aytardi."),
        ("destan", "doston", "Dede Korkut Destanı çok eskidir.", "Dada Qorqut dostoni juda qadimiy."),
        ("ustalık", "ustalik", "Ustalık yıllarla kazanılır.", "Ustalik yillar bilan orttiriladi."),
        ("ezgi", "kuy", "Güzel bir ezgi dinledim.", "Chiroyli bir kuy tingladim."),
        ("söylemek", "aytmoq, kuylamoq", "Türkü söyleyen kızı tanıyorum.", "Qo'shiq aytayotgan qizni taniyman."),
        ("anlatmak", "so'zlab bermoq", "Dedem masal anlatırdı.", "Bobom ertak aytib berardi."),
        ("miras", "meros", "Halk şiiri bize miras kaldı.", "Xalq she'riyati bizga meros bo'lib qoldi."),
    ],
    reading=("Aşık Veysel'in sazı",
        "Aşık Veysel, 1894'te Sivas'ın Şarkışla ilçesinde doğdu. Küçük yaşta çiçek hastalığı yüzünden gözlerini kaybetti. Ancak bu onu yıldırmadı; babasının aldığı sazı çalmayı öğrendi ve şiirler yazmaya başladı.\n\nVeysel'in yazdığı dizeler, köy hayatını, doğayı ve insan sevgisini anlatır. \"Uzun ince bir yoldayım\" şiiri en çok bilinen eserlerindendir. Saz çalan ve türkü söyleyen bu usta, köy köy dolaşarak halkın içinde yaşadı.\n\nGünümüzde hâlâ onun sözleri dinleniyor. Aşık Veysel, Türk halk şiirinin ve müziğinin ölümsüz isimlerinden biri olarak kabul edilir; 1973'te Sivas'ta vefat etti.",
        [
            ("Aşık Veysel nerede doğdu?", ["Sivas'ın Şarkışla ilçesinde", "İstanbul'da", "Konya'da", "Ankara'da"]),
            ("Gözlerini neden kaybetti?", ["Çiçek hastalığı yüzünden", "Kaza yüzünden", "Savaşta", "Doğuştan"]),
            ("Sazı kim aldı?", ["Babası", "Dedesi", "Öğretmeni", "Arkadaşı"]),
            ("En bilinen şiiri hangisi?", ["Uzun ince bir yoldayım", "Gelin canlar", "Bu dünya bir pencere", "Yaprak dökümü"]),
            ("Veysel kaç yılında vefat etti?", ["1973", "1894", "1950", "2000"]),
        ]),
    listening=([
        ("Mert", "Dün akşam saz çalan bir âşık dinledim."),
        ("Elif", "Hangi türküleri söylüyordu?"),
        ("Mert", "Aşık Veysel'in yazdığı deyişleri okuyordu."),
        ("Elif", "Ben de onun sözlerini çok severim."),
        ("Mert", "Gelecek hafta festivalde birçok âşık çalacak."),
        ("Elif", "O zaman birlikte gidelim."),
    ], [
        ("Mert kimni tingladi?", ["Soz chalgan oshiqni", "Pianinochini", "Gitarachini", "Qo'shiqchi qizni"]),
        ("Kelasi hafta nima bo'ladi?", ["Festivalda oshiqlar chiqadi", "Konsert bekor", "Maktab yig'ilishi", "Kitob taqdimoti"]),
    ]),
    practice=[
        ('c', "\"Soz chalayotgan oshiq\"", ["saz çalan âşık", "saz çaldığı âşık", "saz çalacak âşık", "saz çalmış âşıktan"]),
        ('c', "\"Oshiq chalgan soz\"", ["âşığın çaldığı saz", "âşığın çalan saz", "âşık çalan sazı", "âşıkta çalmış saz"]),
        ('c', "\"Men yarin o'qiydigan she'r\"", ["yarın okuyacağım şiir", "dün okuduğum şiir", "okuyan şiir", "okumuş şiir"]),
        ('c', "\"Doston\" turkchada:", ["destan", "ezgi", "deyiş", "koşma"]),
        ('o', "\"U soz chalib qo'shiq aytdi.\" gapini tuzing.", ["Saz", "çalıp", "türkü", "söyledi."]),
        ('o', "\"Bu she'rni yozgan shoirni taniyman.\" gapini tuzing.", ["Bu", "şiiri", "yazan", "şairi", "tanıyorum."]),
    ],
    writing=("Sevimli shoir yoki qo'shiqchi haqida sifat-fe'llar bilan 3 gap yozing.",
             "Şiir yazan bir şairi çok severim. Okuduğum şiirlerde doğa anlatılır. Yarın dinleyeceğim konser için heyecanlıyım."),
    speaking=["Saz çalan âşık geldi.", "Âşığın çaldığı saz çok güzeldi.", "Bu şiiri ezbere biliyorum.", "Halk şiiri bize mirastır."],
    test=[
        ("-An sifat-fe'li nimani tavsiflaydi?", ["egani", "to'ldiruvchini", "payti", "sababni"]),
        ("-DIk sifat-fe'li nimani tavsiflaydi?", ["to'ldiruvchini (obyektni)", "egani", "o'rinni", "tezlikni"]),
        ("\"Saz çalan\" nima?", ["soz chalayotgan", "soz chalgan joy", "soz chalmaydigan", "soz chalish uchun"]),
        ("\"Çaldığı saz\" nima?", ["u chalgan soz", "soz chalgan odam", "soz chalish", "soz chalmaslik"]),
        ("\"Âşık\" kim?", ["soz bilan she'r kuylagan xalq shoiri", "rassom", "o'qituvchi", "tarixchi"]),
        ("Aşık Veysel qaysi yilda tug'ilgan?", ["1894", "1973", "1923", "1250"]),
        ("\"Destan\" nima?", ["doston", "qo'shiq", "she'r", "kuy"]),
        ("\"Miras\" nima?", ["meros", "ixtiro", "ertak", "kuy"]),
        ("\"Ezgi\" nima?", ["kuy", "she'r", "doston", "soz"]),
        ("\"Ozan\" kim?", ["qadimiy xalq shoiri", "rassom", "hakam", "muallim"]),
    ],
    bank=[
        ("\"Uzun ince bir yoldayım\" kimning she'ri?", ["Aşık Veysel", "Yunus Emre", "Karacaoğlan", "Nazım Hikmet"]),
        ("\"Deyişme\" nima?", ["oshiqlarning she'riy bahsi", "yakka qo'shiq", "roman", "ertak"]),
        ("\"Koşma\" nima?", ["xalq she'ri shakli", "ertak", "roman", "maqol"]),
        ("\"Söylemek\" nima?", ["aytmoq, kuylamoq", "yozmoq", "o'qimoq", "eshitmoq"]),
        ("\"Anlatmak\" nima?", ["so'zlab bermoq", "yashirmoq", "unutmoq", "yozmoq"]),
        ("\"Ustalık\" nima?", ["ustalik", "yangilik", "xato", "dam"]),
        ("\"Yazılmış şiir\" nima?", ["yozilgan she'r", "yozayotgan she'r", "yoziladigan she'r", "yozmaydigan she'r"]),
        ("\"Okuyacağım kitap\" nima?", ["o'qiydigan kitobim", "o'qigan kitobim", "o'qiyotgan kitobim", "o'qimaydigan kitobim"]),
        ("\"Bu şiir halk edebiyatına aittir.\" ma'nosi:", ["Bu she'r xalq adabiyotiga tegishli.", "Bu she'r eski.", "Bu she'r yangi.", "Bu she'r qisqa."]),
        ("\"Yıldırmak\" nima?", ["qo'rqitib to'xtatmoq", "yoritmoq", "yig'lamoq", "ko'tarmoq"]),
        ("\"Köy köy dolaşmak\" nima?", ["qishloqma-qishloq yurmoq", "uyda o'tirmoq", "shaharga bormoq", "qishloqni tark etmoq"]),
        ("\"Ölümsüz\" nima?", ["o'lmas", "o'lik", "kasal", "tirik"]),
    ],
)

C = topic(
    'u3c', "C. Hayalden Mecaza — Xayoldan ko'chma ma'noga", 66, 72,
    goals=[
        "Benzetme (gibi, sanki, âdeta, -cA) va mecaz ifodalarini ishlatish",
        "Adabiy tilda obrazli ifodalarni tanish",
        "Qisqa tasviriy matn yozish",
    ],
    blocks=[
        ("Benzetme: gibi, sanki, âdeta, -cA",
         "Taqqoslash vositalari: \"gibi\" (kabi): Gözleri deniz gibi. \"Sanki\" (go'yo): Sanki rüyadaydım. \"Âdeta\" (xuddi): Âdeta bir kuş gibi uçtu. -cA o'xshatish qo'shimchasi: aslanca (sherdek) savaştı. Taqqoslash fikrni jonli qiladi."),
        ("Mecaz ve istiare",
         "Mecaz — so'zning o'z ma'nosi o'rniga ko'chma ma'noda ishlatilishi: Bu çocuk bir elmas. (Bu bola bebaho.) Istiare (metafora) — o'xshatish elementi tushib qolgan shakl: Hayat bir yolculuktur. Kinaye (ishora): \"Uzun boylu\" o'rniga \"direk gibi\" deyish."),
        ("Abartı ve kişileştirme",
         "Mubolag'a: Bir yıl bekledim. (bir yil kutdim — juda uzoq). Jonlantirish: Rüzgâr kapıyı çaldı. (Shamol eshikni qoqdi.) Bu vositalar badiiy matnda tasvirni boyitadi."),
    ],
    facts=[
        "gibi = kabi; sanki = go'yo; âdeta = xuddi.",
        "Mecaz — ko'chma ma'no; istiare — qisqartirilgan o'xshatish.",
        "Mubolag'a va jonlantirish badiiy tasvirni kuchaytiradi.",
        "Nazım Hikmet, Orhan Veli, Yahya Kemal mashhur obrazli she'riyat shoirlari.",
    ],
    vocab=[
        ("benzetme", "o'xshatish", "Şiirde güzel benzetmeler var.", "She'rda chiroyli o'xshatishlar bor."),
        ("mecaz", "ko'chma ma'no", "Mecaz anlamı metni zenginleştirir.", "Ko'chma ma'no matnni boyitadi."),
        ("hayal", "xayol", "Çocuk hayal dünyasında yaşar.", "Bola xayol dunyosida yashaydi."),
        ("gerçek", "haqiqat", "Gerçekle hayal birbirine karıştı.", "Haqiqat va xayol aralashib ketdi."),
        ("duygu", "tuyg'u", "Şair duygularını dizelere döktü.", "Shoir tuyg'ularini misralarga to'kdi."),
        ("imge", "obraz, timsol", "Şiirde bulut bir imgedir.", "She'rda bulut bir timsol."),
        ("sanki", "go'yo", "Sanki rüyada gibiydim.", "Go'yo tushda edim."),
        ("âdeta", "xuddi", "Âdeta uçuyordu.", "Xuddi uchayotgandek edi."),
        ("abartı", "mubolag'a", "Bu bir abartı, ciddiye alma.", "Bu mubolag'a, jiddiy olma."),
        ("tasvir", "tasvir", "Yazar köyü ayrıntılı tasvir etmiş.", "Yozuvchi qishloqni batafsil tasvirlagan."),
        ("dize", "misra", "İlk dize çok etkiliydi.", "Birinchi misra juda ta'sirli edi."),
        ("coşku", "jo'shqinlik", "Konuşmasında büyük bir coşku vardı.", "Nutqida katta jo'shqinlik bor edi."),
    ],
    reading=("Gözleri deniz gibi",
        "Şiirde ve gündelik dilde benzetmeler, anlatımı güçlendirir. \"Gözleri deniz gibi\" dediğimizde, yalnızca renkten değil, derinlikten ve huzurdan da söz ederiz. \"Sanki rüyadaydım\" diyen biri, yaşadığı olayın gerçek dışı güzelliğini anlatır.\n\nMecaz anlam ise sözcüğün asıl anlamından uzaklaşmasıdır. \"Hayat bir yolculuktur\" cümlesinde hayat, gerçekten bir yol değildir; ama önümüzdeki engelleri ve durakları düşündürür.\n\nŞairler duygularını imgelerle aktarır. Orhan Veli gündelik hayatı sade imgelerle anlatırken, Yahya Kemal İstanbul'u bir sevgili gibi över. Okur, bu imgeleri çözümledikçe şiirin derin anlamına ulaşır.",
        [
            ("\"Gözleri deniz gibi\" neyi anlatır?", ["Derinlik ve huzuru", "Yalnızca rengi", "Hastalığı", "Büyüklüğü"]),
            ("\"Sanki rüyadaydım\" ne anlatır?", ["Yaşananın gerçek dışı güzelliğini", "Uyuduğunu", "Yorgunluğu", "Hastalığı"]),
            ("\"Hayat bir yolculuktur\" cümlesi ne türdür?", ["Mecaz (istiare)", "Soru", "Emir", "Sayı"]),
            ("Orhan Veli şiirlerinde ne anlatır?", ["Gündelik hayatı sade imgelerle", "Savaşı", "Tarihi", "Bilimi"]),
            ("Okur şiirin anlamına nasıl ulaşır?", ["İmgeleri çözümleyerek", "Sesli okuyarak", "Ezberleyerek", "Kopyalayarak"]),
        ]),
    listening=([
        ("Öğretmen", "Bu dizede şair bulutu neye benzetmiş?"),
        ("Öğrenci", "Bir yelkenliye benzetmiş sanırım."),
        ("Öğretmen", "Doğru. Peki bunun amacı ne?"),
        ("Öğrenci", "Bulutun hareketini ve hafifliğini göstermek."),
        ("Öğretmen", "Çok güzel. Şimdi sen de bir benzetme kur."),
        ("Öğrenci", "Gece, siyah bir kadife gibi örtülmüştü."),
    ], [
        ("Shoir bulutni nimaga o'xshatgan?", ["Yelkanli kemaga", "Daryoga", "Tog'ga", "Uyga"]),
        ("O'quvchi tuzgan o'xshatish qaysi?", ["Tun qora baxmaldek", "Quyosh oltin", "Dengiz ko'k", "Yer katta"]),
    ]),
    practice=[
        ('c', "\"Ko'zlari dengizdek.\"", ["Gözleri deniz gibi.", "Gözleri denizde.", "Gözleri denize.", "Gözleri deniz için."]),
        ('c', "\"Go'yo tushda edim.\"", ["Sanki rüyadaydım.", "Hiç rüyadaydım.", "Rüyada değilim.", "Rüya gördü."]),
        ('c', "\"Xuddi qushday uchdi.\"", ["Âdeta bir kuş gibi uçtu.", "Hiç bir kuş uçtu.", "Kuşa uçtu.", "Kuş uçmadı."]),
        ('c', "\"Mubolag'a\" turkchada:", ["abartı", "benzetme", "imge", "dize"]),
        ('o', "\"Hayot — bu yo'lovchilikdir.\" gapini tuzing.", ["Hayat", "bir", "yolculuktur."]),
        ('o', "\"Shamol eshikni qoqdi.\" gapini tuzing.", ["Rüzgâr", "kapıyı", "çaldı."]),
    ],
    writing=("Tabiat manzarasini (tong yoki tun) 3 gapda o'xshatish va jonlantirish bilan tasvirlang.",
             "Sabah, güneş bir altın top gibi doğdu. Rüzgâr yapraklarla fısıldaştı. Deniz sanki uyanıyordu."),
    speaking=["Gözleri deniz gibi.", "Sanki rüyadaydım.", "Âdeta uçuyordu.", "Rüzgâr kapıyı çaldı."],
    test=[
        ("\"Gibi\" nima vazifada keladi?", ["o'xshatish", "inkor", "shart", "payt"]),
        ("\"Sanki\" nima degani?", ["go'yo", "albatta", "faqat", "hech"]),
        ("\"Âdeta\" nima degani?", ["xuddi", "faqat", "hech", "doim"]),
        ("-cA qo'shimchasi (aslanca) nima bildiradi?", ["o'xshashlik, usul", "ko'plik", "inkor", "payt"]),
        ("\"Mecaz\" nima?", ["ko'chma ma'no", "asl ma'no", "maqol", "lug'at"]),
        ("\"Hayat bir yolculuktur.\" qaysi usul?", ["istiare (metafora)", "mubolag'a", "savol", "buyruq"]),
        ("\"Dize\" nima?", ["misra", "she'r", "doston", "kuy"]),
        ("\"Imge\" nima?", ["obraz, timsol", "tuyg'u", "kuy", "so'z"]),
        ("\"Abartı\" nima?", ["mubolag'a", "o'xshatish", "kinoya", "inkor"]),
        ("\"Coşku\" nima?", ["jo'shqinlik", "xafalik", "uyqu", "charchoq"]),
    ],
    bank=[
        ("\"Hayal\" nima?", ["xayol", "haqiqat", "tush", "xotira"]),
        ("\"Gerçek\" nima?", ["haqiqat", "xayol", "yolg'on", "tush"]),
        ("\"Duygu\" nima?", ["tuyg'u", "fikr", "misra", "obraz"]),
        ("\"Tasvir\" nima?", ["tasvir", "o'xshatish", "mubolag'a", "kinoya"]),
        ("\"Kişileştirme\" nima?", ["jonlantirish", "mubolag'a", "o'xshatish", "inkor"]),
        ("\"Rüzgâr kapıyı çaldı.\" qaysi usul?", ["jonlantirish", "mubolag'a", "o'xshatish", "savol"]),
        ("\"Bir yıl bekledim.\" (juda uzun) qaysi usul?", ["mubolag'a", "jonlantirish", "benzetme", "inkor"]),
        ("\"Elmas\" mecazda nima?", ["bebaho kishi", "tosh", "pul", "oyna"]),
        ("\"Aslanca\" nima?", ["sherdek", "ko'p", "tez", "sekin"]),
        ("\"Kinaye\" nima?", ["ishora", "tasvir", "o'xshatish", "mubolag'a"]),
        ("\"Yahya Kemal\" kim?", ["shoir", "rassom", "olim", "siyosatchi"]),
        ("\"Okur\" nima?", ["kitobxon", "yozuvchi", "shoir", "nashriyotchi"]),
    ],
)

TOPICS = [A, B, C]
