# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u4a', "A. Hayvanlar — Hayvonlar", 74, 80,
    goals=[
        "Zarf-fe'llar (-(y)Ip, -(y)ArAk, -mAdAn, -(y)IncA) ni qo'llash",
        "Hayvonlar olami, ularning xulq-atvori va yashash muhiti lug'atini bilish",
        "Hayvon haqida ma'lumot beruvchi matn tuzish",
    ],
    blocks=[
        ("-(y)Ip: ketma-ket ishlar",
         "-(y)Ip bir necha ishni ketma-ket bog'laydi va ish egasi bir bo'ladi: Kuş dalda uçup ağaca kondu. Aslan avını gözleyip saldırdı. Birinchi ish tugagach, ikkinchisi boshlanadi, oxirgi fe'l zamon va shaxsni bildiradi."),
        ("-(y)ArAk va -mAdAn: usul va inkor",
         "-(y)ArAk ish qanday bajarilganini bildiradi: Kuşlar kanat çırparak uçar. -mAdAn \"...may\" ma'nosida: Kedi hiç ses çıkarmadan yaklaştı. Bu ikkisi ham asosiy fe'lning holatini tasvirlaydi."),
        ("-(y)IncA ve -DIğIndA: payt ravishdoshi",
         "-(y)IncA \"...gach, ...ganda\" ma'nosida: Yağmur başlayınca hayvanlar barınağa döndü. -DIğIndA ham payt bildiradi: Avcı yaklaştığında kuşlar uçtu. Ikkala tuzilmada keyingi ish oldingisidan so'ng yoki u bilan birga bo'ladi."),
    ],
    facts=[
        "-(y)Ip = ...ib (ketma-ketlik); -(y)ArAk = ...ib (usul); -mAdAn = ...may.",
        "-(y)IncA = ...gach/...ganda (payt).",
        "Qora ayiq, sher va burgut yirtqich hayvonlar qatoriga kiradi.",
        "Ko'p qushlar kuzda issiq o'lkalarga ko'chib o'tadi (göç).",
    ],
    vocab=[
        ("hayvan", "hayvon", "Hayvanlara iyi davranmak gerekir.", "Hayvonlarga yaxshi munosabatda bo'lish kerak."),
        ("yırtıcı", "yirtqich", "Aslan yırtıcı bir hayvandır.", "Sher yirtqich hayvon."),
        ("otçul", "o'txo'r", "İnek otçul bir hayvandır.", "Sigir o'txo'r hayvon."),
        ("göç", "ko'chish", "Kuşlar kışın güneye göç eder.", "Qushlar qishda janubga ko'chadi."),
        ("barınak", "boshpana", "Hayvanlar barınakta kışı geçirir.", "Hayvonlar qishni boshpanada o'tkazadi."),
        ("av", "ov", "Kartal avını havadan izler.", "Burgut o'ljasini havodan kuzatadi."),
        ("sürü", "to'da, suruv", "Kurtlar sürü hâlinde yaşar.", "Bo'rilar to'da bo'lib yashaydi."),
        ("yuva", "in, uya", "Kuş yuvasını ağaca yaptı.", "Qush uyasini daraxtga qurdi."),
        ("kanat", "qanot", "Kuşlar kanatlarıyla uçar.", "Qushlar qanotlari bilan uchadi."),
        ("pençe", "panja", "Kartalın pençeleri güçlüdür.", "Burgutning panjalari kuchli."),
        ("nesli tükenmek", "nasli qurimoq", "Birçok türün nesli tükeniyor.", "Ko'p turlarning nasli qurimoqda."),
        ("koruma altında", "himoya ostida", "Bu tür koruma altındadır.", "Bu tur himoya ostida."),
    ],
    reading=("Leylek yolculuğu",
        "Leylekler her sonbaharda binlerce kilometre uçarak Avrupa'dan Afrika'ya göç eder. Yola çıkmadan önce büyük sürüler oluştururlar. Havada kanatlarını açıp rüzgârdan yararlanarak enerjilerini korurlar.\n\nGöç sırasında leylekler dinlenmek için tarlalara ve göl kıyılarına konar. Yiyecek bulup güç topladıktan sonra yeniden yola koyulurlar. Bahar gelince yuvalarına geri dönerler; çoğu her yıl aynı yuvayı kullanır.\n\nBugün leyleklerin birçok bölgede sayısı azalıyor. Bunun nedeni, doğal yaşam alanlarının yok olması. Bu yüzden birçok ülkede leylekler koruma altına alındı.",
        [
            ("Leylekler her sonbaharda nereye göç eder?", ["Avrupa'dan Afrika'ya", "Asya'dan Avrupa'ya", "Afrika'dan Avrupa'ya", "Amerika'ya"]),
            ("Leylekler yolculukta enerjilerini nasıl korur?", ["Rüzgârdan yararlanarak", "Hiç dinlenmeyerek", "Çok yiyerek", "Yavaş uçarak"]),
            ("Leylekler dinlenmek için nereye konar?", ["Tarlalara ve göl kıyılarına", "Dağ tepelerine", "Çöllere", "Şehirlere"]),
            ("Bahar gelince leylekler ne yapar?", ["Yuvalarına geri döner", "Afrika'da kalır", "Yeni yuva yapar", "Doğuya gider"]),
            ("Leyleklerin sayısı neden azalıyor?", ["Yaşam alanlarının yok olması", "Soğuk hava", "Yiyecek çoklu", "Göçün bitmesi"]),
        ]),
    listening=([
        ("Çocuk", "Baba, kuşlar neden kışın gidiyor?"),
        ("Baba", "Soğuk bastırınca yiyecek bulamıyorlar, o yüzden güneye uçuyorlar."),
        ("Çocuk", "Yolu nasıl buluyorlar?"),
        ("Baba", "Güneşe ve yıldızlara bakarak yönlerini buluyorlar."),
        ("Çocuk", "Bahar gelince geri dönecekler mi?"),
        ("Baba", "Evet, eski yuvalarını bulup yeniden yaşayacaklar."),
    ], [
        ("Qushlar nima uchun ketadi?", ["Sovuq tushib, ozuqa topolmagani uchun", "Qiziqish", "O'yin", "Odamlar haydagani"]),
        ("Ular yo'lni qanday topadi?", ["Quyosh va yulduzlarga qarab", "Xaritaga qarab", "Odamlarga ergashib", "Qo'shiq aytib"]),
    ]),
    practice=[
        ('c', "\"Qush uchib daraxtga qo'ndi.\"", ["Kuş uçup ağaca kondu.", "Kuş uçarak ağaca kondu mu.", "Kuş uçmadan ağaç.", "Kuş uçmak ağaca."]),
        ('c', "\"U ovozsiz yaqinlashdi.\"", ["Ses çıkarmadan yaklaştı.", "Ses çıkararak yaklaştı.", "Ses çıkarsa yaklaştı.", "Ses çıkaran yaklaştı."]),
        ('c', "\"Yomg'ir boshlangach hayvonlar qaytdi.\"", ["Yağmur başlayınca hayvanlar döndü.", "Yağmur başlamadan döndü.", "Yağmur başlıyor döndü.", "Yağmurda dönüyor."]),
        ('c', "\"Yirtqich\" turkchada:", ["yırtıcı", "otçul", "sürü", "yuva"]),
        ('o', "\"Qushlar qanot qoqib uchadi.\" gapini tuzing.", ["Kuşlar", "kanat", "çırparak", "uçar."]),
        ('o', "\"Bu tur himoya ostida.\" gapini tuzing.", ["Bu", "tür", "koruma", "altındadır."]),
    ],
    writing=("Sevimli hayvoningiz haqida 3 gap yozing (-(y)Ip va -(y)ArAk dan foydalaning).",
             "Kedim sabah uyanıp bahçeye çıkar. Sessizce yürüyerek kuşlara yaklaşır. Sonra yorulup güneşte uyur."),
    speaking=["Kuş uçup ağaca kondu.", "Kedi ses çıkarmadan yaklaştı.", "Yağmur başlayınca hayvanlar döndü.", "Bu tür koruma altındadır."],
    test=[
        ("-(y)Ip nimani bildiradi?", ["ketma-ket ishlarni bog'laydi", "shart", "buyruq", "inkor"]),
        ("-mAdAn nimani bildiradi?", ["...may (inkor holat)", "...gach", "...sa", "...gan sari"]),
        ("-(y)IncA nimani bildiradi?", ["...gach/...ganda", "...may", "...ib", "...sa"]),
        ("\"Yırtıcı\" nima?", ["yirtqich", "o'txo'r", "uy hayvoni", "qush"]),
        ("\"Otçul\" nima?", ["o'txo'r", "yirtqich", "hamma narsa yeguvchi", "baliqxo'r"]),
        ("\"Göç\" nima?", ["ko'chish", "uchish", "yugurish", "yashirinish"]),
        ("\"Barınak\" nima?", ["boshpana", "oziq", "suv", "ov"]),
        ("\"Pençe\" nima?", ["panja", "qanot", "dum", "tumshuq"]),
        ("\"Nesli tükenmek\" nima?", ["nasli qurimoq", "ko'paymoq", "ko'chmoq", "o'smoq"]),
        ("\"Sürü\" nima?", ["to'da, suruv", "uya", "qanot", "ov"]),
    ],
    bank=[
        ("\"Av\" nima?", ["ov, o'lja", "uya", "qanot", "to'da"]),
        ("\"Yuva\" nima?", ["uya, in", "qanot", "ov", "suruv"]),
        ("\"Kanat\" nima?", ["qanot", "panja", "dum", "tuk"]),
        ("\"Koruma altında\" nima?", ["himoya ostida", "ov ostida", "yo'qolgan", "ko'chib ketgan"]),
        ("Qaysi gap -(y)Ip bilan?", ["Kuş uçup kondu.", "Kuş uçarak kondu.", "Kuş uçmadan kondu.", "Kuş uçunca kondu."]),
        ("Qaysi gap -(y)ArAk bilan?", ["Kanat çırparak uçtu.", "Kanat çırpıp uçtu.", "Kanat çırpınca uçtu.", "Kanat çırpsa uçtu."]),
        ("\"Leylek\" qaysi hayvon?", ["laylak (qush)", "burgut", "bulbul", "qarg'a"]),
        ("Laylaklar qayerdan qayerga ko'chadi?", ["Yevropadan Afrikaga", "Afrikadan Osiyoga", "Amerikadan Yevropaga", "Osiyodan Avstraliyaga"]),
        ("\"Kurt\" nima?", ["bo'ri", "tulki", "ayiq", "sher"]),
        ("\"Aslan\" nima?", ["sher", "bo'ri", "yo'lbars", "ayiq"]),
        ("\"Kartal\" nima?", ["burgut", "laylak", "bulbul", "qarg'a"]),
        ("\"Tür\" nima?", ["tur, nav", "oila", "suruv", "uya"]),
    ],
)

B = topic(
    'u4b', "B. Bitkiler — O'simliklar", 81, 85,
    goals=[
        "Edilgen (-(I)l, -(I)n) va işteş (-Iş) nisbatlarni qo'llash",
        "O'simliklar, ularning o'sishi va foydasi haqidagi lug'atni bilish",
        "Jarayonni (o'sish, parvarish) tushuntiruvchi matn tuzish",
    ],
    blocks=[
        ("Edilgen çatı: -(I)l, -(I)n",
         "Majhul nisbat ishni bajaruvchi emas, ishning o'zi muhim bo'lganda ishlatiladi: Tohum toprağa ekilir. Su verilir. Fidan her gün sulanır. Ünlü bilan tugasa -n: okunur, yapılır, boyanır. Bajaruvchini ko'rsatish kerak bo'lsa \"tarafından\" ishlatiladi: Bahçıvan tarafından sulanır."),
        ("İşteş çatı: -Iş",
         "Ishtirokdosh nisbat birgalikda yoki o'zaro bajarilgan ishni bildiradi: Çocuklar fidanları birlikte dikiyor. Dallar rüzgârda sallaşıyor. Karşılaşmak, görüşmek, yarışmak kabi fe'llar o'zaro ma'no beradi."),
        ("Neden-sonuç: -DIğI için, -mAsI sayesinde",
         "Sababni bildirishda \"-DIğI için\" (...gani uchun) ishlatiladi: Yağmur yağdığı için bitkiler büyüdü. \"-mAsI sayesinde\" ijobiy sabab: Güneş ışığının olması sayesinde bitkiler fotosentez yapar."),
    ],
    facts=[
        "Edilgen: -(I)l (undosh bilan), -(I)n (unli bilan tugasa): ekilir, sulanır.",
        "İşteş: -Iş — birgalikda yoki o'zaro ish.",
        "Fotosintez: o'simliklar quyosh nuri bilan oziq hosil qiladi.",
        "Turkiyada eng ko'p yetishtiriladigan o'simliklardan: bug'doy, paxta, findiq, choy.",
    ],
    vocab=[
        ("bitki", "o'simlik", "Bitkiler oksijen üretir.", "O'simliklar kislorod chiqaradi."),
        ("tohum", "urug'", "Tohum toprağa ekilir.", "Urug' tuproqqa ekiladi."),
        ("fidan", "ko'chat", "Fidanlar her yıl dikilir.", "Ko'chatlar har yili o'tqaziladi."),
        ("kök", "ildiz", "Kökler toprağın altında uzar.", "Ildizlar tuproq ostida cho'ziladi."),
        ("yaprak", "barg", "Yapraklar sonbaharda dökülür.", "Barglar kuzda to'kiladi."),
        ("çiçek", "gul", "Çiçekler baharda açar.", "Gullar bahorda ochiladi."),
        ("meyve", "meva", "Meyveler yazın olgunlaşır.", "Mevalar yozda pishadi."),
        ("sulamak", "sug'ormoq", "Bahçe her akşam sulanır.", "Bog' har kuni kechqurun sug'oriladi."),
        ("fotosentez", "fotosintez", "Bitkiler fotosentezle beslenir.", "O'simliklar fotosintez bilan oziqlanadi."),
        ("toprak", "tuproq", "Verimli toprakta her şey yetişir.", "Unumdor tuproqda hamma narsa o'sadi."),
        ("filiz", "kurtak, nihol", "İlkbaharda filizler çıkar.", "Bahorda kurtaklar chiqadi."),
        ("ekin", "ekin", "Ekinler yağmur bekliyor.", "Ekinlar yomg'ir kutmoqda."),
    ],
    reading=("Bir tohumun yolculuğu",
        "Her bitki küçük bir tohumdan başlar. Tohum toprağa ekilir, su ve ısıyla uyandırılır. Birkaç gün sonra tohumdan küçük bir filiz çıkar. Kökler toprağın derinliklerine uzanırken yapraklar güneşe doğru büyür.\n\nBitkilerin büyümesi için güneş ışığı, su ve verimli toprak gerekir. Yapraklar güneş ışığını kullanarak besin üretir; bu olaya fotosentez denir. Fotosentez sayesinde havaya oksijen verilir ve insanlar nefes alabilir.\n\nBahçıvanlar fidanları dikmeden önce toprağı hazırlar. Fidanlar düzenli sulanır ve zararlılardan korunur. Birkaç ay sonra çiçekler açar, meyveler olgunlaşır. Bu emeğin karşılığı, sofraya gelen taze ürünlerdir.",
        [
            ("Tohum ne ile uyanır?", ["Su ve ısıyla", "Rüzgârla", "Işık olmadan", "Taşla"]),
            ("Kökler nereye uzanır?", ["Toprağın derinliklerine", "Gökyüzüne", "Yapraklara", "Çiçeğe"]),
            ("Fotosentez ne demektir?", ["Yaprakların güneş ışığıyla besin üretmesi", "Köklerin su emmesi", "Çiçeğin açması", "Meyvenin düşmesi"]),
            ("Fotosentez sayesinde havaya ne verilir?", ["Oksijen", "Karbon", "Azot", "Su"]),
            ("Bahçıvanlar fidanları dikmeden önce ne yapar?", ["Toprağı hazırlar", "Meyve toplar", "Su satar", "Hiçbir şey"]),
        ]),
    listening=([
        ("Nine", "Bu çiçekler her sabah sulanır, değil mi?"),
        ("Torun", "Evet nine, ben sularım. Ama bazıları solmuş."),
        ("Nine", "Güneş almadıkları için solmuşlar. Pencere önüne koyalım."),
        ("Torun", "Peki yaprakları temizlemek gerekir mi?"),
        ("Nine", "Evet, toz temizlenirse bitki daha iyi nefes alır."),
        ("Torun", "O zaman hepsini silelim."),
    ], [
        ("Gullar nima uchun so'lgan?", ["Quyosh olmagani uchun", "Suv ko'p bo'lgani uchun", "Sovuq", "Hasharot"]),
        ("Nima qilishni maslahat berdi?", ["Deraza oldiga qo'yishni", "Qorong'iga qo'yishni", "Tashlashni", "Kesishni"]),
    ]),
    practice=[
        ('c', "\"Urug' tuproqqa ekiladi.\"", ["Tohum toprağa ekilir.", "Tohum toprağı eker.", "Tohum toprakta eker.", "Tohum ekmez."]),
        ('c', "\"Yomg'ir yoqqani uchun o'simliklar o'sdi.\"", ["Yağmur yağdığı için bitkiler büyüdü.", "Yağmur yağsa bitkiler büyür.", "Yağmur yağmadan büyüdü.", "Yağmura büyüdü."]),
        ('c', "\"Barg\" turkchada:", ["yaprak", "kök", "tohum", "çiçek"]),
        ('c', "\"Sug'ormoq\" turkchada:", ["sulamak", "ekmek", "dikmek", "toplamak"]),
        ('o', "\"Ko'chatlar har kuni sug'oriladi.\" gapini tuzing.", ["Fidanlar", "her", "gün", "sulanır."]),
        ('o', "\"Bolalar ko'chatlarni birgalikda o'tqazyapti.\" gapini tuzing.", ["Çocuklar", "fidanları", "birlikte", "dikiyor."]),
    ],
    writing=("O'simlik parvarishi bo'yicha 3 ta majhul gap yozing.",
             "Fidan toprağa dikilir. Her gün sulanır. Zararlılardan korunur."),
    speaking=["Tohum toprağa ekilir.", "Fidanlar düzenli sulanır.", "Yapraklar güneşe doğru büyür.", "Bitkiler oksijen üretir."],
    test=[
        ("Majhul nisbat nimani ko'rsatadi?", ["ish muhim, bajaruvchi emas", "ish o'zaro", "ish buyruq", "ish inkor"]),
        ("\"Ekilir\" nima degani?", ["ekiladi", "ekdi", "ekadi", "eksa"]),
        ("-Iş qo'shimchasi qaysi nisbatni yasaydi?", ["ishtirokdosh (birgalikdagi)", "majhul", "orttirma", "o'zlik"]),
        ("\"-DIğI için\" nima degani?", ["...gani uchun", "...sa", "...gach", "...gan sari"]),
        ("\"Fotosentez\" nima?", ["o'simlikning nur bilan oziq hosil qilishi", "ildiz o'sishi", "gul ochilishi", "meva to'kilishi"]),
        ("\"Kök\" nima?", ["ildiz", "barg", "gul", "meva"]),
        ("\"Tohum\" nima?", ["urug'", "ko'chat", "barg", "ildiz"]),
        ("\"Fidan\" nima?", ["ko'chat", "urug'", "meva", "barg"]),
        ("\"Toprak\" nima?", ["tuproq", "suv", "havo", "tosh"]),
        ("\"Filiz\" nima?", ["kurtak, nihol", "ildiz", "meva", "poya"]),
    ],
    bank=[
        ("\"Meyve\" nima?", ["meva", "barg", "gul", "ildiz"]),
        ("\"Çiçek\" nima?", ["gul", "barg", "meva", "poya"]),
        ("\"Ekin\" nima?", ["ekin", "meva", "ildiz", "barg"]),
        ("\"Sulanır\" nima degani?", ["sug'oriladi", "sug'ordi", "sug'oradi", "sug'orsa"]),
        ("\"Dikilir\" nima degani?", ["o'tqaziladi", "o'tqazdi", "o'tqazadi", "o'tqazsa"]),
        ("\"Verimli toprak\" nima?", ["unumdor tuproq", "unumsiz tuproq", "quruq tuproq", "toshloq tuproq"]),
        ("\"Güneş ışığı sayesinde\" nima?", ["quyosh nuri tufayli", "quyosh nursiz", "quyosh bo'lsa", "quyosh uchun"]),
        ("\"Zararlı\" nima?", ["zararli (hasharot)", "foydali", "chiroyli", "katta"]),
        ("\"Oksijen\" nima?", ["kislorod", "azot", "vodorod", "karbonat"]),
        ("\"Sararmak\" nima?", ["sarg'aymoq", "yashil bo'lmoq", "qurimoq", "o'smoq"]),
        ("\"Solmak\" nima?", ["so'lmoq", "ochilmoq", "o'smoq", "pishmoq"]),
        ("\"Olgunlaşmak\" nima?", ["pishmoq", "so'lmoq", "ochilmoq", "to'kilmoq"]),
    ],
)

C = topic(
    'u4c', "C. Modern Hayat ve Canlılar Âlemi — Zamonaviy hayot va jonzotlar olami", 86, 92,
    goals=[
        "Sabab-natija bog'lovchilari (çünkü, bu yüzden, dolayısıyla, -mAsI nedeniyle) ni qo'llash",
        "Atrof-muhit muammolari va ekologiya lug'atini bilish",
        "Tabiatni muhofaza qilish haqida fikr bildirish",
    ],
    blocks=[
        ("Neden-sonuç bağlaçları",
         "Çünkü — sabab: Hava kirleniyor çünkü araç sayısı artıyor. Bu yüzden / bu nedenle / dolayısıyla — natija: Orman yangınları arttı; bu yüzden birçok hayvan yaşam alanını kaybetti. \"-mAsI nedeniyle / yüzünden\": Ormanların kesilmesi yüzünden türler azalıyor."),
        ("Şart ve sonuç: -DIğI takdirde, -sA ... -(y)AcAk",
         "Rasmiy shart: Önlem alınmadığı takdirde (chora ko'rilmasa) çok tür yok olacak. Oddiy shart: Su kirletilirse balıklar ölür. Bu uslub ogohlantirish va tavsiyalarda keng qo'llanadi."),
        ("Karşılık: rağmen, -sA da, -DIğI hâlde",
         "Ziddiyat: Uyarılara rağmen avcılık sürüyor (ogohlantirishlarga qaramay...). Hava soğuk olmasına rağmen hayvanlar dışarıda. -DIğI hâlde: Yasak olduğu hâlde ağaçlar kesiliyor."),
    ],
    facts=[
        "çünkü = sabab; bu yüzden / dolayısıyla = natija.",
        "-DIğI takdirde = ...gan taqdirda; ...mAsINA rağmen = ...ganiga qaramay.",
        "Iqlim o'zgarishi ko'p turlarning yo'qolishiga olib kelmoqda.",
        "Qayta ishlash va tejamkorlik tabiatni muhofaza qilishning asosiy yo'llari.",
    ],
    vocab=[
        ("çevre", "atrof-muhit", "Çevreyi korumak hepimizin görevidir.", "Atrof-muhitni muhofaza qilish barchamizning vazifamiz."),
        ("kirlilik", "ifloslanish", "Hava kirliliği sağlığı tehdit ediyor.", "Havoning ifloslanishi sog'liqqa xavf solmoqda."),
        ("iklim", "iqlim", "İklim değişikliği tüm dünyayı etkiliyor.", "Iqlim o'zgarishi butun dunyoga ta'sir qilmoqda."),
        ("atık", "chiqindi", "Atıkları ayrı toplamalıyız.", "Chiqindilarni alohida yig'ishimiz kerak."),
        ("geri dönüşüm", "qayta ishlash", "Kâğıt geri dönüşüme gönderilir.", "Qog'oz qayta ishlashga yuboriladi."),
        ("doğal yaşam", "yovvoyi tabiat", "Doğal yaşam alanları daralıyor.", "Yovvoyi tabiat hududlari torayib bormoqda."),
        ("orman", "o'rmon", "Ormanlar dünyanın akciğeridir.", "O'rmonlar dunyoning o'pkasi."),
        ("tür", "tur (biologik)", "Birçok türün nesli tükeniyor.", "Ko'p turlarning nasli qurimoqda."),
        ("tasarruf", "tejamkorlik", "Su tasarrufu yapmalıyız.", "Suvni tejashimiz kerak."),
        ("önlem", "chora", "Hükümet önlem aldı.", "Hukumat chora ko'rdi."),
        ("sürdürülebilir", "barqaror", "Sürdürülebilir yaşam önemlidir.", "Barqaror hayot muhim."),
        ("bilinç", "ong, ogohlik", "Çevre bilinci küçük yaşta kazanılır.", "Ekologik ong yoshlikdan shakllanadi."),
    ],
    reading=("Doğayı korumak zorundayız",
        "Modern hayat bize birçok kolaylık sağladı; ancak doğaya da zarar verdi. Fabrikalardan çıkan dumanlar havayı kirletiyor, çünkü birçok şehirde temiz enerji yetersiz. Bu yüzden solunum hastalıkları artıyor.\n\nOrmanların kesilmesi yüzünden hayvanlar yaşam alanlarını kaybediyor. Önlem alınmadığı takdirde birçok tür yok olabilir. Buna rağmen bazı ülkelerde ağaç kesimi hâlâ sürüyor.\n\nÇözüm, bilinçli yaşamaktan geçiyor. Atıkları ayrı toplayarak geri dönüşüme katkıda bulunabilir, su ve elektrik tasarrufu yapabiliriz. Çocuklara çevre bilinci küçük yaşta kazandırılırsa gelecek nesiller daha yaşanabilir bir dünyada yaşar.",
        [
            ("Hava neden kirleniyor?", ["Fabrika dumanları ve yetersiz temiz enerji yüzünden", "Yağmur yüzünden", "Rüzgâr yüzünden", "Deniz yüzünden"]),
            ("Ormanların kesilmesi sonucu ne olur?", ["Hayvanlar yaşam alanlarını kaybeder", "Yağmur artar", "Daha çok tür doğar", "Hava temizlenir"]),
            ("\"Önlem alınmadığı takdirde\" ne demektir?", ["Chora ko'rilmasa", "Chora ko'rilgani uchun", "Chora ko'rilib", "Chora ko'rmaslik uchun"]),
            ("Atıkları ayrı toplamak neye katkıda bulunur?", ["Geri dönüşüme", "Su kirliliğine", "Orman kesimine", "Hava kirliliğine"]),
            ("Çevre bilinci ne zaman kazandırılmalı?", ["Küçük yaşta", "Yetişkinlikte", "Yaşlılıkta", "Hiçbir zaman"]),
        ]),
    listening=([
        ("Öğretmen", "Bugün çevre kirliliğini konuşacağız. Kim sebeplerini söyleyebilir?"),
        ("Ali", "Fabrikalar ve araçlar çok duman çıkarıyor, bu yüzden hava kirleniyor."),
        ("Ayşe", "Ayrıca plastik atıklar çok, çünkü insanlar geri dönüşüm yapmıyor."),
        ("Öğretmen", "Çok doğru. Peki ne yapabiliriz?"),
        ("Ali", "Atıkları ayırabilir, su tasarrufu yapabiliriz."),
        ("Ayşe", "Önlem alınmadığı takdirde sorun büyüyecek."),
    ], [
        ("Havo nima uchun ifloslanyapti?", ["Zavod va mashinalar tutuni sababli", "Yomg'ir sababli", "Shamol", "Bulut"]),
        ("Ayşe nima uchun plastik chiqindi ko'p deydi?", ["Odamlar qayta ishlamagani uchun", "Plastik arzon", "Do'konlar ochiq", "Yo'q"]),
    ]),
    practice=[
        ('c', "\"Havo ifloslanyapti, chunki mashinalar ko'paydi.\"", ["Hava kirleniyor çünkü araçlar arttı.", "Hava kirleniyor bu yüzden araçlar arttı.", "Hava kirli çünkü az araç.", "Araçlar arttı bu yüzden çünkü."]),
        ('c', "\"Chora ko'rilmasa turlar yo'q bo'ladi.\"", ["Önlem alınmadığı takdirde türler yok olacak.", "Önlem alındı türler yok.", "Önlem alınmak için tür.", "Önlem almadan yoktur."]),
        ('c', "\"Ogohlantirishlarga qaramay\" turkchada:", ["uyarılara rağmen", "uyarılar için", "uyarıdan beri", "uyarıyla birlikte"]),
        ('c', "\"Qayta ishlash\" turkchada:", ["geri dönüşüm", "tasarruf", "önlem", "bilinç"]),
        ('o', "\"Suvni tejashimiz kerak.\" gapini tuzing.", ["Su", "tasarrufu", "yapmalıyız."]),
        ('o', "\"O'rmon kesilgani uchun hayvonlar yo'qolmoqda.\" gapini tuzing.", ["Ormanlar", "kesildiği", "için", "hayvanlar", "azalıyor."]),
    ],
    writing=("Atrof-muhitni muhofaza qilish uchun nima qila olishingiz haqida 3 gap yozing.",
             "Plastik poşet kullanmamaya çalışıyorum. Atıkları ayrı topluyorum. Bu sayede doğaya daha az zarar veriyorum."),
    speaking=["Çevreyi korumak görevimizdir.", "Hava kirleniyor çünkü araçlar arttı.", "Atıkları geri dönüşüme gönderelim.", "Su tasarrufu yapmalıyız."],
    test=[
        ("\"Çünkü\" nimani bildiradi?", ["sabab", "natija", "shart", "qarama-qarshilik"]),
        ("\"Bu yüzden\" nimani bildiradi?", ["natija", "sabab", "shart", "maqsad"]),
        ("\"-DIğI takdirde\" nima degani?", ["...gan taqdirda", "...gani uchun", "...gan sari", "...may"]),
        ("\"Rağmen\" nima degani?", ["...ga qaramay", "...uchun", "...bilan", "...dan beri"]),
        ("\"Çevre\" nima?", ["atrof-muhit", "o'rmon", "iqlim", "tur"]),
        ("\"Kirlilik\" nima?", ["ifloslanish", "tozalik", "iqlim", "chora"]),
        ("\"Geri dönüşüm\" nima?", ["qayta ishlash", "tejamkorlik", "iqlim", "chora"]),
        ("\"Tasarruf\" nima?", ["tejamkorlik", "isrof", "chiqindi", "ifloslanish"]),
        ("\"Sürdürülebilir\" nima?", ["barqaror", "vaqtinchalik", "qimmat", "kichik"]),
        ("\"Bilinç\" nima?", ["ong, ogohlik", "chora", "tur", "chiqindi"]),
    ],
    bank=[
        ("\"Atık\" nima?", ["chiqindi", "tur", "iqlim", "o'rmon"]),
        ("\"Orman\" nima?", ["o'rmon", "tog'", "dasht", "suv"]),
        ("\"İklim\" nima?", ["iqlim", "ob-havo", "fasl", "tabiat"]),
        ("\"Önlem\" nima?", ["chora", "ong", "chiqindi", "tur"]),
        ("\"Doğal yaşam\" nima?", ["yovvoyi tabiat", "shahar hayoti", "uy hayvonlari", "zavod"]),
        ("Qaysi bog'lovchi natijani bildiradi?", ["bu yüzden", "çünkü", "ancak", "eğer"]),
        ("Qaysi bog'lovchi sababni bildiradi?", ["çünkü", "bu yüzden", "dolayısıyla", "bu nedenle"]),
        ("\"Yasak olduğu hâlde\" nima?", ["taqiqlangan bo'lsa-da", "taqiqlangani uchun", "taqiqlangan sari", "taqiqlamasdan"]),
        ("\"Hava kirliliği\" nima?", ["havoning ifloslanishi", "suvning ifloslanishi", "tuproq ifloslanishi", "shovqin"]),
        ("\"Solunum\" nima?", ["nafas olish", "yurish", "uxlash", "yeyish"]),
        ("\"Yaşam alanı\" nima?", ["yashash muhiti", "uy", "ko'cha", "shahar"]),
        ("\"Dolayısıyla\" nima degani?", ["shunga ko'ra, natijada", "chunki", "agar", "balki"]),
    ],
)

TOPICS = [A, B, C]
