# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u5a', "A. Yazının Macerası — Yozuvning sarguzashti", 94, 99,
    goals=[
        "Tarixiy voqealarni hikoya qilishda -DI, -mIş va rivayet shakllarini farqlash",
        "Yozuv tarixi lug'atini (çivi yazısı, hiyeroglif, alfabe) bilish",
        "Turk yozuvlari (Orhun, Uygur, Arap, Lotin) haqida o'qish",
    ],
    blocks=[
        ("Tarihî anlatımda -DI ve -mIş",
         "Aniq guvoh bo'lingan yoki hujjatlashtirilgan voqea -DI bilan: 1928'de Latin alfabesi kabul edildi. Eshitilgan yoki taxminiy ma'lumot -mIş bilan: İlk yazıyı Sümerler bulmuş. Tarixiy matnlarda har ikki shakl ham uchraydi; -mIş farazni yoki yumshoq ishonchni bildiradi."),
        ("Ek fiil -(y)DI ve ilgi: -DIğI söylenir, -DIği düşünülür",
         "Ma'lumot manbasini bildiruvchi tuzilmalar: Yazının M.Ö. 3200 civarında bulunduğu söylenir. İlk alfabenin Fenikelilere ait olduğu düşünülür. Bu uslub ilmiy va tarixiy matnlarga xos."),
        ("-DIktAn sonra / -mAdAn önce",
         "Vaqt ketma-ketligi: Çivi yazısı bulunduktan sonra yazılı kayıtlar çoğaldı. Alfabe yayılmadan önce yazı çok zordu. -DIktAn sonra \"...gandan keyin\", -mAdAn önce \"...maslikdan oldin\"."),
    ],
    facts=[
        "Birinchi yozuv — Shumerlarning mixxat yozuvi (taxminan mil. avv. 3200).",
        "Eng qadimgi turk yozuvi — Orxon-Enasoy (O'rxun) bitiktoshlari (VIII asr).",
        "1928-yilda Turkiyada lotin alifbosi qabul qilindi.",
        "Yozuv ixtirosi tarixni tarixdan oldingi davrdan ajratadi.",
    ],
    vocab=[
        ("yazı", "yozuv", "Yazının icadı tarihte bir dönüm noktasıdır.", "Yozuvning ixtirosi tarixda burilish nuqtasi."),
        ("alfabe", "alifbo", "Alfabe harflerden oluşur.", "Alifbo harflardan tashkil topadi."),
        ("çivi yazısı", "mixxat yozuvi", "Sümerler çivi yazısını kullandı.", "Shumerlar mixxat yozuvidan foydalanishdi."),
        ("hiyeroglif", "ieroglif", "Mısırlılar hiyeroglif kullanırdı.", "Misrliklar ierogliflardan foydalanardi."),
        ("kitabe", "bitiktosh", "Orhun Kitabeleri ilk Türk yazılı belgeleridir.", "Orxon bitiktoshlari ilk turk yozma hujjatlari."),
        ("belge", "hujjat", "Eski belgeler müzede saklanır.", "Qadimgi hujjatlar muzeyda saqlanadi."),
        ("papirüs", "papirus", "Mısırlılar papirüse yazardı.", "Misrliklar papirusga yozardi."),
        ("tablet", "loydan lavha", "Sümerler kil tabletlere yazardı.", "Shumerlar loy lavhalarga yozardi."),
        ("harf", "harf", "Türk alfabesinde yirmi dokuz harf var.", "Turk alifbosida yigirma to'qqiz harf bor."),
        ("okuryazar", "savodli", "Bugün çoğu insan okuryazardır.", "Bugun ko'pchilik savodli."),
        ("tarih öncesi", "tarixdan oldingi davr", "Yazıdan önceki dönem tarih öncesidir.", "Yozuvdan oldingi davr tarixdan oldingi hisoblanadi."),
        ("bulmak", "topmoq, ixtiro qilmoq", "Yazıyı kimin bulduğu tam bilinmiyor.", "Yozuvni kim ixtiro qilgani aniq emas."),
    ],
    reading=("Yazının serüveni",
        "Yazıdan önce insanlar bilgileri konuşarak aktarırdı. Ancak sözlü anlatım zamanla değişebiliyor ve kayboluyordu. İnsanlar bilgiyi kalıcı hâle getirmek için resimlerle anlatmaya başladı. Zamanla bu resimler basit işaretlere dönüştü.\n\nBilinen ilk yazının, Mezopotamya'da yaşayan Sümerler tarafından M.Ö. 3200 civarında bulunduğu söylenir. Sümerler kil tabletlere çivi yazısıyla kayıt tutardı. Mısırlılar ise hiyeroglif kullanır ve papirüs üzerine yazardı.\n\nTürklerin bilinen en eski yazılı belgeleri sekizinci yüzyıldaki Orhun Kitabeleri'dir. Türkler zamanla Uygur, Arap ve Latin alfabelerini kullandı. 1928'de Latin alfabesine geçilince okuryazar oranı hızla arttı.",
        [
            ("İnsanlar kalıcı bilgi için ne yapmaya başladı?", ["Resimlerle anlatmaya", "Konuşmayı bırakmaya", "Şarkı söylemeye", "Taş yontmaya"]),
            ("İlk yazıyı kimler bulmuş?", ["Sümerler", "Mısırlılar", "Romalılar", "Türkler"]),
            ("Sümerler hangi yazıyı kullanırdı?", ["Çivi yazısı", "Hiyeroglif", "Latin alfabesi", "Arap alfabesi"]),
            ("Türklerin bilinen en eski belgeleri nelerdir?", ["Orhun Kitabeleri", "Divanü Lügati't-Türk", "Kutadgu Bilig", "Dede Korkut"]),
            ("1928'de ne oldu?", ["Latin alfabesine geçildi", "Orhun yazısı bulundu", "Uygur alfabesi kabul edildi", "Matbaa kuruldu"]),
        ]),
    listening=([
        ("Rehber", "Burada gördüğünüz kitabe sekizinci yüzyıldan kalmadır."),
        ("Turist", "Hangi alfabeyle yazılmış?"),
        ("Rehber", "Orhun yazısı denir. Türklerin ilk yazılı belgesi olduğu söylenir."),
        ("Turist", "Üzerinde ne yazıyor?"),
        ("Rehber", "Türk milletinin tarihi ve devlet adamlarının öğütleri."),
        ("Turist", "Çok etkileyici. Bir fotoğraf çekebilir miyim?"),
    ], [
        ("Bitiktosh qaysi asrdan?", ["VIII asrdan", "X asrdan", "XV asrdan", "III asrdan"]),
        ("Unda nima yozilgan?", ["Turk millati tarixi va davlat arboblari nasihatlari", "She'r", "Xarita", "Tijorat hujjati"]),
    ]),
    practice=[
        ('c', "\"Yozuvni shumerlar ixtiro qilgan ekan.\"", ["Yazıyı Sümerler bulmuş.", "Yazıyı Sümerler buldu.", "Yazıyı Sümerler bulacak.", "Yazıyı Sümerler bulur."]),
        ('c', "\"1928-yilda lotin alifbosi qabul qilindi.\"", ["1928'de Latin alfabesi kabul edildi.", "1928'de Latin alfabesi kabul edilmiş.", "1928'de Latin alfabesi kabul edecek.", "1928'de Latin kabul ediyor."]),
        ('c', "\"Mixxat yozuvi\" turkchada:", ["çivi yazısı", "hiyeroglif", "alfabe", "kitabe"]),
        ('c', "\"Bitiktosh\" turkchada:", ["kitabe", "tablet", "papirüs", "belge"]),
        ('o', "\"Yozuv topilgandan keyin yozma yozuvlar ko'paydi.\" gapini tuzing.", ["Yazı", "bulunduktan", "sonra", "kayıtlar", "çoğaldı."]),
        ('o', "\"Orxon bitiktoshlari VIII asrdan qolgan.\" gapini tuzing.", ["Orhun", "Kitabeleri", "sekizinci", "yüzyıldan", "kalmadır."]),
    ],
    writing=("Yozuvning inson hayotidagi ahamiyati haqida 3 gap yozing.",
             "Yazı sayesinde bilgiler nesilden nesile aktarıldı. Yazı bulunduktan sonra tarih yazılabildi. Bugün okuryazar olmak çok önemli."),
    speaking=["Yazıyı Sümerler bulmuş.", "Orhun Kitabeleri sekizinci yüzyıldandır.", "1928'de Latin alfabesi kabul edildi.", "Yazı insanlığın en büyük icadıdır."],
    test=[
        ("-DI va -mIş farqi nima?", ["-DI aniq o'tgan; -mIş eshitilgan/taxminiy", "-DI kelasi; -mIş hozirgi", "farqi yo'q", "-DI inkor"]),
        ("\"Sümerler yazıyı bulmuş.\" nimani bildiradi?", ["eshitilgan ma'lumot", "shaxsiy ko'rgan", "kelasi", "buyruq"]),
        ("\"Çivi yazısı\" nima?", ["mixxat yozuvi", "ieroglif", "alifbo", "bitiktosh"]),
        ("\"Hiyeroglif\" kimning yozuvi?", ["Misrliklar", "Shumerlar", "Turklar", "Rimliklar"]),
        ("\"Kitabe\" nima?", ["bitiktosh", "papirus", "lavha", "kitob"]),
        ("\"Belge\" nima?", ["hujjat", "kitob", "yozuv", "lavha"]),
        ("Orxon bitiktoshlari qaysi asrdan?", ["VIII asr", "I asr", "XV asr", "XX asr"]),
        ("\"-DIktAn sonra\" nima degani?", ["...gandan keyin", "...gandan oldin", "...gan sari", "...maguncha"]),
        ("\"Okuryazar\" nima?", ["savodli", "kutubxonachi", "yozuvchi", "o'quvchi"]),
        ("\"Tarih öncesi\" nima?", ["tarixdan oldingi davr", "o'rta asrlar", "yangi davr", "bugungi kun"]),
    ],
    bank=[
        ("\"Harf\" nima?", ["harf", "so'z", "gap", "alifbo"]),
        ("\"Alfabe\" nima?", ["alifbo", "harf", "yozuv", "belgi"]),
        ("\"Papirüs\" nima?", ["papirus", "loy lavha", "teri", "qog'oz"]),
        ("Shumerlar nimaga yozgan?", ["loy lavhalarga", "papirusga", "qog'ozga", "teriga"]),
        ("Misrliklar nimaga yozgan?", ["papirusga", "loyga", "qog'ozga", "yog'ochga"]),
        ("\"Bulunduğu söylenir\" nima?", ["topilgani aytiladi", "topildi", "topilmaydi", "topadi"]),
        ("\"Düşünülür\" nima?", ["o'ylanadi, taxmin qilinadi", "unutiladi", "bilinadi", "yoziladi"]),
        ("Turk alifbosida nechta harf bor?", ["29", "26", "32", "33"]),
        ("\"Yazı icadı\" nima?", ["yozuv ixtirosi", "yozuv xatosi", "yozuv qoidasi", "yozuv turi"]),
        ("\"Kalıcı\" nima?", ["doimiy", "vaqtincha", "yangi", "tez"]),
        ("\"Kayıt tutmak\" nima?", ["qayd yuritmoq", "yo'qotmoq", "yirtmoq", "o'qimoq"]),
        ("\"Aktarmak\" nima?", ["yetkazmoq, ko'chirmoq", "yashirmoq", "yirtmoq", "o'chirmoq"]),
    ],
)

B = topic(
    'u5b', "B. Medeniyetler — Sivilizatsiyalar", 100, 105,
    goals=[
        "Tarixiy va akademik matnda edilgen yapı (-(I)l, -(I)n) va -mAsIyle tuzilmasini ishlatish",
        "Qadimgi sivilizatsiyalar va ularning merosi lug'atini bilish",
        "Turk-islom sivilizatsiyasining jahon madaniyatiga ta'siri haqida o'qish",
    ],
    blocks=[
        ("Tarihte edilgen çatı",
         "Tarixiy matnlarda majhul nisbat ko'p qo'llanadi: Şehir M.Ö. 500'de kuruldu. Surlar yıkıldı. Kütüphane yakıldı. Bajaruvchi noma'lum yoki ahamiyatsiz bo'lganda shu shakl tanlanadi."),
        ("-mAsI ile sebep/sonuç: -mAsIyle, -mAsI sayesinde",
         "Ish natijasini bildiruvchi tuzilmalar: Ticaretin gelişmesiyle şehirler büyüdü. Yazının bulunması sayesinde bilgi saklanabildi. -mAsIyle \"...ishi bilan\" ma'nosida sabab-natija beradi."),
        ("Karşılaştırmalı anlatım: oysa, ancak, buna karşılık",
         "Qarama-qarshilik bog'lovchilari: Mısır nehir kıyısında kurulmuştu; oysa Mezopotamya iki nehir arasındaydı. Buna karşılık: Romalılar yol yaptı; buna karşılık Yunanlar felsefe geliştirdi."),
    ],
    facts=[
        "Qadimgi sivilizatsiyalar daryo vodiylarida paydo bo'lgan: Nil, Dajla-Frot, Hind, Xuanxe.",
        "Edilgen: kuruldu, yıkıldı — bajaruvchi muhim emas.",
        "Turklar Markaziy Osiyodan Anadolugacha ko'p madaniyatni birlashtirgan.",
        "Selchuklar va Usmoniylar me'morchilik va ilmga katta hissa qo'shgan.",
    ],
    vocab=[
        ("medeniyet", "sivilizatsiya", "Medeniyetler birbirini etkiler.", "Sivilizatsiyalar bir-biriga ta'sir qiladi."),
        ("uygarlık", "madaniyat, tamaddun", "Uygarlıklar nehir kıyısında doğdu.", "Tamaddunlar daryo bo'ylarida tug'ildi."),
        ("imparatorluk", "imperiya", "Roma İmparatorluğu çok büyüktü.", "Rim imperiyasi juda katta edi."),
        ("miras", "meros", "Eski medeniyetler bize miras bıraktı.", "Qadimgi sivilizatsiyalar bizga meros qoldirdi."),
        ("kazı", "qazish ishlari", "Arkeologlar kazıda tablet buldu.", "Arxeologlar qazishda lavha topdi."),
        ("anıt", "yodgorlik", "Bu anıt iki bin yıllık.", "Bu yodgorlik ikki ming yillik."),
        ("sur", "shahar devori", "Şehir surlarla çevriliydi.", "Shahar devor bilan o'ralgan edi."),
        ("ticaret", "savdo", "Ticaret şehirleri büyüttü.", "Savdo shaharlarni kattalashtirdi."),
        ("ilerleme", "taraqqiyot", "Bilimle ilerleme sağlandı.", "Ilm bilan taraqqiyot ta'minlandi."),
        ("yıkılmak", "qulamoq", "İmparatorluk yıkıldı.", "Imperiya quladi."),
        ("kurmak", "qurmoq, tashkil etmoq", "Osmanlı Devleti 1299'da kuruldu.", "Usmoniylar davlati 1299-yilda tashkil topdi."),
        ("yayılmak", "tarqalmoq", "Bu din hızla yayıldı.", "Bu din tez tarqaldi."),
    ],
    reading=("Medeniyetler nasıl doğar?",
        "Büyük medeniyetlerin çoğu nehir kıyılarında doğdu. Mısır Nil'in, Sümerler Dicle ve Fırat'ın, Çin Sarı Nehir'in kıyısında gelişti. Nehirlerin getirdiği bereketli toprak sayesinde tarım yapıldı, fazla ürün ticarete dönüştü ve şehirler kuruldu.\n\nYazının bulunmasıyla bilgiler kaydedildi, kanunlar yazıldı. Ticaretin gelişmesiyle de kültürler birbiriyle tanıştı. Roma yollar ve hukuk, Yunanistan felsefe ve sanat alanında önemli bir miras bıraktı.\n\nTürkler ise Orta Asya'dan Anadolu'ya uzanan geniş bir coğrafyada birçok medeniyetle karşılaştı. Selçuklular ve Osmanlılar mimari, bilim ve devlet yönetimi alanında kalıcı eserler bıraktı. Bugün bu miras müzelerde ve şehirlerde yaşatılıyor.",
        [
            ("Büyük medeniyetler çoğunlukla nerede doğdu?", ["Nehir kıyılarında", "Dağlarda", "Çöllerde", "Adalarda"]),
            ("Nehirler ne sağladı?", ["Bereketli toprak", "Altın", "Kömür", "Taş"]),
            ("Yazının bulunmasıyla ne yapıldı?", ["Bilgiler kaydedildi, kanunlar yazıldı", "Savaşlar bitti", "Şehirler yıkıldı", "Ticaret durdu"]),
            ("Roma ve Yunanistan'ın mirası nedir?", ["Yollar-hukuk ve felsefe-sanat", "Sadece savaş", "Sadece tarım", "Yazı"]),
            ("Türkler hangi coğrafyada medeniyetlerle karşılaştı?", ["Orta Asya'dan Anadolu'ya", "Afrika'da", "Amerika'da", "Avustralya'da"]),
        ]),
    listening=([
        ("Arkeolog", "Kazıda iki bin yıllık bir anıt bulundu."),
        ("Gazeteci", "Hangi medeniyete aitmiş?"),
        ("Arkeolog", "Roma dönemine ait olduğu düşünülüyor."),
        ("Gazeteci", "Şehir surları da bulundu mu?"),
        ("Arkeolog", "Evet, surların bir kısmı yıkılmış ama temeller sağlam."),
        ("Gazeteci", "Müzede sergilenecek mi?"),
    ], [
        ("Qazishda nima topildi?", ["Ikki ming yillik yodgorlik", "Pul", "Kitob", "Qurol"]),
        ("U qaysi davrga tegishli deb o'ylanadi?", ["Rim davriga", "Yunon davriga", "Turk davriga", "Misr davriga"]),
    ]),
    practice=[
        ('c', "\"Shahar mil. avv. 500-yilda qurildi.\"", ["Şehir M.Ö. 500'de kuruldu.", "Şehir M.Ö. 500'de kurdu.", "Şehir M.Ö. 500'de kurulacak.", "Şehir M.Ö. 500'de kurarım."]),
        ('c', "\"Savdoning rivojlanishi bilan shaharlar o'sdi.\"", ["Ticaretin gelişmesiyle şehirler büyüdü.", "Ticaret gelişirse şehir büyür.", "Ticaret gelişmeden büyüdü.", "Ticarete büyüdü."]),
        ('c', "\"Imperiya\" turkchada:", ["imparatorluk", "medeniyet", "anıt", "sur"]),
        ('c', "\"Meros\" turkchada:", ["miras", "kazı", "anıt", "ticaret"]),
        ('o', "\"Imperiya quladi.\" gapini tuzing.", ["İmparatorluk", "yıkıldı."]),
        ('o', "\"Bu din tez tarqaldi.\" gapini tuzing.", ["Bu", "din", "hızla", "yayıldı."]),
    ],
    writing=("Bilgan sivilizatsiya haqida 3 majhul gap yozing.",
             "Mısır medeniyeti Nil kıyısında kuruldu. Piramitler yapıldı. Hiyeroglif yazısı geliştirildi."),
    speaking=["Şehir surlarla çevrilmişti.", "Medeniyetler birbirini etkiler.", "İmparatorluk yıkıldı.", "Ticaretin gelişmesiyle şehirler büyüdü."],
    test=[
        ("Majhul nisbat nima uchun ishlatiladi?", ["bajaruvchi noma'lum yoki muhim emas", "buyruq uchun", "inkor uchun", "savol uchun"]),
        ("\"-mAsIyle\" nima ma'no beradi?", ["...ishi bilan (sabab-natija)", "...maslik", "...gan sari", "...ish uchun"]),
        ("\"Oysa\" nimani bildiradi?", ["qarama-qarshilik", "sabab", "natija", "shart"]),
        ("\"Medeniyet\" nima?", ["sivilizatsiya", "yodgorlik", "savdo", "qazish"]),
        ("\"Kazı\" nima?", ["qazish ishlari", "yodgorlik", "meros", "devor"]),
        ("\"Anıt\" nima?", ["yodgorlik", "devor", "savdo", "imperiya"]),
        ("\"Sur\" nima?", ["shahar devori", "yodgorlik", "yo'l", "ko'prik"]),
        ("\"Yıkılmak\" nima?", ["qulamoq", "qurilmoq", "o'smoq", "ochilmoq"]),
        ("\"Kurmak\" nima?", ["qurmoq", "buzmoq", "yoqmoq", "yo'qotmoq"]),
        ("\"Ilerleme\" nima?", ["taraqqiyot", "orqaga ketish", "to'xtash", "tinchlik"]),
    ],
    bank=[
        ("\"Uygarlık\" nima?", ["tamaddun", "savdo", "meros", "yodgorlik"]),
        ("\"Ticaret\" nima?", ["savdo", "qazish", "meros", "ilm"]),
        ("\"Yayılmak\" nima?", ["tarqalmoq", "yig'ilmoq", "qulamoq", "yo'qolmoq"]),
        ("Misr sivilizatsiyasi qaysi daryo bo'yida?", ["Nil", "Dajla", "Frot", "Hind"]),
        ("Shumerlar qaysi daryolar bo'yida?", ["Dajla va Frot", "Nil", "Xuanxe", "Amudaryo"]),
        ("Xitoy sivilizatsiyasi qaysi daryo bo'yida?", ["Sariq daryo (Xuanxe)", "Nil", "Hind", "Dunay"]),
        ("\"Buna karşılık\" nima?", ["unga qaramay, aksincha", "shu sababli", "agar", "balki"]),
        ("\"Kütüphane yakıldı.\" nima?", ["Kutubxona yondirildi.", "Kutubxona yoqdi.", "Kutubxona yonadi.", "Kutubxona yonsa."]),
        ("Selchuklar nimaga hissa qo'shgan?", ["me'morchilik, ilm, davlat boshqaruvi", "faqat dengiz", "faqat dehqonchilik", "faqat savdo"]),
        ("\"Tablet\" nima?", ["loy lavha", "qog'oz", "gazeta", "kitob"]),
        ("\"Eserler\" nima?", ["asarlar", "devorlar", "yo'llar", "qurollar"]),
        ("\"Yaşatmak\" nima?", ["yashatmoq, saqlab qolmoq", "o'ldirmoq", "buzmoq", "unutmoq"]),
    ],
)

C = topic(
    'u5c', "C. Kilometre Taşlarımız — Burilish nuqtalarimiz", 106, 112,
    goals=[
        "Shart shakllari (-sA, -DIğI takdirde, -(y)AcAk olsa) ni tarixiy kontekstda qo'llash",
        "Turk tarixidagi muhim burilish nuqtalarini sanash",
        "Tarixiy voqeani sabab-natija bilan tushuntirish",
    ],
    blocks=[
        ("Gerçek ve gerçek dışı şart",
         "Reallik: Yağmur yağarsa ekin biter. Realdan tashqari (hozirgi): Para olsa ev alırdım. O'tmishdagi shart: Zamanında gitseydi başarırdı (vaqtida borganida uddalagan bo'lardi). Tarixiy muhokamada \"agar shunday bo'lmaganida\" ma'nosi uchun: Malazgirt kazanılmasaydı Anadolu açılamazdı."),
        ("-DIğI takdirde, -mAdIğI sürece",
         "Rasmiy shart: Anlaşmaya uyulduğu takdirde barış sağlanır. -mAdIğI sürece \"...maguncha\" ma'nosida: Yeni bir devlet kurulmadığı sürece düzen sağlanamaz."),
        ("Dönüm noktası: -DIğI tarih, -DIğI yıl",
         "Sanani aniqlash: Malazgirt Savaşı 1071'de yapıldı. Osmanlı Devleti 1299'da kuruldu. İstanbul 1453'te fethedildi. Cumhuriyet 29 Ekim 1923'te ilan edildi. -DIğI yıl/tarih \"...gan yili/sanasi\"."),
    ],
    facts=[
        "1071 — Malazgirt jangi, Anadoluning turklar uchun ochilishi.",
        "1299 — Usmoniylar davlatining tashkil topishi; 1453 — Istanbulning fath etilishi.",
        "29 oktyabr 1923 — Turkiya Respublikasi e'lon qilindi.",
        "Shart: -sA (haqiqiy), -sAydI (o'tmishdagi realdan tashqari).",
    ],
    vocab=[
        ("dönüm noktası", "burilish nuqtasi", "1453 bir dönüm noktasıdır.", "1453-yil burilish nuqtasi."),
        ("zafer", "g'alaba", "Büyük zafer kazanıldı.", "Katta g'alaba qozonildi."),
        ("fetih", "fath", "İstanbul'un fethi büyük bir olaydı.", "Istanbulning fathi katta voqea edi."),
        ("cumhuriyet", "respublika", "Cumhuriyet 1923'te ilan edildi.", "Respublika 1923-yilda e'lon qilindi."),
        ("devlet", "davlat", "Yeni bir devlet kuruldu.", "Yangi davlat tashkil topdi."),
        ("savaş", "urush", "Savaşta çok kayıp verildi.", "Urushda ko'p talofot ko'rildi."),
        ("barış", "tinchlik", "Barış anlaşması imzalandı.", "Tinchlik shartnomasi imzolandi."),
        ("bağımsızlık", "mustaqillik", "Bağımsızlık her şeyden değerlidir.", "Mustaqillik hamma narsadan qimmatli."),
        ("lider", "yetakchi", "Lider halkı birleştirdi.", "Yetakchi xalqni birlashtirdi."),
        ("anlaşma", "kelishuv, shartnoma", "Anlaşma imzalandı.", "Shartnoma imzolandi."),
        ("ilan etmek", "e'lon qilmoq", "Bağımsızlık ilan edildi.", "Mustaqillik e'lon qilindi."),
        ("sınır", "chegara", "Sınırlar yeniden çizildi.", "Chegaralar qayta chizildi."),
    ],
    reading=("Tarihin dönüm noktaları",
        "Her milletin tarihinde yönünü değiştiren olaylar vardır. Türkler için 1071'deki Malazgirt Zaferi böyle bir dönüm noktasıdır. Bu zaferden sonra Türkler Anadolu'ya yerleşmeye başladı ve yeni beylikler kuruldu. Zafer kazanılmasaydı Anadolu'nun tarihi çok farklı olurdu.\n\n1453'te Fatih Sultan Mehmet İstanbul'u fethetti. Bu olay, Orta Çağ'ın kapanıp Yeni Çağ'ın başladığı tarih olarak kabul edilir. Fetihle birlikte şehir, imparatorluğun başkenti oldu ve kültürlerin buluşma noktasına dönüştü.\n\n29 Ekim 1923'te Mustafa Kemal Atatürk önderliğinde Cumhuriyet ilan edildi. Bağımsızlık savaşı kazanıldığı için yeni bir devlet kurulabildi. Bu üç olay, Türk tarihinin en önemli kilometre taşlarıdır.",
        [
            ("Malazgirt Zaferi hangi yıldır?", ["1071", "1299", "1453", "1923"]),
            ("Malazgirt'ten sonra ne oldu?", ["Türkler Anadolu'ya yerleşmeye başladı", "Savaş bitti", "İstanbul fethedildi", "Cumhuriyet kuruldu"]),
            ("İstanbul'un fethi hangi çağların sınırı kabul edilir?", ["Orta Çağ ve Yeni Çağ", "Tunç ve Demir", "Yeni ve Yakın", "Taş ve Bakır"]),
            ("Cumhuriyet ne zaman ilan edildi?", ["29 Ekim 1923", "19 Mayıs 1919", "23 Nisan 1920", "30 Ağustos 1922"]),
            ("Yeni devlet neden kurulabildi?", ["Bağımsızlık savaşı kazanıldığı için", "Çok para bulunduğu için", "Dostlar yardım ettiği için", "Seçim yapıldığı için"]),
        ]),
    listening=([
        ("Tarih hocası", "Malazgirt kazanılmasaydı sizce ne olurdu?"),
        ("Öğrenci", "Türkler Anadolu'ya bu kadar rahat giremezdi."),
        ("Hoca", "Doğru. Peki İstanbul'un fethi neden önemli?"),
        ("Öğrenci", "Çünkü Orta Çağ'ı bitirdi ve yeni bir dönem başlattı."),
        ("Hoca", "Çok güzel. Cumhuriyet için de bir şey söyleyebilir misin?"),
        ("Öğrenci", "29 Ekim 1923'te ilan edildi ve modern bir devlet kuruldu."),
    ], [
        ("Malazgirt yutilmaganida nima bo'lardi?", ["Turklar Anadoluga bunchalik oson kira olmasdi", "Hech narsa o'zgarmasdi", "Urush davom etardi", "Respublika erta bo'lardi"]),
        ("Istanbulning fathi nimani boshlab berdi?", ["Yangi davrni", "Respublikani", "Urushni", "Tinchlikni"]),
    ]),
    practice=[
        ('c', "\"Agar vaqtida borganida uddalagan bo'lardi.\"", ["Zamanında gitseydi başarırdı.", "Zamanında gitti başarır.", "Zamanında gidecek.", "Zamanında gitmiş."]),
        ('c', "\"Shartnomaga amal qilingan taqdirda tinchlik ta'minlanadi.\"", ["Anlaşmaya uyulduğu takdirde barış sağlanır.", "Anlaşmaya uyuldu barış.", "Anlaşma uyduğu için.", "Anlaşmaya uymak için."]),
        ('c', "\"Respublika\" turkchada:", ["cumhuriyet", "devlet", "fetih", "savaş"]),
        ('c', "\"Burilish nuqtasi\" turkchada:", ["dönüm noktası", "sınır", "anlaşma", "lider"]),
        ('o', "\"Respublika 1923-yilda e'lon qilindi.\" gapini tuzing.", ["Cumhuriyet", "1923'te", "ilan", "edildi."]),
        ('o', "\"Istanbul 1453-yilda fath etildi.\" gapini tuzing.", ["İstanbul", "1453'te", "fethedildi."]),
    ],
    writing=("Vatan tarixingizdagi bir burilish nuqtasi haqida 3 gap yozing.",
             "1991'de ülkemiz bağımsızlığını ilan etti. Bu olay tarihimizin dönüm noktasıdır. Bağımsızlık sayesinde yeni bir dönem başladı."),
    speaking=["Malazgirt 1071'de kazanıldı.", "İstanbul 1453'te fethedildi.", "Cumhuriyet 1923'te ilan edildi.", "Bağımsızlık her şeyden değerlidir."],
    test=[
        ("-sAydI qo'shimchasi nimani bildiradi?", ["o'tmishdagi realdan tashqari shart", "kelasi zamon", "buyruq", "inkor"]),
        ("\"Gitseydi başarırdı.\" nima degani?", ["Agar borganida uddalagan bo'lardi", "Bordi va uddaladi", "Boradi va uddalaydi", "Bormadi"]),
        ("\"-DIğI takdirde\" nima degani?", ["...gan taqdirda", "...gani uchun", "...ganda", "...maguncha"]),
        ("\"-mAdIğI sürece\" nima degani?", ["...maguncha", "...gan sari", "...gach", "...ish uchun"]),
        ("Malazgirt jangi qaysi yil?", ["1071", "1299", "1453", "1923"]),
        ("Usmoniylar davlati qaysi yili tashkil topgan?", ["1299", "1071", "1453", "1923"]),
        ("Istanbul qachon fath etilgan?", ["1453", "1071", "1299", "1923"]),
        ("Respublika qachon e'lon qilingan?", ["29 oktyabr 1923", "19 may 1919", "23 aprel 1920", "30 avgust 1922"]),
        ("\"Fetih\" nima?", ["fath", "tinchlik", "shartnoma", "mustaqillik"]),
        ("\"Bağımsızlık\" nima?", ["mustaqillik", "tinchlik", "g'alaba", "chegara"]),
    ],
    bank=[
        ("\"Barış\" nima?", ["tinchlik", "urush", "g'alaba", "chegara"]),
        ("\"Savaş\" nima?", ["urush", "tinchlik", "shartnoma", "g'alaba"]),
        ("\"Sınır\" nima?", ["chegara", "yo'l", "shahar", "daryo"]),
        ("\"Anlaşma\" nima?", ["kelishuv, shartnoma", "urush", "g'alaba", "tinchlik"]),
        ("\"Ilan etmek\" nima?", ["e'lon qilmoq", "yashirmoq", "buzmoq", "yo'q qilmoq"]),
        ("\"Lider\" nima?", ["yetakchi", "askar", "elchi", "muallim"]),
        ("\"Devlet\" nima?", ["davlat", "shahar", "xalq", "chegara"]),
        ("\"Kazanılmasaydı\" nima?", ["yutilmaganida", "yutilgan", "yutilmaydi", "yutilsa"]),
        ("\"Yeni Çağ\" qachon boshlangan (an'anaviy)?", ["1453 atrofida", "1071", "1923", "500"]),
        ("\"Orta Çağ\" nima?", ["o'rta asrlar", "yangi davr", "qadimgi davr", "yaqin davr"]),
        ("Mustafa Kemal Atatürk kim?", ["Turkiya Respublikasi asoschisi", "Usmoniy sultoni", "Selchuk beyi", "Bizans imperatori"]),
        ("\"Zafer\" nima?", ["g'alaba", "mag'lubiyat", "fath", "tinchlik"]),
    ],
)

TOPICS = [A, B, C]
