# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u6a', "A. Sempozyuma Hazırlık — Simpoziumga tayyorgarlik", 114, 117,
    goals=[
        "Rasmiy murojaat va iltimos shakllarini (-mAnIzI rica ederiz, -rsAnIz) qo'llash",
        "Konferensiya va ilmiy tadbir lug'atini bilish",
        "Taklifnoma va ro'yxatdan o'tish matnini tushunish",
    ],
    blocks=[
        ("Resmî rica: -mAnIzI rica ederiz, -rsAnIz memnun oluruz",
         "Rasmiy iltimos: Başvuru formunu doldurmanızı rica ederiz. (Ariza shaklini to'ldirishingizni so'raymiz.) Özetinizi cuma gününe kadar göndermeniz gerekmektedir. Muloyim shart: Katılırsanız memnun oluruz. Katılabilirseniz çok seviniriz."),
        ("Davet ve bilgilendirme: -mAktAdIr, -(y)AcAktIr",
         "Rasmiy axborot: Sempozyum 12-14 Mayıs tarihlerinde düzenlenecektir. Kayıtlar 1 Nisan'da başlamaktadır. -(y)AcAktIr kelajak rasmiy zamonini, -mAktAdIr hozirgi davomli rasmiy zamonni bildiradi."),
        ("Zorunluluk bildirme: -mAsI gerekmektedir, -mAsI zorunludur",
         "Majburiyat: Bildiri özetinin en fazla 300 kelime olması gerekmektedir. Katılımcıların kimlik göstermesi zorunludur. Bu shakllar rasmiy hujjatlarda ko'p uchraydi."),
    ],
    facts=[
        "Rasmiy iltimos: -mAnIzI rica ederiz.",
        "Rasmiy kelajak: -(y)AcAktIr; rasmiy hozirgi: -mAktAdIr.",
        "Simpozium — ma'lum mavzuda mutaxassislar yig'ilishi; bildiri — ma'ruza.",
        "Xulosa (özet) odatda 200-300 so'zdan oshmaydi.",
    ],
    vocab=[
        ("sempozyum", "simpozium", "Sempozyum üniversitede yapılacak.", "Simpozium universitetda o'tkaziladi."),
        ("bildiri", "ilmiy ma'ruza", "Bildiri özetini gönderdim.", "Ma'ruza xulosasini yubordim."),
        ("özet", "xulosa (qisqacha)", "Özet iki yüz kelimeyi geçmemeli.", "Xulosa ikki yuz so'zdan oshmasligi kerak."),
        ("katılımcı", "ishtirokchi", "Katılımcılar salona yerleşti.", "Ishtirokchilar zalga joylashdi."),
        ("kayıt", "ro'yxatga olish", "Kayıt işlemleri sabah başlıyor.", "Ro'yxatga olish ishlari ertalab boshlanadi."),
        ("davet", "taklif", "Davetinizi memnuniyetle kabul ederim.", "Taklifingizni mamnuniyat bilan qabul qilaman."),
        ("konu", "mavzu", "Konu başlığını belirleyelim.", "Mavzu sarlavhasini belgilaylik."),
        ("oturum", "sessiya", "Birinci oturum saat onda.", "Birinchi sessiya soat o'nda."),
        ("düzenlemek", "tashkil qilmoq", "Etkinliği üniversite düzenliyor.", "Tadbirni universitet tashkil qilmoqda."),
        ("program", "dastur", "Programı e-postayla gönderdik.", "Dasturni elektron pochta orqali yubordik."),
        ("rica etmek", "iltimos qilmoq", "Sizden bir şey rica ediyorum.", "Sizdan bir narsa iltimos qilaman."),
        ("son tarih", "oxirgi muddat", "Başvuru için son tarih 1 Mayıs.", "Ariza uchun oxirgi muddat 1 may."),
    ],
    reading=("Davet mektubu",
        "Sayın Katılımcılar,\n\n\"Bilimin Gözüyle\" başlıklı uluslararası sempozyumumuz 12-14 Mayıs tarihlerinde Ankara'da düzenlenecektir. Sempozyuma katılmak isteyen araştırmacıların özetlerini en geç 1 Nisan'a kadar göndermeleri rica olunur. Özetlerin en fazla üç yüz kelimeden oluşması gerekmektedir.\n\nKabul edilen bildiriler bilimsel kurul tarafından belirlenecek ve 20 Nisan'da duyurulacaktır. Kayıtlar çevrim içi yapılmaktadır. Katılımınızdan memnuniyet duyarız.\n\nSaygılarımızla,\nDüzenleme Kurulu",
        [
            ("Sempozyum nerede düzenlenecek?", ["Ankara'da", "İstanbul'da", "İzmir'de", "Bursa'da"]),
            ("Özetler ne zamana kadar gönderilmeli?", ["1 Nisan'a kadar", "20 Nisan'a kadar", "12 Mayıs'a kadar", "1 Mayıs'a kadar"]),
            ("Özetlerin en fazla kaç kelime olmalı?", ["Üç yüz", "İki yüz", "Beş yüz", "Yüz"]),
            ("Kabul edilen bildiriler ne zaman duyurulacak?", ["20 Nisan'da", "1 Nisan'da", "12 Mayıs'ta", "14 Mayıs'ta"]),
            ("Kayıtlar nasıl yapılıyor?", ["Çevrim içi", "Posta ile", "Telefonla", "Yüz yüze"]),
        ]),
    listening=([
        ("Sekreter", "Sempozyum için kaydınızı yaptırdınız mı?"),
        ("Dr. Aslı", "Henüz değil. Özetimi göndermem gerekiyor."),
        ("Sekreter", "Son tarih cuma günü. Formu doldurmanızı rica ederim."),
        ("Dr. Aslı", "Tamam, hemen göndereceğim. Konaklama da ayarlanacak mı?"),
        ("Sekreter", "Evet, otel bilgilerini e-postayla ileteceğiz."),
        ("Dr. Aslı", "Teşekkür ederim."),
    ], [
        ("Dr. Aslı nimani yuborishi kerak?", ["Xulosasini", "Pasportini", "Pulini", "Kitobini"]),
        ("Mehmonxona haqida qanday xabar beriladi?", ["Elektron pochta orqali", "Telefon", "Xat", "Og'zaki"]),
    ]),
    practice=[
        ('c', "\"Arizani to'ldirishingizni so'raymiz.\"", ["Formu doldurmanızı rica ederiz.", "Formu doldurdum.", "Formu dolduracak.", "Formu doldursa."]),
        ('c', "\"Simpozium 12-14 may kunlari tashkil etiladi.\"", ["Sempozyum 12-14 Mayıs'ta düzenlenecektir.", "Sempozyum 12-14 Mayıs'ta düzenledi.", "Sempozyum 12-14 Mayıs düzenliyor.", "Sempozyum düzenlenmiş."]),
        ('c', "\"Ishtirokchi\" turkchada:", ["katılımcı", "oturum", "davet", "özet"]),
        ('c', "\"Ro'yxatga olish\" turkchada:", ["kayıt", "program", "konu", "bildiri"]),
        ('o', "\"Ishtirokchilarning shaxsni tasdiqlashi shart.\" gapini tuzing.", ["Katılımcıların", "kimlik", "göstermesi", "zorunludur."]),
        ('o', "\"Xulosa uch yuz so'zdan oshmasligi kerak.\" gapini tuzing.", ["Özetin", "üç yüz", "kelimeyi", "geçmemesi", "gerekir."]),
    ],
    writing=("Simpoziumga qatnashish uchun qisqa rasmiy ariza (3 gap) yozing.",
             "Sayın Düzenleme Kurulu, Sempozyuma katılmak istiyorum. Özetimi ekte gönderiyorum. Katılımımın onaylanmasını rica ederim."),
    speaking=["Formu doldurmanızı rica ederiz.", "Sempozyum Mayıs'ta düzenlenecektir.", "Son tarih cuma günüdür.", "Katılımınızdan memnuniyet duyarız."],
    test=[
        ("\"Rica ederiz\" nima degani?", ["iltimos qilamiz", "rad etamiz", "qabul qilamiz", "buyuramiz"]),
        ("\"-(y)AcAktIr\" qaysi zamon?", ["rasmiy kelasi zamon", "o'tgan", "hozirgi", "shart"]),
        ("\"-mAktAdIr\" qaysi zamon?", ["rasmiy hozirgi (davomli)", "kelasi", "o'tgan", "buyruq"]),
        ("\"Sempozyum\" nima?", ["simpozium", "dastur", "ro'yxat", "sessiya"]),
        ("\"Bildiri\" nima?", ["ilmiy ma'ruza", "taklif", "ro'yxat", "mavzu"]),
        ("\"Özet\" nima?", ["qisqacha xulosa", "uzun matn", "sarlavha", "ro'yxat"]),
        ("\"Oturum\" nima?", ["sessiya", "dastur", "taklif", "ro'yxat"]),
        ("\"Kayıt\" nima?", ["ro'yxatga olish", "dastur", "taklif", "mavzu"]),
        ("\"Zorunludur\" nima degani?", ["majburiy", "ixtiyoriy", "mumkin", "taqiqlangan"]),
        ("\"Son tarih\" nima?", ["oxirgi muddat", "birinchi kun", "dam olish", "bayram"]),
    ],
    bank=[
        ("\"Davet\" nima?", ["taklif", "ro'yxat", "xulosa", "mavzu"]),
        ("\"Düzenlemek\" nima?", ["tashkil qilmoq", "buzmoq", "tark etmoq", "yopmoq"]),
        ("\"Konu\" nima?", ["mavzu", "dastur", "xulosa", "taklif"]),
        ("\"Program\" nima?", ["dastur", "ro'yxat", "mavzu", "taklif"]),
        ("\"Rica etmek\" nima?", ["iltimos qilmoq", "buyurmoq", "rad etmoq", "kutmoq"]),
        ("\"Memnuniyet duyarız.\" nima?", ["Mamnun bo'lamiz.", "Xafa bo'lamiz.", "Rad etamiz.", "Kutamiz."]),
        ("\"Saygılarımızla\" nima?", ["hurmat bilan", "salom", "xayr", "rahmat"]),
        ("\"Sayın\" nima?", ["hurmatli", "aziz", "yaxshi", "eski"]),
        ("\"Katılmak\" nima?", ["qatnashmoq", "ketmoq", "kutmoq", "yozmoq"]),
        ("\"Konaklama\" nima?", ["turar joy, yashash", "ovqat", "yo'l", "dastur"]),
        ("\"Onaylanmak\" nima?", ["tasdiqlanmoq", "rad etilmoq", "yozilmoq", "yopilmoq"]),
        ("\"Çevrim içi\" nima?", ["onlayn", "oflayn", "qog'ozda", "og'zaki"]),
    ],
)

B = topic(
    'u6b', "B. Sempozyum Günleri — Simpozium kunlari", 118, 122,
    goals=[
        "Ilmiy nutqda -DIğI görülmektedir, -mAktAdIr, -(y)AcAğI tahmin edilmektedir tuzilmalarini qo'llash",
        "Taqdimot va munozara paytida ishlatiladigan iboralarni bilish",
        "Savol berish va javob qaytarish madaniyatini o'zlashtirish",
    ],
    blocks=[
        ("Bilimsel dil: -DIğI görülmektedir, -mAktAdIr",
         "Ilmiy uslubda tadqiqot xulosalari betaraf tarzda ifodalanadi: Araştırmada gençlerin çoğunun internet kullandığı görülmektedir. Veriler, artışın devam ettiğini göstermektedir. Bu shakl muallif fikrini emas, natijani bildiradi."),
        ("Soru sorma ve görüş bildirme",
         "Munozarada: Bir sorum olacaktı. (Bir savolim bor edi.) Katılmıyorum çünkü... Bence... Bu konuda şunu eklemek isterim. Söz alabilir miyim? (So'z olsam bo'ladimi?) Bunu biraz açabilir misiniz? (Buni biroz ochib bera olasizmi?)"),
        ("Bağlaçlar: ayrıca, ancak, dolayısıyla, öte yandan",
         "Ilmiy matnni bog'lash: Ayrıca (bundan tashqari), ancak (biroq), dolayısıyla (shuning uchun), öte yandan (boshqa tomondan). Bu vositalar fikrni izchil qiladi."),
    ],
    facts=[
        "Ilmiy uslub: -DIğI görülmektedir / göstermektedir.",
        "Munozara: Söz alabilir miyim? Katılıyorum/Katılmıyorum.",
        "Bog'lovchilar: ayrıca, ancak, dolayısıyla, öte yandan.",
        "Simpoziumda odatda ma'ruza, savol-javob va xulosa sessiyasi bo'ladi.",
    ],
    vocab=[
        ("araştırma", "tadqiqot", "Araştırma üç yıl sürdü.", "Tadqiqot uch yil davom etdi."),
        ("veri", "ma'lumot, statistika", "Veriler yeni bir sonuç gösteriyor.", "Ma'lumotlar yangi natijani ko'rsatmoqda."),
        ("sonuç", "natija", "Sonuçlar ilginçti.", "Natijalar qiziq edi."),
        ("yöntem", "usul, metod", "Araştırmada anket yöntemi kullanıldı.", "Tadqiqotda so'rovnoma usuli qo'llandi."),
        ("varsayım", "faraz", "Varsayım doğrulandı.", "Faraz tasdiqlandi."),
        ("görüş", "fikr, nuqtai nazar", "Görüşlerinizi paylaşabilirsiniz.", "Fikrlaringizni ulashishingiz mumkin."),
        ("tartışma", "munozara", "Tartışma çok verimliydi.", "Munozara juda samarali edi."),
        ("sunum", "taqdimot", "Sunum yirmi dakika sürdü.", "Taqdimot yigirma daqiqa davom etdi."),
        ("moderatör", "boshqaruvchi", "Moderatör söz hakkı verdi.", "Boshqaruvchi so'z huquqini berdi."),
        ("katkı", "hissa", "Bu çalışma alana büyük katkı sağladı.", "Bu ish sohaga katta hissa qo'shdi."),
        ("eleştiri", "tanqid", "Eleştiriler yapıcıydı.", "Tanqidlar konstruktiv edi."),
        ("çözümlemek", "tahlil qilmoq", "Veriler çözümlendi.", "Ma'lumotlar tahlil qilindi."),
    ],
    reading=("Sempozyumun ikinci günü",
        "Sempozyumun ikinci gününde ilk oturum \"Gençlerin Dijital Alışkanlıkları\" konusuyla başladı. Konuşmacı, yaptığı araştırmanın sonuçlarını sundu. Veriler, gençlerin günde ortalama beş saat internette vakit geçirdiğini göstermektedir. Ayrıca araştırmada, çevrim içi öğrenmenin geleneksel yöntemlerden daha çok tercih edildiği görülmektedir.\n\nSunumun ardından tartışma bölümüne geçildi. Salondan bir katılımcı söz alıp \"Örneklem yeterince büyük mü?\" diye sordu. Konuşmacı, bin iki yüz kişiyle çalıştıklarını belirterek soruyu yanıtladı. Başka bir katılımcı ise sonuçların farklı yaş gruplarında değişebileceğini ekledi.\n\nGünün sonunda moderatör, tartışmaların verimli geçtiğini söyleyip tüm katılımcılara teşekkür etti.",
        [
            ("İlk oturum hangi konuyla başladı?", ["Gençlerin dijital alışkanlıkları", "Çevre kirliliği", "Tarihî eserler", "Spor"]),
            ("Gençler günde ortalama kaç saat internette?", ["Beş saat", "İki saat", "On saat", "Bir saat"]),
            ("Katılımcı hangi soruyu sordu?", ["Örneklem yeterince büyük mü?", "Veriler nereden geldi?", "Yöntem nedir?", "Sonuç nedir?"]),
            ("Araştırmaya kaç kişi katıldı?", ["Bin iki yüz", "Yüz", "Beş yüz", "On bin"]),
            ("Moderatör günün sonunda ne yaptı?", ["Katılımcılara teşekkür etti", "Oturumu iptal etti", "Soru sordu", "Sunum yaptı"]),
        ]),
    listening=([
        ("Moderatör", "Sunum için teşekkürler. Salondan soru var mı?"),
        ("Katılımcı", "Söz alabilir miyim? Yönteminiz hakkında bir sorum olacaktı."),
        ("Konuşmacı", "Tabii, buyurun."),
        ("Katılımcı", "Veriler nasıl toplandı?"),
        ("Konuşmacı", "Çevrim içi anketle topladık ve sonra çözümledik."),
        ("Moderatör", "Teşekkürler, bir sonraki bildiriye geçelim."),
    ], [
        ("Ishtirokchi nima so'radi?", ["Usul haqida", "Narx haqida", "Vaqt haqida", "Joy haqida"]),
        ("Ma'lumotlar qanday yig'ilgan?", ["Onlayn so'rovnoma bilan", "Intervyu", "Kuzatuv", "Kitoblardan"]),
    ]),
    practice=[
        ('c', "\"Tadqiqotda yoshlarning ko'pi internetdan foydalanishi ko'rinmoqda.\"", ["Araştırmada gençlerin çoğunun internet kullandığı görülmektedir.", "Araştırmada gençler internet kullandı mı.", "Gençler araştırmada internet.", "Araştırma gençleri görüyor."]),
        ('c', "\"So'z olsam bo'ladimi?\"", ["Söz alabilir miyim?", "Söz aldım mı?", "Söz alacak mıyım?", "Söz alsın mı?"]),
        ('c', "\"Munozara\" turkchada:", ["tartışma", "sunum", "yöntem", "veri"]),
        ('c', "\"Tahlil qilmoq\" turkchada:", ["çözümlemek", "sunmak", "sormak", "katılmak"]),
        ('o', "\"Veriler yangi natijani ko'rsatmoqda.\" gapini tuzing.", ["Veriler", "yeni", "bir", "sonuç", "göstermektedir."]),
        ('o', "\"Ishtirokchilarga rahmat aytdi.\" gapini tuzing.", ["Katılımcılara", "teşekkür", "etti."]),
    ],
    writing=("Tadqiqot natijasini ilmiy uslubda 3 gap bilan yozing (-mAktAdIr dan foydalaning).",
             "Araştırma sonuçları öğrencilerin çoğunun düzenli okuduğunu göstermektedir. Okuma süresi artmaktadır. Bu durum olumlu bir gelişmedir."),
    speaking=["Söz alabilir miyim?", "Bir sorum olacaktı.", "Veriler artışı göstermektedir.", "Bu konuda şunu eklemek isterim."],
    test=[
        ("\"Görülmektedir\" nima degani?", ["ko'rinmoqda (ilmiy)", "ko'rdi", "ko'radi", "ko'rsa"]),
        ("\"Söz alabilir miyim?\" nima?", ["So'z olsam bo'ladimi?", "So'z oldingmi?", "So'z olaman", "So'z ol"]),
        ("\"Ancak\" nima degani?", ["biroq", "shuning uchun", "bundan tashqari", "chunki"]),
        ("\"Dolayısıyla\" nima degani?", ["shunga ko'ra", "biroq", "boshqa tomondan", "ammo"]),
        ("\"Ayrıca\" nima degani?", ["bundan tashqari", "biroq", "shuning uchun", "agar"]),
        ("\"Veri\" nima?", ["ma'lumot, statistika", "natija", "usul", "faraz"]),
        ("\"Yöntem\" nima?", ["usul", "natija", "faraz", "tanqid"]),
        ("\"Varsayım\" nima?", ["faraz", "natija", "usul", "ma'lumot"]),
        ("\"Katkı\" nima?", ["hissa", "tanqid", "natija", "usul"]),
        ("\"Moderatör\" kim?", ["boshqaruvchi", "ma'ruzachi", "tinglovchi", "kotib"]),
    ],
    bank=[
        ("\"Eleştiri\" nima?", ["tanqid", "maqtov", "natija", "faraz"]),
        ("\"Sonuç\" nima?", ["natija", "usul", "faraz", "ma'lumot"]),
        ("\"Sunum\" nima?", ["taqdimot", "munozara", "tadqiqot", "ro'yxat"]),
        ("\"Araştırma\" nima?", ["tadqiqot", "taqdimot", "savol", "natija"]),
        ("\"Görüş\" nima?", ["fikr", "ko'rish", "natija", "usul"]),
        ("\"Örneklem\" nima?", ["tanlanma (namuna)", "natija", "usul", "faraz"]),
        ("\"Öte yandan\" nima?", ["boshqa tomondan", "shuning uchun", "ammo", "chunki"]),
        ("\"Açabilir misiniz?\" nima?", ["ochib bera olasizmi?", "ochdingizmi?", "ochasizmi?", "ochdim"]),
        ("\"Katılmıyorum\" nima?", ["qo'shilmayman", "qo'shilaman", "qatnashaman", "ketaman"]),
        ("\"Katılıyorum\" nima?", ["qo'shilaman", "qo'shilmayman", "bilmayman", "bormayman"]),
        ("\"Yapıcı\" nima?", ["konstruktiv", "buzg'unchi", "uzun", "qisqa"]),
        ("\"Verimli\" nima?", ["samarali", "samarasiz", "uzun", "qisqa"]),
    ],
)

C = topic(
    'u6c', "C. Bildiri Sunuyorum — Ma'ruza qilaman", 123, 130,
    goals=[
        "Ma'ruza strukturasini (kirish, asosiy qism, xulosa) va bog'lovchi iboralarni qo'llash",
        "Ilmiy taqdimot lug'ati va uslubini bilish",
        "Qisqa ilmiy ma'ruzani turkcha tayyorlash",
    ],
    blocks=[
        ("Sunum yapısı: giriş, gelişme, sonuç",
         "Ma'ruza uch qismdan iborat. Kirish: Bugün sizlere ... hakkında konuşacağım. Asosiy qism: İlk olarak ... İkinci olarak ... Bununla birlikte ... Xulosa: Sonuç olarak ... Özetle ... Dinlediğiniz için teşekkür ederim."),
        ("Sıralama ve geçiş ifadeleri",
         "Ketma-ketlik: ilk olarak, daha sonra, ardından, son olarak. O'tish: Bununla birlikte (shu bilan birga), buna karşın (bunga qaramay), örneğin (masalan), başka bir deyişle (boshqacha aytganda)."),
        ("Grafik ve tablo yorumlama",
         "Grafikni tahlil qilish: Grafiğe göre ... artmıştır. Tabloda görüldüğü gibi ... Ortalamanın üzerinde / altında. Yüzde yirmi oranında yükselmiştir."),
    ],
    facts=[
        "Ma'ruza tuzilishi: giriş — gelişme — sonuç.",
        "Ketma-ketlik: ilk olarak, daha sonra, son olarak.",
        "Xulosa: sonuç olarak, özetle.",
        "Grafik tahlili: -DIğI görülmektedir, ...oranında artmıştır.",
    ],
    vocab=[
        ("giriş", "kirish", "Sunumun girişi kısa olmalı.", "Taqdimotning kirishi qisqa bo'lishi kerak."),
        ("gelişme", "asosiy qism, rivojlanish", "Gelişme bölümünde örnekler verdim.", "Asosiy qismda misollar keltirdim."),
        ("sonuç", "xulosa, natija", "Sonuç bölümünde özetledim.", "Xulosa qismida umumlashtirdim."),
        ("grafik", "grafik", "Grafik artışı gösteriyor.", "Grafik o'sishni ko'rsatmoqda."),
        ("tablo", "jadval", "Tablodaki verilere bakınız.", "Jadvaldagi ma'lumotlarga qarang."),
        ("oran", "nisbat, foiz", "Oran yüzde yirmi arttı.", "Nisbat yigirma foizga oshdi."),
        ("ortalama", "o'rtacha", "Ortalama puan seksen beş.", "O'rtacha ball sakson besh."),
        ("örnek", "misol", "Size bir örnek vereyim.", "Sizga bir misol keltiray."),
        ("vurgulamak", "ta'kidlamoq", "Bu noktayı vurgulamak isterim.", "Bu nuqtani ta'kidlashni istardim."),
        ("özetlemek", "umumlashtirmoq", "Konuyu kısaca özetleyeceğim.", "Mavzuni qisqacha umumlashtiraman."),
        ("kanıtlamak", "isbotlamoq", "Deney bu varsayımı kanıtladı.", "Tajriba bu farazni isbotladi."),
        ("sınırlılık", "cheklov", "Çalışmanın sınırlılıkları var.", "Ishning cheklovlari bor."),
    ],
    reading=("Başarılı bir sunum nasıl yapılır?",
        "İyi bir bildiri sunumu üç aşamadan oluşur: giriş, gelişme ve sonuç. Girişte konuşmacı kendini tanıtır ve konuyu kısaca açıklar. \"Bugün sizlere şehirlerde hava kirliliği hakkında konuşacağım\" gibi bir cümle dinleyicinin dikkatini toplar.\n\nGelişme bölümünde ilk olarak araştırmanın yöntemi anlatılır; ardından bulgular grafik ve tablolarla sunulur. Konuşmacı \"Grafikte görüldüğü gibi, kirlilik oranı son beş yılda yüzde yirmi artmıştır\" diyerek veriyi yorumlar. Bununla birlikte sınırlılıklar da belirtilmelidir.\n\nSonuç bölümünde ana fikirler özetlenir ve öneriler sunulur. Son olarak dinleyicilere teşekkür edilir ve sorular alınır. Sakin olmak ve zamana uymak başarılı sunumun anahtarıdır.",
        [
            ("Sunum kaç aşamadan oluşur?", ["Üç", "İki", "Dört", "Beş"]),
            ("Girişte konuşmacı ne yapar?", ["Kendini tanıtır ve konuyu açıklar", "Sonuçları sunar", "Soru sorar", "Teşekkür eder"]),
            ("Gelişme bölümünde ilk ne anlatılır?", ["Araştırmanın yöntemi", "Teşekkür", "Öneriler", "Sorular"]),
            ("Örnek cümleye göre kirlilik oranı ne kadar arttı?", ["Yüzde yirmi", "Yüzde elli", "Yüzde on", "Yüzde yüz"]),
            ("Başarılı sunumun anahtarı nedir?", ["Sakin olmak ve zamana uymak", "Hızlı konuşmak", "Slayt çoğaltmak", "Okumak"]),
        ]),
    listening=([
        ("Konuşmacı", "Bugün sizlere çevrimiçi eğitim hakkında konuşacağım."),
        ("Konuşmacı", "İlk olarak yöntemi anlatacağım, daha sonra bulguları sunacağım."),
        ("Konuşmacı", "Tabloda görüldüğü gibi katılım oranı yüzde otuz arttı."),
        ("Konuşmacı", "Bununla birlikte bazı sınırlılıklar da var."),
        ("Konuşmacı", "Sonuç olarak çevrimiçi eğitim verimlidir."),
        ("Konuşmacı", "Beni dinlediğiniz için teşekkür ederim."),
    ], [
        ("Ma'ruzachi dastlab nimani tushuntiradi?", ["Usulni", "Natijani", "Xulosani", "Rahmatni"]),
        ("Ishtirok darajasi qanchaga oshgan?", ["O'ttiz foizga", "O'n foizga", "Ellik foizga", "Hech"]),
    ]),
    practice=[
        ('c', "\"Bugun sizlarga ... haqida gapirib beraman.\"", ["Bugün sizlere ... hakkında konuşacağım.", "Bugün sizi ... konuştum.", "Bugün siz ... konuşuyor.", "Bugün ... sizden konuştu."]),
        ('c', "\"Birinchidan\" turkchada:", ["ilk olarak", "son olarak", "sonuç olarak", "örneğin"]),
        ('c', "\"Masalan\" turkchada:", ["örneğin", "bununla birlikte", "özetle", "ilk olarak"]),
        ('c', "\"Xulosa qilib aytganda\" turkchada:", ["sonuç olarak", "ilk olarak", "ayrıca", "örneğin"]),
        ('o', "\"Jadvalda ko'rinishicha ishtirok oshgan.\" gapini tuzing.", ["Tabloda", "görüldüğü", "gibi", "katılım", "artmıştır."]),
        ('o', "\"Sizga bir misol keltiray.\" gapini tuzing.", ["Size", "bir", "örnek", "vereyim."]),
    ],
    writing=("Qisqa ma'ruza rejasini tuzing: kirish, asosiy qism, xulosa (har biriga bir gap).",
             "Giriş: Bugün çevre kirliliğinden bahsedeceğim. Gelişme: İlk olarak nedenlerini inceleyeceğim. Sonuç: Önlemlerin artırılması gerekiyor."),
    speaking=["Bugün sizlere konuşacağım.", "İlk olarak yöntemi anlatacağım.", "Tabloda görüldüğü gibi oran arttı.", "Dinlediğiniz için teşekkür ederim."],
    test=[
        ("Ma'ruza necha qismdan iborat?", ["uch (kirish, asosiy, xulosa)", "ikki", "to'rt", "besh"]),
        ("\"Giriş\" nima?", ["kirish", "xulosa", "asosiy qism", "natija"]),
        ("\"Sonuç olarak\" nima degani?", ["xulosa qilib", "dastlab", "masalan", "shuning uchun"]),
        ("\"Örneğin\" nima degani?", ["masalan", "bundan tashqari", "chunki", "natijada"]),
        ("\"Bununla birlikte\" nima degani?", ["shu bilan birga", "chunki", "masalan", "natijada"]),
        ("\"Oran\" nima?", ["nisbat, foiz", "jadval", "misol", "xulosa"]),
        ("\"Ortalama\" nima?", ["o'rtacha", "eng ko'p", "eng kam", "jami"]),
        ("\"Vurgulamak\" nima?", ["ta'kidlamoq", "unutmoq", "yashirmoq", "o'chirmoq"]),
        ("\"Özetlemek\" nima?", ["umumlashtirmoq", "cho'zmoq", "yashirmoq", "unutmoq"]),
        ("\"Tablo\" nima?", ["jadval", "grafik", "misol", "xulosa"]),
    ],
    bank=[
        ("\"Grafik\" nima?", ["grafik", "jadval", "xulosa", "misol"]),
        ("\"Kanıtlamak\" nima?", ["isbotlamoq", "rad etmoq", "yashirmoq", "unutmoq"]),
        ("\"Sınırlılık\" nima?", ["cheklov", "afzallik", "natija", "xulosa"]),
        ("\"Gelişme\" nima?", ["asosiy qism, rivojlanish", "kirish", "xulosa", "rahmat"]),
        ("\"Son olarak\" nima?", ["oxirida", "dastlab", "masalan", "ammo"]),
        ("\"Daha sonra\" nima?", ["keyin", "oldin", "ayni payt", "hech"]),
        ("\"Ardından\" nima?", ["undan keyin", "undan oldin", "ayni payt", "hech"]),
        ("\"Başka bir deyişle\" nima?", ["boshqacha aytganda", "masalan", "shuning uchun", "ammo"]),
        ("\"Yüzde yirmi\" nima?", ["yigirma foiz", "o'n foiz", "yuz foiz", "ikki foiz"]),
        ("\"Ortalamanın üzerinde\" nima?", ["o'rtachadan yuqori", "o'rtachadan past", "o'rtacha", "hech"]),
        ("\"Kendini tanıtmak\" nima?", ["o'zini tanishtirmoq", "o'zini yashirmoq", "ketmoq", "kutmoq"]),
        ("\"Dikkat toplamak\" nima?", ["diqqatni jalb qilmoq", "uxlamoq", "ketmoq", "yozmoq"]),
    ],
)

TOPICS = [A, B, C]
