# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u7a', "A. Abaküsten Bilgisayara — Abakdan kompyuterga", 132, 139,
    goals=[
        "Sonlar, kasrlar va arifmetik amallar turkchasini bilish",
        "Hisoblash vositalarining tarixini (abak, kalkulyator, kompyuter) o'qib tushunish",
        "Ketma-ketlik va sabab bildiruvchi tuzilmalarni qo'llash",
    ],
    blocks=[
        ("Sayılar ve işlemler",
         "Toplama (+): İki artı üç beş eder. Çıkarma (-): On eksi dört altı eder. Çarpma (x): Üç kere dört on iki eder. Bölme (/): On ikiyi dörde böleriz, üç eder. Kesir: yarım (1/2), çeyrek (1/4), üçte bir (1/3), dörtte üç (3/4). Yüzde: yüzde elli (%50)."),
        ("Sıra ve kesir sayıları: -(I)ncI, -(I)şAr, -lArcA",
         "Tartib son: birinci, ikinci, üçüncü. Taqsimlash: ikişer (ikkitadan), üçer (uchtadan). Taxminiy ko'p: yüzlerce (yuzlab), binlerce (minglab). Örnek: Öğrencilere üçer kitap verildi."),
        ("Tarihsel gelişim: -DIktAn sonra, ...-(y)AlI",
         "Vaqt ketma-ketligi: Abaküs bulunduktan sonra hesap kolaylaştı. Bilgisayar icat edileli yetmiş yıl oldu. -(y)AlI \"...gandan beri\" ma'nosini beradi: Telefon icat edileli hayat değişti."),
    ],
    facts=[
        "+ artı, - eksi, x kere (çarpı), / bölü; yüzde = %.",
        "Abaküs — eng qadimgi hisoblash vositalaridan biri (Mesopotamiya, Xitoy).",
        "Birinchi elektron kompyuterlar XX asr o'rtalarida paydo bo'lgan.",
        "-(y)AlI = ...gandan beri; -şAr = ...tadan (taqsimlash).",
    ],
    vocab=[
        ("abaküs", "abak (hisoblash taxtasi)", "Abaküs eski bir hesap aracıdır.", "Abak qadimiy hisoblash vositasi."),
        ("hesap makinesi", "kalkulyator", "Hesap makinesiyle işlemi yaptım.", "Kalkulyator bilan amalni bajardim."),
        ("bilgisayar", "kompyuter", "Bilgisayarlar hayatımızı değiştirdi.", "Kompyuterlar hayotimizni o'zgartirdi."),
        ("toplama", "qo'shish", "Toplama işlemi kolaydır.", "Qo'shish amali oson."),
        ("çıkarma", "ayirish", "Çıkarma işlemi dikkat ister.", "Ayirish amali diqqat talab qiladi."),
        ("çarpma", "ko'paytirish", "Çarpma tablosunu ezberledim.", "Ko'paytirish jadvalini yodladim."),
        ("bölme", "bo'lish", "Bölme işlemini yapabiliyor musun?", "Bo'lish amalini bajara olasanmi?"),
        ("kesir", "kasr", "Yarım bir kesirdir.", "Yarim kasrdir."),
        ("rakam", "raqam", "Sayılar rakamlardan oluşur.", "Sonlar raqamlardan tashkil topadi."),
        ("sayı", "son", "Beş bir sayıdır.", "Besh bir sondir."),
        ("hesaplamak", "hisoblamoq", "Maliyeti hesapladım.", "Xarajatni hisobladim."),
        ("ilk", "birinchi, dastlabki", "İlk bilgisayar çok büyüktü.", "Birinchi kompyuter juda katta edi."),
    ],
    reading=("Hesap yapmanın tarihi",
        "İnsanlar sayı saymaya parmaklarıyla başladı. Zamanla taş ve çubuklarla hesap yapıldı. Bundan sonra abaküs bulundu. Abaküs, Mezopotamya ve Çin'de yüzlerce yıl kullanıldı; küçük boncukları kaydırarak toplama ve çıkarma yapılırdı.\n\nOn yedinci yüzyılda ilk mekanik hesap makineleri geliştirildi. Ancak asıl devrim yirminci yüzyılın ortasında yaşandı: İlk elektronik bilgisayarlar bir odayı dolduracak kadar büyüktü ve saniyede binlerce işlem yapabiliyordu. Bilgisayarlar icat edileli birkaç on yıl geçti; bugün cebimizdeki telefonlar o dev makinelerden milyonlarca kat güçlüdür.\n\nSayılar sadece hesap için değil, bilimde, müzikte ve sanatta da kullanılır. Bu yüzden matematik hayatın her alanında karşımıza çıkar.",
        [
            ("İnsanlar saymaya neyle başladı?", ["Parmaklarıyla", "Abaküsle", "Bilgisayarla", "Hesap makinesiyle"]),
            ("Abaküs nerelerde kullanıldı?", ["Mezopotamya ve Çin'de", "Amerika'da", "Afrika'da", "Avrupa'da"]),
            ("İlk elektronik bilgisayarlar nasıldı?", ["Bir odayı dolduracak kadar büyüktü", "Cep boyutundaydı", "Çok ucuzdu", "Çok yavaştı"]),
            ("Bugün telefonlar eski bilgisayarlardan nasıl?", ["Milyonlarca kat güçlü", "Daha zayıf", "Aynı", "Daha büyük"]),
            ("Metne göre matematik nerede karşımıza çıkar?", ["Hayatın her alanında", "Sadece okulda", "Sadece bankada", "Sadece fabrikada"]),
        ]),
    listening=([
        ("Öğrenci", "Öğretmenim, on iki bölü dört kaç eder?"),
        ("Öğretmen", "Üç eder. Yarım ile çeyreği toplarsak kaç eder?"),
        ("Öğrenci", "Dörtte üç eder."),
        ("Öğretmen", "Çok güzel. Şimdi çıkarma: yüz eksi otuz beş?"),
        ("Öğrenci", "Altmış beş."),
        ("Öğretmen", "Aferin, hesap makinesini kullanmadan yaptın."),
    ], [
        ("12 / 4 nechaga teng?", ["Uchga", "Beshga", "To'rtga", "Oltiga"]),
        ("Yarim va chorakni qo'shsak nima chiqadi?", ["To'rtdan uch", "Yarim", "Bir", "Chorak"]),
    ]),
    practice=[
        ('c', "\"Ikki qo'shuv uch besh bo'ladi.\"", ["İki artı üç beş eder.", "İki eksi üç beş eder.", "İki kere üç beş.", "İki bölü üç beş."]),
        ('c', "\"Yarim\" turkchada:", ["yarım", "çeyrek", "üçte bir", "yüzde"]),
        ('c', "\"Chorak\" turkchada:", ["çeyrek", "yarım", "bütün", "üçte"]),
        ('c', "\"Kompyuter ixtiro qilinganiga yetmish yil bo'ldi.\"", ["Bilgisayar icat edileli yetmiş yıl oldu.", "Bilgisayar icat edecek yetmiş yıl.", "Bilgisayar icat etti yetmiş yılı.", "Bilgisayar yetmiş icat."]),
        ('o', "\"O'quvchilarga uchtadan kitob berildi.\" gapini tuzing.", ["Öğrencilere", "üçer", "kitap", "verildi."]),
        ('o', "\"O'n ikkini to'rtga bo'lamiz.\" gapini tuzing.", ["On", "ikiyi", "dörde", "böleriz."]),
    ],
    writing=("Bir kunlik xarajatingizni hisoblab, 3 gap yozing (sonlar va amallar bilan).",
             "Bugün marketten on iki lira harcadım. Otobüse beş lira verdim. Toplam on yedi lira harcamış oldum."),
    speaking=["İki artı üç beş eder.", "On ikiyi dörde böleriz.", "Yüzde elli yarım demektir.", "Bilgisayar icat edileli hayat değişti."],
    test=[
        ("\"Artı\" nima?", ["qo'shuv (+)", "ayirish", "ko'paytirish", "bo'lish"]),
        ("\"Eksi\" nima?", ["ayirish (-)", "qo'shish", "ko'paytirish", "bo'lish"]),
        ("\"Çarpma\" nima?", ["ko'paytirish", "qo'shish", "ayirish", "bo'lish"]),
        ("\"Bölme\" nima?", ["bo'lish", "qo'shish", "ayirish", "ko'paytirish"]),
        ("\"Yarım\" nechaga teng?", ["1/2", "1/4", "1/3", "3/4"]),
        ("\"Çeyrek\" nechaga teng?", ["1/4", "1/2", "1/3", "3/4"]),
        ("\"Üçer\" nima degani?", ["uchtadan", "uch marta", "uchinchi", "yuzlab"]),
        ("\"Binlerce\" nima degani?", ["minglab", "bir", "mingta", "yuzta"]),
        ("\"-(y)AlI\" nima degani?", ["...gandan beri", "...gandan keyin", "...gan sari", "...maguncha"]),
        ("\"Abaküs\" nima?", ["abak", "kalkulyator", "kompyuter", "kasr"]),
    ],
    bank=[
        ("\"Rakam\" nima?", ["raqam", "son", "kasr", "amal"]),
        ("\"Sayı\" nima?", ["son", "raqam", "harf", "amal"]),
        ("\"Hesaplamak\" nima?", ["hisoblamoq", "yozmoq", "o'qimoq", "yig'moq"]),
        ("\"Kesir\" nima?", ["kasr", "son", "raqam", "foiz"]),
        ("\"Hesap makinesi\" nima?", ["kalkulyator", "kompyuter", "abak", "soat"]),
        ("\"Yüzde elli\" nima?", ["50%", "5%", "500%", "15%"]),
        ("\"İlk\" nima?", ["birinchi", "oxirgi", "ikkinchi", "so'nggi"]),
        ("\"Üçte bir\" nima?", ["1/3", "3/1", "1/2", "3/4"]),
        ("\"Dörtte üç\" nima?", ["3/4", "4/3", "1/4", "1/3"]),
        ("\"Yüzlerce\" nima?", ["yuzlab", "yuz", "mingta", "o'n"]),
        ("\"Eder\" nima degani?", ["teng bo'ladi", "teng emas", "ko'p", "kam"]),
        ("\"Maliyet\" nima?", ["tannarx, xarajat", "foyda", "soliq", "narx"]),
    ],
)

B = topic(
    'u7b', "B. Sayılar Ne Söyler? — Sonlar nima deydi?", 140, 144,
    goals=[
        "Statistika va foiz bilan ishlash (artmak, azalmak, oranında) ifodalarini qo'llash",
        "Grafik va diagramma tahlil qilish iboralarini bilish",
        "Aholi va iqtisodiyot ma'lumotlarini matnda tushunish",
    ],
    blocks=[
        ("Artış ve azalış ifadeleri",
         "O'zgarishni ifodalash: artmak (oshmoq), azalmak (kamaymoq), yükselmek (ko'tarilmoq), düşmek (tushmoq), sabit kalmak (o'zgarmay qolmoq). Nisbat: yüzde on oranında artmıştır. Taqqoslash: ... ile karşılaştırıldığında, ...e göre."),
        ("Sayısal ifadeler: ortalama, çoğunluk, azınlık",
         "Ortalama (o'rtacha), çoğunluk (ko'pchilik), azınlık (ozchilik), yarıdan fazla (yarmidan ko'p), her on kişiden biri (har o'n kishidan biri). Örnek: Nüfusun yarıdan fazlası şehirde yaşıyor."),
        ("Yorum yapma: -mAktAdIr, -DIğI gözlenmektedir",
         "Ma'lumotni sharhlash: Grafikte görüldüğü gibi, işsizlik oranı düşmektedir. Veriler, tüketimin arttığını göstermektedir. Bu sonuç ... açıklanabilir."),
    ],
    facts=[
        "artmak ↔ azalmak; yükselmek ↔ düşmek; sabit kalmak.",
        "çoğunluk = ko'pchilik; azınlık = ozchilik; ortalama = o'rtacha.",
        "Grafik tahlili: ...ile karşılaştırıldığında, ...oranında artmıştır.",
        "Turkiya aholisi 85 milliondan ortiq (taxminan).",
    ],
    vocab=[
        ("nüfus", "aholi", "Nüfus her yıl artıyor.", "Aholi har yili o'smoqda."),
        ("istatistik", "statistika", "İstatistikler ilginç sonuçlar veriyor.", "Statistika qiziq natijalar bermoqda."),
        ("artış", "o'sish", "Fiyatlarda artış var.", "Narxlarda o'sish bor."),
        ("azalış", "kamayish", "Doğum oranında azalış görülüyor.", "Tug'ilish nisbatida kamayish ko'rinmoqda."),
        ("çoğunluk", "ko'pchilik", "Çoğunluk bu görüşte.", "Ko'pchilik shu fikrda."),
        ("azınlık", "ozchilik", "Azınlık farklı düşünüyor.", "Ozchilik boshqacha o'ylaydi."),
        ("anket", "so'rovnoma", "Ankete beş yüz kişi katıldı.", "So'rovnomada besh yuz kishi qatnashdi."),
        ("oran", "nisbat", "İşsizlik oranı düştü.", "Ishsizlik nisbati tushdi."),
        ("karşılaştırmak", "qiyoslamoq", "İki yılı karşılaştıralım.", "Ikki yilni qiyoslaylik."),
        ("yaklaşık", "taxminan", "Yaklaşık iki milyon kişi katıldı.", "Taxminan ikki million kishi qatnashdi."),
        ("toplam", "jami", "Toplam gelir yüz bin lira.", "Jami daromad yuz ming lira."),
        ("tahmini", "taxminiy", "Tahmini maliyet yüksek.", "Taxminiy xarajat yuqori."),
    ],
    reading=("Rakamlar ne anlatıyor?",
        "Son on yılın verilerine bakıldığında Türkiye'nin nüfusunun yaklaşık yüzde on arttığı görülmektedir. Nüfusun yarıdan fazlası otuz beş yaşın altındadır; yani ülke genç bir nüfusa sahiptir. Şehirlerde yaşayanların oranı ise yüzde seksen civarındadır.\n\nEğitim alanında da önemli gelişmeler var. Okuryazar oranı yükselmiş, üniversite öğrencisi sayısı iki katına çıkmıştır. Ancak kırsal bölgelerde okullaşma oranı hâlâ şehirlere göre düşüktür.\n\nAnket sonuçları, gençlerin çoğunluğunun teknolojiyi günlük yaşamda kullandığını göstermektedir. Rakamlar yalnızca sayı değildir; bir toplumun hâlini ve geleceğini anlatır. Bu nedenle verileri doğru yorumlamak gerekir.",
        [
            ("Nüfus son on yılda ne kadar arttı?", ["Yaklaşık yüzde on", "Yüzde elli", "Yüzde bir", "Yüzde yüz"]),
            ("Nüfusun yarıdan fazlası kaç yaşın altında?", ["Otuz beş", "On beş", "Elli", "Yirmi"]),
            ("Şehirde yaşayanların oranı yaklaşık nedir?", ["Yüzde seksen", "Yüzde elli", "Yüzde yirmi", "Yüzde yüz"]),
            ("Üniversite öğrenci sayısı nasıl değişti?", ["İki katına çıktı", "Yarıya düştü", "Aynı kaldı", "Üç kat azaldı"]),
            ("Kırsalda okullaşma oranı şehirlere göre nasıl?", ["Daha düşük", "Daha yüksek", "Aynı", "Bilinmiyor"]),
        ]),
    listening=([
        ("Sunucu", "Son ankete göre insanların yüzde altmışı online alışveriş yapıyor."),
        ("Konuk", "Evet, geçen yıla göre yüzde on beş artış var."),
        ("Sunucu", "Peki hangi yaş grubu daha çok kullanıyor?"),
        ("Konuk", "Yirmi ile otuz yaş arası çoğunluğu oluşturuyor."),
        ("Sunucu", "Yaşlılar ise azınlıkta, değil mi?"),
        ("Konuk", "Evet, ama onların sayısı da giderek artıyor."),
    ], [
        ("Onlayn xaridlar o'tgan yilga nisbatan qanchaga oshgan?", ["O'n besh foizga", "Oltmish foizga", "Ellik foizga", "Ikki foizga"]),
        ("Qaysi yosh guruhi ko'pchilikni tashkil etadi?", ["Yigirmadan o'ttizgacha", "Qirqdan ellikkacha", "O'ndan yigirmagacha", "Oltmishdan yuqori"]),
    ]),
    practice=[
        ('c', "\"Narxlar o'n foizga oshdi.\"", ["Fiyatlar yüzde on oranında arttı.", "Fiyatlar yüzde on azaldı.", "Fiyatlar on kere.", "Fiyatlar yüzde on."]),
        ('c', "\"Aholining yarmidan ko'pi shaharda yashaydi.\"", ["Nüfusun yarıdan fazlası şehirde yaşıyor.", "Nüfusun yarısından az.", "Nüfus yarı şehirde değil.", "Nüfus şehir yarı."]),
        ('c', "\"Ko'pchilik\" turkchada:", ["çoğunluk", "azınlık", "ortalama", "oran"]),
        ('c', "\"Taxminan\" turkchada:", ["yaklaşık", "toplam", "tahmin", "oran"]),
        ('o', "\"Grafikda ishsizlik kamayayotgani ko'rinmoqda.\" gapini tuzing.", ["Grafikte", "işsizliğin", "azaldığı", "görülmektedir."]),
        ('o', "\"Ikki yilni qiyoslaylik.\" gapini tuzing.", ["İki", "yılı", "karşılaştıralım."]),
    ],
    writing=("Sinfdoshlaringiz orasida so'rovnoma o'tkazib, natijani 3 gapda yozing (foiz bilan).",
             "Anket yüz kişiyle yapıldı. Yüzde altmışı kitap okumayı seviyor. Azınlık ise sadece film izlemeyi tercih ediyor."),
    speaking=["Fiyatlar yüzde on arttı.", "Nüfusun yarıdan fazlası gençtir.", "Çoğunluk bu görüşte.", "Veriler artışı göstermektedir."],
    test=[
        ("\"Artmak\" nima degani?", ["oshmoq", "kamaymoq", "tushmoq", "to'xtamoq"]),
        ("\"Azalmak\" nima degani?", ["kamaymoq", "oshmoq", "ko'tarilmoq", "to'xtamoq"]),
        ("\"Çoğunluk\" nima?", ["ko'pchilik", "ozchilik", "o'rtacha", "jami"]),
        ("\"Azınlık\" nima?", ["ozchilik", "ko'pchilik", "o'rtacha", "jami"]),
        ("\"Ortalama\" nima?", ["o'rtacha", "jami", "ko'p", "kam"]),
        ("\"Yarıdan fazla\" nima?", ["yarmidan ko'p", "yarmidan kam", "yarim", "butun"]),
        ("\"Anket\" nima?", ["so'rovnoma", "statistika", "diagramma", "jadval"]),
        ("\"Nüfus\" nima?", ["aholi", "oila", "shahar", "xalq"]),
        ("\"Karşılaştırmak\" nima?", ["qiyoslamoq", "hisoblamoq", "yozmoq", "tushunmoq"]),
        ("\"Toplam\" nima?", ["jami", "o'rtacha", "ko'p", "kam"]),
    ],
    bank=[
        ("\"Yükselmek\" nima?", ["ko'tarilmoq", "tushmoq", "to'xtamoq", "yo'qolmoq"]),
        ("\"Düşmek\" nima (kamayish ma'nosida)?", ["tushmoq", "ko'tarilmoq", "oshmoq", "to'xtamoq"]),
        ("\"Sabit kalmak\" nima?", ["o'zgarmay qolmoq", "oshmoq", "tushmoq", "yo'qolmoq"]),
        ("\"Yaklaşık\" nima?", ["taxminan", "aniq", "hech", "ko'p"]),
        ("\"İstatistik\" nima?", ["statistika", "jadval", "grafik", "sarlavha"]),
        ("\"Tahmini\" nima?", ["taxminiy", "aniq", "yangi", "eski"]),
        ("\"Her on kişiden biri\" nima?", ["har o'n kishidan biri", "o'n kishi", "o'ntadan ko'p", "o'ntadan kam"]),
        ("\"...ile karşılaştırıldığında\" nima?", ["...bilan qiyoslaganda", "...uchun", "...sababli", "...gandan beri"]),
        ("\"...e göre\" nima?", ["...ga ko'ra", "...ga qaramay", "...uchun", "...sari"]),
        ("\"Yorumlamak\" nima?", ["sharhlamoq", "hisoblamoq", "yozmoq", "yashirmoq"]),
        ("\"Genç nüfus\" nima?", ["yosh aholi", "keksa aholi", "kam aholi", "ko'p aholi"]),
        ("\"Okullaşma oranı\" nima?", ["maktabga qamrov darajasi", "o'qituvchi soni", "dars soati", "maktab narxi"]),
    ],
)

C = topic(
    'u7c', "C. Hayatımızdaki Sayılar — Hayotimizdagi sonlar", 145, 154,
    goals=[
        "Sonlar bilan bog'liq idiomalar va madaniy ma'nolarni bilish",
        "Telefon, manzil, sana va vaqt sonlarini aytish",
        "Sonlarga oid fikr-mulohaza va taxmin bildirish",
    ],
    blocks=[
        ("Sayılarla ilgili deyimler",
         "Bir elin parmakları gibi (bir-biridan farqli). Yedi iklim dört bucak (butun dunyo). Ya sabır çekmek, yedi kat... kabi iboralar. Üç günlük dünya (qisqa umr). Bir göz kırpmada (bir ko'z qisganda). İkiye bölmek (ikkiga bo'lmoq)."),
        ("Telefon, adres, tarih ve saat",
         "Telefon: 0532 123 45 67 — sıfır beş yüz otuz iki, yüz yirmi üç, kırk beş, altmış yedi. Sana: 12 Mayıs 2024 — on iki Mayıs iki bin yirmi dört. Vaqt: 15.45 — on beş kırk beş yoki dörde çeyrek var. Manzil: Atatürk Caddesi No: 25 Daire: 4."),
        ("Tahmin ve yorum: -sA gerek, herhalde, kadar",
         "Taxmin: Yaklaşık yüz kişi vardır. Herhalde on bir civarı olacak. Qiyos: İki kat, üç misli (uch barobar), yarı yarıya (yarmi). Misal: Fiyat iki katına çıktı."),
    ],
    facts=[
        "Sonli idiomalar: yedi iklim dört bucak = butun dunyo.",
        "Telefon nomerlari guruhlab o'qiladi: sıfır beş yüz otuz iki ...",
        "Vaqt: on beş kırk beş yoki dörde çeyrek var.",
        "iki kat = ikki barobar; yarı yarıya = yarmi-yarimga.",
    ],
    vocab=[
        ("iki kat", "ikki barobar", "Fiyat iki kat arttı.", "Narx ikki barobar oshdi."),
        ("yarı yarıya", "yarmi-yarimga", "Masrafı yarı yarıya paylaştık.", "Xarajatni yarmi-yarimga bo'lishdik."),
        ("telefon numarası", "telefon raqami", "Telefon numaranı verir misin?", "Telefon raqamingni bera olasanmi?"),
        ("doğum tarihi", "tug'ilgan sana", "Doğum tarihimi yazdım.", "Tug'ilgan sanamni yozdim."),
        ("sıra", "navbat, tartib", "Sırada üçüncüyüm.", "Navbatda uchinchiman."),
        ("numara", "nomer", "Evimin numarası on iki.", "Uyimning nomeri o'n ikki."),
        ("dakika", "daqiqa", "On dakika sonra gelirim.", "O'n daqiqadan keyin kelaman."),
        ("saniye", "soniya", "Bir saniye bekler misin?", "Bir soniya kutib tura olasanmi?"),
        ("asır", "asr", "Bu yirmi birinci asırdır.", "Bu yigirma birinchi asr."),
        ("on yıl", "o'n yil", "On yıl önce taşındık.", "O'n yil oldin ko'chib o'tdik."),
        ("tek / çift", "toq / juft", "Beş tek, altı çift sayıdır.", "Besh toq, olti juft son."),
        ("sıfır", "nol", "Sıfır sayısı çok önemlidir.", "Nol soni juda muhim."),
    ],
    reading=("Sayıların gizli hayatı",
        "Sayılar yalnızca matematikte değil, hayatın her yerinde karşımıza çıkar. Telefon numaramız, doğum tarihimiz, ev adresimiz hep rakamlardan oluşur. Ancak kültürlerde sayıların özel anlamları da vardır. Türkçede \"yedi iklim dört bucak\" dünyanın her yerini, \"üç günlük dünya\" ise hayatın kısalığını anlatır.\n\nBazı sayılar şans getirir veya uğursuz sayılır. Yedi, birçok kültürde şanslı kabul edilir. On üç ise bazı ülkelerde uğursuz sayılırken Türkiye'de pek bir önem taşımaz.\n\nGünlük hayatta sayıları doğru kullanmak da önemlidir. Bir telefon numarasını yanlış yazmak, büyük sorunlara yol açabilir. Bu yüzden numaraları iki iki veya üç üç okumak bellekte kalmasını kolaylaştırır.",
        [
            ("\"Yedi iklim dört bucak\" ne anlatır?", ["Dünyanın her yerini", "Yedi mevsimi", "Dört yönü", "Bir şehri"]),
            ("\"Üç günlük dünya\" ne anlatır?", ["Hayatın kısalığını", "Bir hafta tatili", "Üç günü", "Dünyanın küçüklüğünü"]),
            ("Birçok kültürde hangi sayı şanslı?", ["Yedi", "On üç", "Sıfır", "Dört"]),
            ("Numaraları nasıl okumak hatırlamayı kolaylaştırır?", ["İki iki veya üç üç", "Tek tek", "Hızlıca", "Sessizce"]),
            ("Yanlış telefon numarası ne yapar?", ["Büyük sorunlara yol açabilir", "Hiçbir şey olmaz", "Daha çok arama yapar", "Güvenlik sağlar"]),
        ]),
    listening=([
        ("Ayşe", "Telefon numaranı alabilir miyim?"),
        ("Burak", "Elbette: sıfır beş yüz otuz iki, yüz yirmi üç, kırk beş, altmış yedi."),
        ("Ayşe", "Adresin de lazım. Hangi cadde?"),
        ("Burak", "Atatürk Caddesi, numara yirmi beş, daire dört."),
        ("Ayşe", "Peki doğum tarihin ne zaman?"),
        ("Burak", "On iki Mayıs bin dokuz yüz doksan beş."),
    ], [
        ("Burakning uy raqami nechada?", ["Yigirma besh", "O'n ikki", "To'rt", "Yuz yigirma"]),
        ("U qachon tug'ilgan?", ["12 may 1995", "12 may 2005", "5 dekabr 1990", "15 may 1992"]),
    ]),
    practice=[
        ('c', "\"Narx ikki barobar oshdi.\"", ["Fiyat iki kat arttı.", "Fiyat iki eksildi.", "Fiyat iki oldu.", "Fiyat ikiye bölündü."]),
        ('c', "\"Xarajatni yarmi-yarimga bo'ldik.\"", ["Masrafı yarı yarıya paylaştık.", "Masrafı tamamen ödedik.", "Masrafı hiç paylaşmadık.", "Masrafı iki yıl."]),
        ('c', "\"Butun dunyo\" ma'nosidagi ibora:", ["yedi iklim dört bucak", "üç günlük dünya", "bir göz kırpmada", "ikiye bölmek"]),
        ('c', "\"Nol\" turkchada:", ["sıfır", "tek", "çift", "yarım"]),
        ('o', "\"Telefon raqamingni bera olasanmi?\" gapini tuzing.", ["Telefon", "numaranı", "verir", "misin?"]),
        ('o', "\"O'n daqiqadan keyin kelaman.\" gapini tuzing.", ["On", "dakika", "sonra", "gelirim."]),
    ],
    writing=("O'zingiz haqingizda raqamlar bilan 3 gap yozing (yosh, tug'ilgan sana, telefon).",
             "Yirmi iki yaşındayım. Doğum tarihim on iki Mayıs iki bin dört. Telefon numaram sıfır beş yüz otuz iki yüz yirmi üç kırk beş altmış yedi."),
    speaking=["Telefon numaranı verir misin?", "On dakika sonra gelirim.", "Fiyat iki kat arttı.", "Yedi iklim dört bucak."],
    test=[
        ("\"Yedi iklim dört bucak\" nima?", ["butun dunyo", "yetti fasl", "to'rt yo'nalish", "bir shahar"]),
        ("\"Üç günlük dünya\" nima?", ["hayotning qisqaligi", "uch kunlik ta'til", "uch kun", "kichik dunyo"]),
        ("\"İki kat\" nima?", ["ikki barobar", "yarim", "ikkita", "ikki yil"]),
        ("\"Yarı yarıya\" nima?", ["yarmi-yarimga", "to'liq", "hech", "ikki barobar"]),
        ("\"Sıfır\" nima?", ["nol", "bir", "yarim", "yuz"]),
        ("\"Tek sayı\" nima?", ["toq son", "juft son", "kasr", "foiz"]),
        ("\"Çift sayı\" nima?", ["juft son", "toq son", "kasr", "foiz"]),
        ("\"Saniye\" nima?", ["soniya", "daqiqa", "soat", "kun"]),
        ("\"Asır\" nima?", ["asr", "yil", "oy", "hafta"]),
        ("\"Numara\" nima?", ["nomer", "ism", "manzil", "sana"]),
    ],
    bank=[
        ("\"Dakika\" nima?", ["daqiqa", "soniya", "soat", "kun"]),
        ("\"Doğum tarihi\" nima?", ["tug'ilgan sana", "yashash joyi", "kasbi", "ismi"]),
        ("\"Sıra\" nima?", ["navbat, tartib", "nol", "son", "kasr"]),
        ("15.45 qanday o'qiladi?", ["on beş kırk beş", "on beş elli", "on dört kırk", "on altı kırk beş"]),
        ("\"On yıl\" nima?", ["o'n yil", "bir asr", "bir oy", "o'n kun"]),
        ("\"Bir göz kırpmada\" nima?", ["bir ko'z qisganda", "uzoq vaqt", "hech qachon", "ertaga"]),
        ("\"Üç misli\" nima?", ["uch barobar", "uchinchi", "uchta", "uch kun"]),
        ("\"Civarı\" nima?", ["atrofida, taxminan", "aniq", "ko'p", "kam"]),
        ("\"Adres\" nima?", ["manzil", "nomer", "sana", "ism"]),
        ("\"Daire\" nima (manzilda)?", ["kvartira", "ko'cha", "shahar", "uy"]),
        ("\"Şans getirir\" nima?", ["omad keltiradi", "baxtsizlik", "zarar", "xursandlik"]),
        ("\"Uğursuz\" nima?", ["baxtsiz, mash'um", "omadli", "yaxshi", "yangi"]),
    ],
)

TOPICS = [A, B, C]
