# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl import topic

A = topic(
    'u8a', "A. Bilim Adamı — Olim", 156, 160,
    goals=[
        "Biografiya yozishda -DI, -mIş, -DIktAn sonra, -(y)ArAk tuzilmalarini qo'llash",
        "Mashhur turk va sharq olimlari haqidagi matnni o'qib tushunish",
        "Ilm va kashfiyotga oid lug'atni bilish",
    ],
    blocks=[
        ("Biyografi anlatımı: doğdu, büyüdü, çalıştı",
         "Biografiyada voqealar ketma-ket o'tgan zamonda beriladi: 1010'da Harezm'de doğdu. Genç yaşta tıp okudu. Birçok eser yazdı ve 1048'de vefat etti. Tug'ilish, o'qish, ish, vafot ketma-ketligi saqlanadi."),
        ("Zaman bağlaçları: -DIktAn sonra, -mAdAn önce, -(y)IncA, -ken",
         "Vaqt bog'lovchilari: Eğitimini tamamladıktan sonra şehre döndü. Kitabı bitirmeden önce bir deney yaptı. Genç ken (yoshligida) matematikle ilgilendi. Hasta olunca çalışmayı bıraktı."),
        ("Katkı ve unvan: sayesinde, ... olarak tanındı",
         "Hissa va unvon: Bu keşif sayesinde tıp ilerledi. Bilim adamı olarak tanındı. \"...ı bulan kişi\" (ixtirochi), \"...nin kurucusu\". Hayatını bilime adadı (umrini ilmga bag'ishladi)."),
    ],
    facts=[
        "Biografiya: tug'ilgan joyi — o'qishi — kashfiyoti — vafoti.",
        "-DIktAn sonra = ...gandan keyin; -mAdAn önce = ...magunga qadar.",
        "Ibn Sino, Beruniy, Xorazmiy, Ulug'bek — Turon olimlari.",
        "Aziz Sancar — turk-amerikalik biolog, 2015-yilda Nobel mukofoti laureati.",
    ],
    vocab=[
        ("bilim adamı", "olim", "Bilim adamları hayatını araştırmaya adar.", "Olimlar umrini tadqiqotga bag'ishlaydi."),
        ("keşif", "kashfiyot", "Bu keşif tıpta devrim yarattı.", "Bu kashfiyot tibbiyotda inqilob yasadi."),
        ("buluş", "ixtiro", "Buluşlar hayatı kolaylaştırır.", "Ixtirolar hayotni yengillashtiradi."),
        ("deney", "tajriba, eksperiment", "Deney başarıyla sonuçlandı.", "Tajriba muvaffaqiyat bilan yakunlandi."),
        ("ödül", "mukofot", "Nobel ödülünü kazandı.", "Nobel mukofotini qo'lga kiritdi."),
        ("eser", "asar", "Onun birçok eseri dillere çevrildi.", "Uning ko'p asarlari tillarga tarjima qilindi."),
        ("öğrenci", "talaba, o'quvchi", "Öğrencileriyle birlikte çalıştı.", "Shogirdlari bilan birga ishladi."),
        ("hekim", "tabib", "Hekim hastaları tedavi etti.", "Tabib bemorlarni davoladi."),
        ("astronomi", "astronomiya", "Astronomi yıldızları inceler.", "Astronomiya yulduzlarni o'rganadi."),
        ("matematikçi", "matematik", "Matematikçi yeni bir yöntem buldu.", "Matematik yangi usul topdi."),
        ("adamak", "bag'ishlamoq", "Hayatını bilime adadı.", "Hayotini ilmga bag'ishladi."),
        ("vefat etmek", "vafot etmoq", "1037'de vefat etti.", "1037-yilda vafot etdi."),
    ],
    reading=("Aziz Sancar'ın hikâyesi",
        "Aziz Sancar, 1946'da Mardin'in Savur ilçesinde doğdu. İlkokulu köyünde okudu, sonra İstanbul Üniversitesi Tıp Fakültesi'ni bitirdi. Tıp eğitimini tamamladıktan sonra Amerika Birleşik Devletleri'ne gitti ve araştırmalara başladı.\n\nSancar, hücrelerin hasar gören DNA'yı nasıl onardığını inceledi. Bu çalışmasıyla 2015'te Nobel Kimya Ödülü'nü kazandı. Ödül töreninde Türk bayrağını taşıması, ülkesinde büyük sevinç yarattı.\n\nBugün Sancar, hem bilim insanı hem de Türkiye'de gençlere ilham veren biridir. Başarısını azim ve çalışkanlığa borçlu olduğunu söylüyor. Ona göre bilim, merak ve sabırla büyür.",
        [
            ("Aziz Sancar nerede doğdu?", ["Mardin'in Savur ilçesinde", "İstanbul'da", "Ankara'da", "İzmir'de"]),
            ("Tıp eğitimini bitirdikten sonra nereye gitti?", ["Amerika Birleşik Devletleri'ne", "Almanya'ya", "Fransa'ya", "Japonya'ya"]),
            ("Neyi inceledi?", ["Hasarlı DNA'nın onarımını", "Yıldızları", "Bitkileri", "Denizleri"]),
            ("Hangi ödülü kazandı?", ["2015 Nobel Kimya Ödülü", "Nobel Barış Ödülü", "Altın Küre", "Oscar"]),
            ("Başarısını neye borçlu olduğunu söylüyor?", ["Azim ve çalışkanlığa", "Şansa", "Paraya", "Tanıdıklara"]),
        ]),
    listening=([
        ("Öğrenci", "Ödevim İbn Sina hakkında. Ne biliyorsun?"),
        ("Arkadaş", "Buhara yakınlarında doğdu. Genç yaşta tıp okudu."),
        ("Öğrenci", "Eserlerini nerede yazdı?"),
        ("Arkadaş", "Çeşitli şehirlerde. \"El-Kanun fi't-Tıb\" yazdıktan sonra çok ünlendi."),
        ("Öğrenci", "Kaç yaşında vefat etti?"),
        ("Arkadaş", "Elli yedi yaşında, 1037'de."),
    ], [
        ("Ibn Sino qayerda tug'ilgan?", ["Buxoro yaqinida", "Xorazmda", "Samarqandda", "Misrda"]),
        ("U nechada vafot etgan?", ["Ellik yetti yoshida", "Oltmishda", "Qirqda", "Ellikda"]),
    ]),
    practice=[
        ('c', "\"U 1010-yilda Xorazmda tug'ildi.\"", ["1010'da Harezm'de doğdu.", "1010'da Harezm'de doğacak.", "1010'da Harezm'de doğmuş olur.", "1010'da Harezm'de doğar."]),
        ('c', "\"O'qishni tugatgandan keyin shaharga qaytdi.\"", ["Eğitimini tamamladıktan sonra şehre döndü.", "Eğitimi tamamlamadan şehre döndü.", "Eğitimi tamamlarken şehre.", "Eğitim tamamlayıp önce."]),
        ('c', "\"Ixtiro\" turkchada:", ["buluş", "keşif", "ödül", "deney"]),
        ('c', "\"Mukofot\" turkchada:", ["ödül", "eser", "deney", "hekim"]),
        ('o', "\"U umrini ilmga bag'ishladi.\" gapini tuzing.", ["Hayatını", "bilime", "adadı."]),
        ('o', "\"Bu kashfiyot sayesida tibbiyot rivojlandi.\" gapini tuzing.", ["Bu", "keşif", "sayesinde", "tıp", "ilerledi."]),
    ],
    writing=("O'zingiz hurmat qiladigan olim haqida 3 gapli qisqa biografiya yozing.",
             "Ulug Bey 1394'te doğdu. Semerkant'ta bir rasathane kurdu. 1449'da vefat etti."),
    speaking=["Harezm'de doğdu.", "Eğitimini tamamladıktan sonra döndü.", "Hayatını bilime adadı.", "Nobel ödülünü kazandı."],
    test=[
        ("Biografiyada odatda qaysi zamon?", ["o'tgan zamon", "kelasi zamon", "buyruq", "shart"]),
        ("\"-DIktAn sonra\" nima?", ["...gandan keyin", "...gunga qadar", "...gan sari", "...ish uchun"]),
        ("\"Genç ken\" nima degani?", ["yoshligida", "keksayganda", "kecha", "ertaga"]),
        ("\"Keşif\" nima?", ["kashfiyot", "ixtiro", "mukofot", "asar"]),
        ("\"Buluş\" nima?", ["ixtiro", "kashfiyot", "mukofot", "tajriba"]),
        ("\"Deney\" nima?", ["tajriba", "asar", "mukofot", "kashfiyot"]),
        ("\"Eser\" nima?", ["asar", "mukofot", "tajriba", "olim"]),
        ("\"Ödül\" nima?", ["mukofot", "asar", "tajriba", "ixtiro"]),
        ("\"Adamak\" nima?", ["bag'ishlamoq", "olmoq", "yo'qotmoq", "yashirmoq"]),
        ("\"Vefat etmek\" nima?", ["vafot etmoq", "tug'ilmoq", "o'qimoq", "yozmoq"]),
    ],
    bank=[
        ("\"Hekim\" nima?", ["tabib", "o'qituvchi", "olim", "rassom"]),
        ("\"Matematikçi\" kim?", ["matematik", "fizik", "kimyogar", "rassom"]),
        ("\"Astronomi\" nima?", ["astronomiya", "geografiya", "tibbiyot", "matematika"]),
        ("Aziz Sancar qachon Nobel olgan?", ["2015", "1946", "2000", "1990"]),
        ("Aziz Sancar nimani o'rgangan?", ["DNK tiklanishini", "yulduzlarni", "o'simliklarni", "dengizni"]),
        ("\"Çalışkanlık\" nima?", ["mehnatsevarlik", "tanbal", "baxt", "omad"]),
        ("\"Azim\" nima?", ["qat'iyat", "dangasalik", "qo'rquv", "xato"]),
        ("\"Merak\" nima?", ["qiziqish", "qo'rquv", "g'azab", "uyqu"]),
        ("\"İlham vermek\" nima?", ["ilhom bermoq", "ilhomni yo'qotmoq", "yashirmoq", "unutmoq"]),
        ("\"Tıp Fakültesi\" nima?", ["tibbiyot fakulteti", "huquq fakulteti", "til fakulteti", "tarix fakulteti"]),
        ("\"Ünlenmek\" nima?", ["mashhur bo'lmoq", "unutilmoq", "ketmoq", "kelmoq"]),
        ("\"Hasar gören\" nima?", ["shikastlangan", "yangi", "sog'lom", "katta"]),
    ],
)

B = topic(
    'u8b', "B. Kişiliğin Anahtarı: El Yazısı — Shaxsiyat kaliti: qo'l yozuvi", 161, 164,
    goals=[
        "Xulq-atvor va xarakter sifatlari lug'atini qo'llash",
        "Taxmin va xulosa shakllarini (-mIş gibi, belli ki, anlaşılan) ishlatish",
        "Qo'l yozuvi va xarakter munosabati haqidagi matnni tushunish",
    ],
    blocks=[
        ("Çıkarım ve tahmin: belli ki, anlaşılan, -mIş gibi",
         "Xulosa chiqarishda: Belli ki bu kişi titizdir. (Ma'lumki, bu odam puxta.) Anlaşılan o gün çok yorulmuş. (Ko'rinishidan, u kuni charchagan.) Sanki / -mIş gibi: Çok yorulmuş gibi görünüyor. -DIr bilan: Yazısı düzgünse, düzenli bir insandır."),
        ("Kişilik sıfatları: -(I)cI, -kAn, -gIn, -sIz",
         "Xarakter sifatlari: çalışkan (mehnatsevar), titiz (puxta), sabırlı (sabrli), cömert (saxiy), utangaç (uyatchan), açık sözlü (ochiq so'zli). Qo'shimchalar: -kAn: çalışkan, unutkan; -gIn: bıkkın, kırgın; -sIz: sabırsız, umursamaz. Zid ma'nolar: cömert - cimri."),
        ("Şart ve genelleme: -sA ... -DIr, -(y)An ... genellikle",
         "Umumiy xulosa: Harfleri büyük yazanlar genellikle kendine güvenir. Satırları yukarı kalkanlar iyimserdir. Bu \"-An + ism + -DIr\" tuzilmasi taxminiy umumlashtirishni beradi."),
    ],
    facts=[
        "belli ki = ma'lumki; anlaşılan = ko'rinishidan; -mIş gibi = ...gandek.",
        "-kAn (çalışkan), -gIn (bıkkın), -sIz (sabırsız) — sifat yasovchilar.",
        "Grafologiya qo'l yozuvini o'rganuvchi soha; ilmiy isboti cheklangan.",
        "Cömert ↔ cimri; sabırlı ↔ sabırsız; cesur ↔ korkak.",
    ],
    vocab=[
        ("el yazısı", "qo'l yozuvi", "El yazısı kişiliği yansıtır mı?", "Qo'l yozuvi shaxsiyatni aks ettiradimi?"),
        ("kişilik", "shaxsiyat", "Kişilik zamanla gelişir.", "Shaxsiyat vaqt o'tishi bilan shakllanadi."),
        ("karakter", "xarakter", "Güçlü bir karaktere sahip.", "Kuchli xarakterga ega."),
        ("çalışkan", "mehnatsevar", "Çalışkan bir öğrenciydi.", "Mehnatsevar o'quvchi edi."),
        ("titiz", "puxta, tartibli", "Titiz biri olduğu için hata yapmaz.", "Puxta inson bo'lgani uchun xato qilmaydi."),
        ("sabırlı", "sabrli", "Sabırlı insanlar başarır.", "Sabrli odamlar uddalaydi."),
        ("cömert", "saxiy", "Cömert biri hep yardım eder.", "Saxiy inson doim yordam beradi."),
        ("cimri", "xasis", "Cimri insanlar hiç harcamaz.", "Xasis odamlar hech narsa sarflamaydi."),
        ("utangaç", "uyatchan", "Utangaç çocuk konuşmadı.", "Uyatchan bola gapirmadi."),
        ("kendine güvenmek", "o'ziga ishonmoq", "Kendine güvenen kişi rahat konuşur.", "O'ziga ishongan kishi erkin gapiradi."),
        ("iyimser", "optimist", "İyimser insanlar hayatı sever.", "Optimist odamlar hayotni sevadi."),
        ("belli ki", "ma'lumki", "Belli ki çok çalışmış.", "Ma'lumki, ko'p ishlagan."),
    ],
    reading=("El yazısı kişiliği anlatır mı?",
        "Grafoloji, el yazısından kişilik özelliklerini yorumlamaya çalışan bir alandır. Uzmanlara göre harflerin büyüklüğü, satırların eğimi ve yazının basıncı yazanın karakteri hakkında ipuçları verebilir.\n\nÖrneğin harfleri büyük yazanlar genellikle dışa dönük ve kendine güvenli kabul edilir. Küçük yazanlar ise dikkatli ve içe dönük olabilir. Satırlar yukarı doğru kalkıyorsa yazarın iyimser olduğu düşünülür. Düzgün ve düzenli yazanların titiz biri olması muhtemeldir.\n\nAncak bilim insanları bu yöntemin tam olarak kanıtlanmadığını belirtir. El yazısı, yazanın o günkü ruh hâlinden ve yorgunluğundan da etkilenebilir. Bu nedenle sonuçlara ihtiyatla yaklaşmak gerekir.",
        [
            ("Grafoloji neyi yorumlamaya çalışır?", ["El yazısından kişilik özelliklerini", "Yıldızları", "Rüyaları", "Yüzü"]),
            ("Harfleri büyük yazanlar genellikle nasıl kabul edilir?", ["Dışa dönük ve kendine güvenli", "Utangaç", "Cimri", "Hasta"]),
            ("Satırlar yukarı kalkıyorsa ne düşünülür?", ["Yazar iyimserdir", "Yazar yorgundur", "Yazar sabırsızdır", "Yazar hastadır"]),
            ("Bilim insanları bu yöntem için ne diyor?", ["Tam olarak kanıtlanmadı", "Tamamen doğru", "Çok eski", "Çok pahalı"]),
            ("El yazısı neden etkilenebilir?", ["Ruh hâlinden ve yorgunluktan", "Mevsimden", "Rüzgârdan", "Kalemin rengi"]),
        ]),
    listening=([
        ("Ceren", "Bu mektubun yazısı çok düzgün. Belli ki yazan titiz biri."),
        ("Okan", "Bence sabırlı da. Satırlar eğri değil, düz."),
        ("Ceren", "Ama harfler küçük, biraz içe dönük olabilir."),
        ("Okan", "Anlaşılan sen grafoloji öğrenmişsin."),
        ("Ceren", "Biraz okudum ama kesin sonuç çıkmaz."),
        ("Okan", "Haklısın, yazı ruh hâline göre de değişir."),
    ], [
        ("Ceren xat yozuvchi haqida nima deydi?", ["Puxta kishi", "Dangasa", "Saxiy", "Uyatchan"]),
        ("Okan qanday xulosaga keladi?", ["Yozuv kayfiyatga qarab ham o'zgaradi", "Hamma narsa aniq", "Xat soxta", "Yozuv ahamiyatsiz"]),
    ]),
    practice=[
        ('c', "\"Ma'lumki, bu odam puxta.\"", ["Belli ki bu kişi titiz.", "Belli ki bu kişi titizdi mi.", "Belli bu kişi.", "Titiz bu belli kişi."]),
        ('c', "\"Ko'rinishidan, u kuni charchagan.\"", ["Anlaşılan o gün çok yorulmuş.", "Anlaşılan o gün yorulacak.", "Anlaşılan yorgun değil.", "Anlaşılan o gün."]),
        ('c', "\"Saxiy\" ning aksi:", ["cimri", "cömert", "sabırlı", "çalışkan"]),
        ('c', "\"Mehnatsevar\" turkchada:", ["çalışkan", "utangaç", "cimri", "korkak"]),
        ('o', "\"Harflarni katta yozganlar o'ziga ishonadi.\" gapini tuzing.", ["Harfleri", "büyük", "yazanlar", "kendine", "güvenir."]),
        ('o', "\"U sanki charchagandek ko'rinadi.\" gapini tuzing.", ["Çok", "yorulmuş", "gibi", "görünüyor."]),
    ],
    writing=("Do'stingizning xarakteri haqida 3 gap yozing (belli ki, anlaşılan dan foydalaning).",
             "Arkadaşım çok çalışkandır. Belli ki sabırlı biridir. Anlaşılan geleceğe iyimser bakıyor."),
    speaking=["Belli ki titiz biri.", "Anlaşılan çok yorulmuş.", "Çalışkan bir öğrenci.", "Kendine güveniyor gibi görünüyor."],
    test=[
        ("\"Belli ki\" nima degani?", ["ma'lumki", "balki", "hech", "faqat"]),
        ("\"Anlaşılan\" nima degani?", ["ko'rinishidan", "aniq emas", "albatta", "hech"]),
        ("\"-mIş gibi\" nima degani?", ["...gandek", "...maguncha", "...sa", "...gan sari"]),
        ("\"Titiz\" nima?", ["puxta, tartibli", "dangasa", "saxiy", "xasis"]),
        ("\"Cömert\" nima?", ["saxiy", "xasis", "uyatchan", "optimist"]),
        ("\"Cimri\" nima?", ["xasis", "saxiy", "sabrli", "mehnatsevar"]),
        ("\"Utangaç\" nima?", ["uyatchan", "jasur", "optimist", "ochiq"]),
        ("\"İyimser\" nima?", ["optimist", "pessimist", "uyatchan", "xasis"]),
        ("\"Karakter\" nima?", ["xarakter", "yozuv", "tuyg'u", "fikr"]),
        ("\"Grafoloji\" nimani o'rganadi?", ["qo'l yozuvini", "yulduzlarni", "yuzni", "tushni"]),
    ],
    bank=[
        ("\"Sabırsız\" nima?", ["sabrsiz", "sabrli", "saxiy", "optimist"]),
        ("\"Çalışkan\" ning aksi:", ["tembel", "titiz", "cömert", "iyimser"]),
        ("\"Açık sözlü\" nima?", ["ochiq so'zli", "yopiq", "uyatchan", "xasis"]),
        ("\"Kendine güvenmek\" nima?", ["o'ziga ishonmoq", "o'zidan shubhalanmoq", "qo'rqmoq", "yashirmoq"]),
        ("\"İçe dönük\" nima?", ["introvert", "ekstravert", "optimist", "saxiy"]),
        ("\"Dışa dönük\" nima?", ["ekstravert", "introvert", "uyatchan", "xasis"]),
        ("\"Ruh hâli\" nima?", ["kayfiyat", "kasallik", "yosh", "sana"]),
        ("\"İhtiyat\" nima?", ["ehtiyotkorlik", "tezkorlik", "tezlik", "xatolik"]),
        ("\"Eğim\" nima?", ["qiyalik", "shakl", "rang", "hajm"]),
        ("\"Basınç\" nima (yozuvda)?", ["bosim", "qiyalik", "rang", "hajm"]),
        ("\"İpucu\" nima?", ["ishora, belgi", "xulosa", "dalil", "natija"]),
        ("\"Muhtemel\" nima?", ["ehtimoliy", "mumkin emas", "aniq", "xato"]),
    ],
)

C = topic(
    'u8c', "C. Yüz Hatları ile Karakter Okumak — Yuz tuzilishi orqali xarakterni o'qish", 165, 170,
    goals=[
        "Taxmin va shubha ifodalarini (-DIr, -(y)AbIlIr, sanki, galiba, sanırım) qo'llash",
        "Tashqi ko'rinish va yuz tafsilotlarini ifodalovchi lug'atni bilish",
        "Insonlar haqida ehtiyotkorlik bilan fikr bildirish",
    ],
    blocks=[
        ("Tahmin ifadeleri: galiba, sanırım, herhalde, -DIr",
         "Kuchsiz ishonch: Galiba yorgun. (Ehtimol charchagan.) Sanırım o cömert biri. (Menimcha, u saxiy.) Herhalde sabırlıdır. -DIr qo'shimchasi ehtimolni rasmiy bildiradi: Alnı geniş olan zekidir (peshonasi keng odam aqlli bo'lsa kerak)."),
        ("Dış görünüş: -lI, -sIz, -(y)An",
         "Tashqi ko'rinish: Geniş alınlı (keng peshonali), uzun kirpikli, yuvarlak yüzlü (dumaloq yuzli). Sifat yasovchi -lI: gözlü, kaşlı; -sIz: sakalsız (soqolsiz). -(y)An bilan: Gülümseyen yüz (jilmaygan yuz)."),
        ("Genelleme yapmama: her zaman, her insan, ön yargı",
         "Ehtiyotkorlik: Bu her zaman doğru değildir. Her insan farklıdır. İlk izlenimle hüküm vermek yanlış olabilir. Ön yargı (oldindan hukm) insonlarni noto'g'ri baholashga olib keladi."),
    ],
    facts=[
        "galiba, sanırım, herhalde — kuchsiz ishonch bildiradi.",
        "Yuz tuzilishi bo'yicha xarakterni aniqlash (fiziognomiya) qadimdan mavjud, ammo ilmiy isbotlanmagan.",
        "-lI ega bo'lishni, -sIz yo'qlikni bildiradi: gözlü / gözsüz.",
        "Birinchi taassurot ba'zan aldamchi bo'lishi mumkin.",
    ],
    vocab=[
        ("yüz hatları", "yuz tuzilishi", "Yüz hatları insanın duygularını yansıtır.", "Yuz tuzilishi insonning tuyg'ularini aks ettiradi."),
        ("alın", "peshona", "Geniş alınlı biri zeki görünür.", "Keng peshonali kishi aqlli ko'rinadi."),
        ("kaş", "qosh", "Kalın kaşları var.", "Qalin qoshlari bor."),
        ("kirpik", "kiprik", "Uzun kirpikleri güzel.", "Uzun kipriklari chiroyli."),
        ("burun", "burun", "İnce bir burnu var.", "Ingichka burni bor."),
        ("çene", "iyak", "Çenesi belirgin.", "Iyagi ko'zga tashlanadi."),
        ("yanak", "yonoq", "Yanakları pembe.", "Yonoqlari pushti."),
        ("gülümsemek", "jilmaymoq", "Gülümseyen insanlar sıcak görünür.", "Jilmaygan odamlar iliq ko'rinadi."),
        ("izlenim", "taassurot", "İlk izlenim önemlidir.", "Birinchi taassurot muhim."),
        ("ön yargı", "oldindan hukm", "Ön yargılı olmamalıyız.", "Oldindan hukmga ega bo'lmasligimiz kerak."),
        ("yansıtmak", "aks ettirmoq", "Yüz ruh hâlini yansıtır.", "Yuz kayfiyatni aks ettiradi."),
        ("belirgin", "ko'zga tashlanuvchi", "Belirgin bir özellik.", "Ko'zga tashlanuvchi xususiyat."),
    ],
    reading=("Yüze bakıp karakter okunur mu?",
        "İnsanlar tarih boyunca yüz hatlarından karakter okumaya çalışmıştır. Antik Yunan'da bile alnı geniş olanların zeki, kalın kaşlıların kararlı olduğu düşünülürdü. Günümüzde de ilk görüşte insanlar hakkında hızlı yargılara varıyoruz.\n\nPsikologlar ise ilk izlenimin yanıltıcı olabileceğini söylüyor. Gülümseyen bir yüz sıcak görünür, ama bu kişinin her zaman iyi niyetli olduğu anlamına gelmez. Araştırmalar, yüz hatlarıyla kişilik arasında kesin bir ilişki bulunmadığını gösteriyor.\n\nBu yüzden insanları tanımadan yargılamamak gerekir. Herkes farklıdır ve karakteri anlamanın en iyi yolu, onunla zaman geçirip konuşmaktır. Ön yargı, çoğu zaman haksız sonuçlara yol açar.",
        [
            ("Antik Yunan'da geniş alınlı kişiler için ne düşünülürdü?", ["Zeki oldukları", "Cesur oldukları", "Cimri oldukları", "Hasta oldukları"]),
            ("Psikologlar ilk izlenim için ne diyor?", ["Yanıltıcı olabilir", "Her zaman doğrudur", "Önemsizdir", "Bilimseldir"]),
            ("Araştırmalar ne gösteriyor?", ["Yüz hatları ile kişilik arasında kesin ilişki yok", "Kesin ilişki var", "Sadece gözler önemli", "Sadece yaş önemli"]),
            ("Karakteri anlamanın en iyi yolu nedir?", ["Onunla zaman geçirip konuşmak", "Fotoğrafına bakmak", "Adını öğrenmek", "Kıyafetine bakmak"]),
            ("Ön yargı neye yol açar?", ["Haksız sonuçlara", "Doğru kararlara", "Arkadaşlığa", "Bilgiye"]),
        ]),
    listening=([
        ("Merve", "Şu yeni gelen çocuk galiba çok utangaç."),
        ("Kaan", "Neden öyle düşünüyorsun?"),
        ("Merve", "Sürekli yere bakıyor, sanırım konuşmaktan çekiniyor."),
        ("Kaan", "Belki de sadece yorgundur. İlk izlenime güvenme."),
        ("Merve", "Haklısın. Gidip tanışalım."),
        ("Kaan", "Evet, ön yargısız olmak lazım."),
    ], [
        ("Merve yangi bola haqida nima o'ylaydi?", ["Uyatchan", "Jasur", "Yoqimtoy", "Kasal"]),
        ("Kaan nimani maslahat beradi?", ["Birinchi taassurotga ishonmaslikni", "Uni e'tiborsiz qoldirishni", "Uni masxara qilishni", "Ketishni"]),
    ]),
    practice=[
        ('c', "\"Ehtimol u charchagan.\"", ["Galiba yorgun.", "Kesin yorgun.", "Hiç yorgun.", "Yorgundu."]),
        ('c', "\"Menimcha, u saxiy.\"", ["Sanırım o cömert.", "O cömert değil mi.", "O cömertlerdir.", "Cömert sanırım ki."]),
        ('c', "\"Keng peshonali\" turkchada:", ["geniş alınlı", "uzun burunlu", "kalın kaşlı", "ince bıyıklı"]),
        ('c', "\"Taassurot\" turkchada:", ["izlenim", "yanak", "alın", "çene"]),
        ('o', "\"Birinchi taassurot muhim.\" gapini tuzing.", ["İlk", "izlenim", "önemlidir."]),
        ('o', "\"Har bir odam har xil.\" gapini tuzing.", ["Her", "insan", "farklıdır."]),
    ],
    writing=("Chiroyli, ammo oldindan hukmga qarshi 3 gap yozing (galiba, sanırım).",
             "Bir insanı ilk görüşte yargılamamak gerekir. Galiba herkesin farklı bir hikâyesi var. Sanırım tanıyınca düşüncelerimiz değişir."),
    speaking=["Galiba çok yorgun.", "Sanırım o cömert biri.", "İlk izlenim yanıltıcı olabilir.", "Her insan farklıdır."],
    test=[
        ("\"Galiba\" nima degani?", ["ehtimol", "albatta", "hech", "faqat"]),
        ("\"Sanırım\" nima degani?", ["menimcha", "aniq", "albatta", "hech"]),
        ("\"Herhalde\" nima degani?", ["ehtimol, aftidan", "albatta emas", "hech", "faqat"]),
        ("\"Alın\" nima?", ["peshona", "burun", "iyak", "qosh"]),
        ("\"Kaş\" nima?", ["qosh", "kiprik", "yonoq", "peshona"]),
        ("\"Kirpik\" nima?", ["kiprik", "qosh", "burun", "iyak"]),
        ("\"Çene\" nima?", ["iyak", "burun", "yonoq", "peshona"]),
        ("\"Yanak\" nima?", ["yonoq", "iyak", "burun", "qosh"]),
        ("\"Gülümsemek\" nima?", ["jilmaymoq", "yig'lamoq", "g'azablanmoq", "uxlamoq"]),
        ("\"Ön yargı\" nima?", ["oldindan hukm", "xulosa", "izlanish", "taassurot"]),
    ],
    bank=[
        ("\"Yüz hatları\" nima?", ["yuz tuzilishi", "yuz rangi", "yosh", "kayfiyat"]),
        ("\"Yansıtmak\" nima?", ["aks ettirmoq", "yashirmoq", "yo'qotmoq", "yozmoq"]),
        ("\"Belirgin\" nima?", ["ko'zga tashlanuvchi", "sezilmas", "kichik", "eski"]),
        ("\"Geniş alınlı\" nima?", ["keng peshonali", "uzun burunli", "dumaloq yuzli", "yosh"]),
        ("\"Gözlü\" nima?", ["ko'zli", "ko'zsiz", "ko'rmaydigan", "yumuq"]),
        ("\"Sakalsız\" nima?", ["soqolsiz", "soqolli", "mo'ylovli", "kalta"]),
        ("\"Yargılamak\" nima?", ["hukm qilmoq", "maqtamoq", "tinglamoq", "o'rganmoq"]),
        ("\"Yanıltıcı\" nima?", ["aldamchi", "aniq", "yangi", "kam"]),
        ("\"Haksız\" nima?", ["nohaq", "to'g'ri", "adolatli", "qonuniy"]),
        ("\"İlk görüşte\" nima?", ["birinchi ko'rishda", "oxirgi marta", "ikkinchi marta", "uzoq vaqtdan keyin"]),
        ("\"Kararlı\" nima?", ["qat'iyatli", "ikkilanuvchan", "tanbal", "uyatchan"]),
        ("\"İyi niyetli\" nima?", ["yaxshi niyatli", "yomon niyatli", "tanbal", "uyatchan"]),
    ],
)

TOPICS = [A, B, C]
