# Generated by Django 6.1.1 on 2026-09-24 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('presentation', 'Taqdimot'), ('game_timeline', "O'yin: xronologiya"), ('game_matching', "O'yin: moslashtirish")], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('ai_provider', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assets', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='history_ai.topic')),
            ],
        ),
    ]
