# Generated by Django 6.1.1 on 2026-09-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_ai', '0002_generatedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedasset',
            name='kind',
            field=models.CharField(choices=[('presentation', 'Taqdimot'), ('game_timeline', "O'yin: xronologiya"), ('game_matching', "O'yin: moslashtirish"), ('game_fill_blank', "O'yin: bo'sh joyni to'ldirish")], max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='history_ai.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedasset',
            unique_together={('topic', 'kind')},
        ),
    ]
