# Generated by Django 6.1.1 on 2026-09-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_ai', '0011_certificate_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Foydalanuvchi sozlamasi', 'verbose_name_plural': 'Foydalanuvchi sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='xpevent',
            options={'verbose_name': 'Ball voqeasi', 'verbose_name_plural': 'Ball voqealari'},
        ),
    ]
