# Generated by Django 6.1.1 on 2026-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history_ai", "0013_dailyactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="email_reminders",
            field=models.BooleanField(
                default=True, verbose_name="Streak eslatma emaillari"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="last_reminder_sent",
            field=models.DateField(blank=True, null=True),
        ),
    ]
