# Generated by Django 6.1.1 on 2026-10-07 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_ai', '0014_lessonfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('per_stage', models.JSONField(default=dict)),
                ('level_key', models.CharField(blank=True, max_length=20)),
                ('level_label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='history_ai.book')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='history_ai.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daraja natijasi',
                'verbose_name_plural': 'Daraja natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
