# Generated by Django 6.1.1 on 2026-10-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_ai', '0016_examsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_bank', to='history_ai.topic')),
            ],
        ),
    ]
