# Generated by Django 6.1.1 on 2026-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_ai', '0017_exambank'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='tab_switches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
